In [1]:
# 라이브러리 로드
from IPython.display import display
from pprint import pprint

import pandas as pd

In [2]:
# 성공한_FnB채널 데이터 로드
df_success_fnb = pd.read_csv("../../data/results/preprocessed/fnb_longform_success_data.csv", encoding='utf-8')

df_success_fnb.info()

<class 'pandas.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 38 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   video_id                    694 non-null    str
 1   title                       694 non-null    str
 2   channel_id                  694 non-null    str
 3   channel_title               694 non-null    str
 4   description                 694 non-null    str
 5   upload_date                 694 non-null    str
 6   tags                        694 non-null    str
 7   view_count                  694 non-null    int64
 8   like_count                  694 non-null    float64
 9   comment_count               694 non-null    float64
 10  duration                    694 non-null    float64
 11  definition                  694 non-null    str
 12  license                     694 non-null    str
 13  embeddable                  694 non-null    bool
 14  has_paid_product_placement  694 non-null    bool
 15  thumbnail                   694 non-null    str
 16  caption                     694 non-null    bool
 17  final_url                   694 non-null    str
 18  instream_type               694 non-null    str
 19  channel_handle              694 non-null    str
 20  channel_tier                694 non-null    str
 21  description_missing_flag    694 non-null    int64
 22  tags_missing_flag           694 non-null    int64
 23  er                          694 non-null    float64
 24  ler                         694 non-null    float64
 25  cer                         694 non-null    float64
 26  wei                         694 non-null    float64
 27  description_length          694 non-null    int64
 28  category_name               694 non-null    str
 29  upload_year                 694 non-null    int64
 30  upload_month                694 non-null    int64
 31  upload_dayofweek            694 non-null    str
 32  upload_hour                 694 non-null    int64
 33  tags_count                  694 non-null    int64
 34  upload_quarter              694 non-null    int64
 35  upload_ym_quarter           694 non-null    str
 36  upload_ymd                  694 non-null    str
 37  grade                       694 non-null    str
dtypes: bool(3), float64(7), int64(9), str(19)
memory usage: 1.1 MB

In [3]:
# 실패한_FnB채널 데이터 로드
df_fail_fnb = pd.read_csv("../../data/results/preprocessed/fnb_longform_fail_data.csv", encoding='utf-8')

df_fail_fnb.info()

<class 'pandas.DataFrame'>
RangeIndex: 723 entries, 0 to 722
Data columns (total 38 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   video_id                    723 non-null    str
 1   title                       723 non-null    str
 2   channel_id                  723 non-null    str
 3   channel_title               723 non-null    str
 4   description                 723 non-null    str
 5   upload_date                 723 non-null    str
 6   tags                        723 non-null    str
 7   view_count                  723 non-null    int64
 8   like_count                  723 non-null    float64
 9   comment_count               723 non-null    float64
 10  duration                    723 non-null    float64
 11  definition                  723 non-null    str
 12  license                     723 non-null    str
 13  embeddable                  723 non-null    bool
 14  has_paid_product_placement  723 non-null    bool
 15  thumbnail                   723 non-null    str
 16  caption                     723 non-null    bool
 17  final_url                   723 non-null    str
 18  instream_type               723 non-null    str
 19  channel_handle              723 non-null    str
 20  channel_tier                723 non-null    str
 21  description_missing_flag    723 non-null    int64
 22  tags_missing_flag           723 non-null    int64
 23  er                          723 non-null    float64
 24  ler                         723 non-null    float64
 25  cer                         723 non-null    float64
 26  wei                         723 non-null    float64
 27  description_length          723 non-null    int64
 28  category_name               723 non-null    str
 29  upload_year                 723 non-null    int64
 30  upload_month                723 non-null    int64
 31  upload_dayofweek            723 non-null    str
 32  upload_hour                 723 non-null    int64
 33  tags_count                  723 non-null    int64
 34  upload_quarter              723 non-null    int64
 35  upload_ym_quarter           723 non-null    str
 36  upload_ymd                  723 non-null    str
 37  grade                       723 non-null    str
dtypes: bool(3), float64(7), int64(9), str(19)
memory usage: 1.1 MB

In [4]:
# 성공한_IT채널 데이터 로드
df_success_it = pd.read_csv("../../data/results/preprocessed/it_longform_success_data.csv", encoding='utf-8')

df_success_it.info()

<class 'pandas.DataFrame'>
RangeIndex: 1527 entries, 0 to 1526
Data columns (total 38 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   video_id                    1527 non-null   str
 1   title                       1527 non-null   str
 2   channel_id                  1527 non-null   str
 3   channel_title               1527 non-null   str
 4   description                 1527 non-null   str
 5   upload_date                 1527 non-null   str
 6   tags                        1527 non-null   str
 7   view_count                  1527 non-null   int64
 8   like_count                  1527 non-null   float64
 9   comment_count               1527 non-null   float64
 10  duration                    1527 non-null   float64
 11  definition                  1527 non-null   str
 12  license                     1527 non-null   str
 13  embeddable                  1527 non-null   bool
 14  has_paid_product_placement  1527 non-null   bool
 15  thumbnail                   1527 non-null   str
 16  caption                     1527 non-null   bool
 17  final_url                   1527 non-null   str
 18  instream_type               1527 non-null   str
 19  channel_handle              1527 non-null   str
 20  channel_tier                1527 non-null   str
 21  description_missing_flag    1527 non-null   int64
 22  tags_missing_flag           1527 non-null   int64
 23  er                          1527 non-null   float64
 24  ler                         1527 non-null   float64
 25  cer                         1527 non-null   float64
 26  wei                         1527 non-null   float64
 27  description_length          1527 non-null   int64
 28  category_name               1527 non-null   str
 29  upload_year                 1527 non-null   int64
 30  upload_month                1527 non-null   int64
 31  upload_dayofweek            1527 non-null   str
 32  upload_hour                 1527 non-null   int64
 33  tags_count                  1527 non-null   int64
 34  upload_quarter              1527 non-null   int64
 35  upload_ym_quarter           1527 non-null   str
 36  upload_ymd                  1527 non-null   str
 37  grade                       1527 non-null   str
dtypes: bool(3), float64(7), int64(9), str(19)
memory usage: 2.6 MB

In [5]:
# 실패한_IT채널 데이터 로드
df_fail_it = pd.read_csv("../../data/results/preprocessed/it_longform_fail_data.csv", encoding='utf-8')

df_fail_it.info()

<class 'pandas.DataFrame'>
RangeIndex: 1241 entries, 0 to 1240
Data columns (total 38 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   video_id                    1241 non-null   str
 1   title                       1241 non-null   str
 2   channel_id                  1241 non-null   str
 3   channel_title               1241 non-null   str
 4   description                 1241 non-null   str
 5   upload_date                 1241 non-null   str
 6   tags                        1241 non-null   str
 7   view_count                  1241 non-null   int64
 8   like_count                  1241 non-null   float64
 9   comment_count               1241 non-null   float64
 10  duration                    1241 non-null   float64
 11  definition                  1241 non-null   str
 12  license                     1241 non-null   str
 13  embeddable                  1241 non-null   bool
 14  has_paid_product_placement  1241 non-null   bool
 15  thumbnail                   1241 non-null   str
 16  caption                     1241 non-null   bool
 17  final_url                   1241 non-null   str
 18  instream_type               1241 non-null   str
 19  channel_handle              1241 non-null   str
 20  channel_tier                1241 non-null   str
 21  description_missing_flag    1241 non-null   int64
 22  tags_missing_flag           1241 non-null   int64
 23  er                          1241 non-null   float64
 24  ler                         1241 non-null   float64
 25  cer                         1241 non-null   float64
 26  wei                         1241 non-null   float64
 27  description_length          1241 non-null   int64
 28  category_name               1241 non-null   str
 29  upload_year                 1241 non-null   int64
 30  upload_month                1241 non-null   int64
 31  upload_dayofweek            1241 non-null   str
 32  upload_hour                 1241 non-null   int64
 33  tags_count                  1241 non-null   int64
 34  upload_quarter              1241 non-null   int64
 35  upload_ym_quarter           1241 non-null   str
 36  upload_ymd                  1241 non-null   str
 37  grade                       1241 non-null   str
dtypes: bool(3), float64(7), int64(9), str(19)
memory usage: 1.9 MB

---
### 테스트 데이터 제작

In [6]:
# 테스트 데이터 추출 (성공한 영상)
df_success_fnb_test = df_success_fnb.iloc[501:503]

df_success_fnb_test.head(1)

,video_id,title,channel_id,channel_title,description,upload_date,tags,view_count,like_count,comment_count,...,category_name,upload_year,upload_month,upload_dayofweek,upload_hour,tags_count,upload_quarter,upload_ym_quarter,upload_ymd,grade
501,3KuJZy8Ol2s,화려한 촛농 데코가 케이크를 감싸네,UCiyg3rAdPOJN4eKAgAs5FOQ,SPC그룹,케이크에 휘리릭 초코를 흘려주면\n고품격 #멜팅케이크 가 짜잔! 🎂\n\n#촛농데코...,2023-05-31 08:15:00+00:00,"촛농, 촛농케이크, 아이싱, 휘핑, 생크림, 케이크추천, 케이크꾸미기, 케이크만들기...",200,9.0,0.0,...,브이로그/라이프스타일,2023,5,수요일,8,13,2,2023-Q2,2023-05-31,성공

In [7]:
# 테스트 데이터 추출 (실패한 영상)
df_fail_fnb_test = df_fail_fnb.iloc[516:518]

df_fail_fnb_test.head(1)

,video_id,title,channel_id,channel_title,description,upload_date,tags,view_count,like_count,comment_count,...,category_name,upload_year,upload_month,upload_dayofweek,upload_hour,tags_count,upload_quarter,upload_ym_quarter,upload_ymd,grade
516,MUd2Y78Zh58,Samyang In Video [Full ver],UCxHML2F6f8c5L7N2-0gF6Vw,삼양그룹,-,2024-12-03 08:36:33+00:00,"삼양그룹, 삼양, samyang, 삼양사",379,0.0,0.0,...,예능/오락 콘텐츠,2024,12,화요일,8,4,4,2024-Q4,2024-12-03,실패

In [8]:
# 테스트 데이터 추출 (성공한 영상)
df_success_it_test = df_success_it.iloc[1500:1502]

df_success_it_test.head(1)

,video_id,title,channel_id,channel_title,description,upload_date,tags,view_count,like_count,comment_count,...,category_name,upload_year,upload_month,upload_dayofweek,upload_hour,tags_count,upload_quarter,upload_ym_quarter,upload_ymd,grade
1500,HHzhqIQL7iQ,월요라이브 | 뮤지컬은밀하게위대하게 THE LAST ‘나는 두렵습니다’ | 김찬호 ...,UC_7nyGIBuYk6HBBBftbn3kg,NOL,월요라이브에서 만났던 뮤지컬은밀하게위대하게 THE LAST 라이브 무대!\n그 중 ...,2026-02-27 01:30:17+00:00,"nol, 야놀자, yanolja, 월요라이브, 뮤지컬은밀하게위대하게, 뮤지컬은밀하게...",773,16.0,1.0,...,예능/오락 콘텐츠,2026,2,금요일,1,13,1,2026-Q1,2026-02-27,성공

In [9]:
# 테스트 데이터 추출 (실패한 영상)
df_fail_it_test = df_fail_it.iloc[12:14]

df_fail_it_test.head(1)

,video_id,title,channel_id,channel_title,description,upload_date,tags,view_count,like_count,comment_count,...,category_name,upload_year,upload_month,upload_dayofweek,upload_hour,tags_count,upload_quarter,upload_ym_quarter,upload_ymd,grade
12,Bv27XaEZ5ek,갤럭시 Z 플립7과 함께 떠나는 우정 여행 | 유쓰피릿,UCp3BSINVC7Ggj4kChEUiy7Q,LG유플러스 (LG Uplus),유쓰피릿이 말아주는 갤럭시와 함께하는 우정 여행!\n갤럭시 Z 플립7만큼 매력 넘치...,2025-09-04 02:09:44+00:00,"#LG유플러스, #유쓰, #유쓰피릿, #유쓰트립, #삼성전자, #갤럭시, #Z플립7...",84019,200.0,3.0,...,예능/오락 콘텐츠,2025,9,목요일,2,8,3,2025-Q3,2025-09-04,실패

In [10]:
df_test = pd.concat([df_success_fnb_test, df_fail_fnb_test, df_success_it_test, df_fail_it_test], ignore_index=True)

In [11]:
df_test.head(10)

,video_id,title,channel_id,channel_title,description,upload_date,tags,view_count,like_count,comment_count,...,category_name,upload_year,upload_month,upload_dayofweek,upload_hour,tags_count,upload_quarter,upload_ym_quarter,upload_ymd,grade
0,3KuJZy8Ol2s,화려한 촛농 데코가 케이크를 감싸네,UCiyg3rAdPOJN4eKAgAs5FOQ,SPC그룹,케이크에 휘리릭 초코를 흘려주면\n고품격 #멜팅케이크 가 짜잔! 🎂\n\n#촛농데코...,2023-05-31 08:15:00+00:00,"촛농, 촛농케이크, 아이싱, 휘핑, 생크림, 케이크추천, 케이크꾸미기, 케이크만들기...",200,9.0,0.0,...,브이로그/라이프스타일,2023,5,수요일,8,13,2,2023-Q2,2023-05-31,성공
1,5Rvp36ZnOf8,이 안에 5색 크림 있다.. 크림 듬뿍 채운 소라빵,UCiyg3rAdPOJN4eKAgAs5FOQ,SPC그룹,돌돌 말린 #소라빵 안에 형형색색 #크림 이 빵긋-\n보기도 좋고 맛은 더 좋은 5...,2023-05-26 09:15:00+00:00,"빵, 토핑, 초코크림, 5색크림, 5색크림소라빵, 레시피, 노하우, 제조법, 홈베이...",215,6.0,1.0,...,브이로그/라이프스타일,2023,5,금요일,9,11,2,2023-Q2,2023-05-26,성공
2,MUd2Y78Zh58,Samyang In Video [Full ver],UCxHML2F6f8c5L7N2-0gF6Vw,삼양그룹,-,2024-12-03 08:36:33+00:00,"삼양그룹, 삼양, samyang, 삼양사",379,0.0,0.0,...,예능/오락 콘텐츠,2024,12,화요일,8,4,4,2024-Q4,2024-12-03,실패
3,WjnPNCqbhx4,영상으로 보는 삼양 [사회공헌편],UCxHML2F6f8c5L7N2-0gF6Vw,삼양그룹,-,2024-12-03 08:30:24+00:00,"삼양그룹, 삼양, samyang, 삼양사",82,0.0,0.0,...,예능/오락 콘텐츠,2024,12,화요일,8,4,4,2024-Q4,2024-12-03,실패
4,HHzhqIQL7iQ,월요라이브 | 뮤지컬은밀하게위대하게 THE LAST ‘나는 두렵습니다’ | 김찬호 ...,UC_7nyGIBuYk6HBBBftbn3kg,NOL,월요라이브에서 만났던 뮤지컬은밀하게위대하게 THE LAST 라이브 무대!\n그 중 ...,2026-02-27 01:30:17+00:00,"nol, 야놀자, yanolja, 월요라이브, 뮤지컬은밀하게위대하게, 뮤지컬은밀하게...",773,16.0,1.0,...,예능/오락 콘텐츠,2026,2,금요일,1,13,1,2026-Q1,2026-02-27,성공
5,BCXC1teZEHE,"월요라이브 | 뮤지컬은밀하게위대하게 THE LAST ‘빨래’ | 백인태, 니엘, 민...",UC_7nyGIBuYk6HBBBftbn3kg,NOL,"🪖백인태, 니엘, 민규 배우가 월요라이브에서 부른 \n뮤지컬 은밀하게 위대하게 : ...",2026-02-27 01:00:15+00:00,"nol, 야놀자, yanolja, NOL티켓, 월요라이브, 뮤지컬은밀하게위대하게, ...",1064,43.0,2.0,...,예능/오락 콘텐츠,2026,2,금요일,1,16,1,2026-Q1,2026-02-27,성공
6,Bv27XaEZ5ek,갤럭시 Z 플립7과 함께 떠나는 우정 여행 | 유쓰피릿,UCp3BSINVC7Ggj4kChEUiy7Q,LG유플러스 (LG Uplus),유쓰피릿이 말아주는 갤럭시와 함께하는 우정 여행!\n갤럭시 Z 플립7만큼 매력 넘치...,2025-09-04 02:09:44+00:00,"#LG유플러스, #유쓰, #유쓰피릿, #유쓰트립, #삼성전자, #갤럭시, #Z플립7...",84019,200.0,3.0,...,예능/오락 콘텐츠,2025,9,목요일,2,8,3,2025-Q3,2025-09-04,실패
7,H_cdM3NijjM,[U+소호] AI 전화 이용 방법을 알고 싶어요 (U+우리가게패키지 앱),UCp3BSINVC7Ggj4kChEUiy7Q,LG유플러스 (LG Uplus),이 영상은 AI 성우(ixi-TTS) 목소리로 제작되었어요. 😊\n\n[ 설정하기]...,2025-06-13 05:42:01+00:00,"매장관리, 우리가게패키지, LG, LG유플러스",6702,7.0,0.0,...,예능/오락 콘텐츠,2025,6,금요일,5,4,2,2025-Q2,2025-06-13,실패

In [12]:
df_test.to_csv("../../works/Haeun/thumbnail_analysis/data/썸네일분석모델_테스트성능확인용-1.csv", index=False, encoding='utf-8-sig')