In [1]:

# ========================================
# 필요한 라이브러리를 불러옵니다
# ========================================

import os
import time
import platform
from pprint import pprint
from typing import List, Literal, Optional

import requests
import json
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from pydantic_ai import Agent, ModelRetry
from pydantic_ai.models.google import GoogleModelSettings

# 운영체제별 한글 폰트 설정
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'NanumGothic'

# 마이너스 기호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

# 출력 짤림 방지
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 50)

# .env 파일에서 API 키 로드
load_dotenv()
api_key = os.getenv('GEMINI_API_KEY')
gemini_model = os.getenv('GEMINI_MODEL', 'gemini-3.1-flash-lite-preview')
youtube_api_key = os.getenv('YOUTUBE_API_KEY')
youtube_api_key2 = os.getenv('YOUTUBE_API_KEY2')
youtube_api_key3 = os.getenv('YOUTUBE_API_KEY3')

# PydanticAI는 GEMINI_API_KEY 환경변수를 자동으로 인식합니다
# 모델 ID 형식: 'google-gla:{모델명}'
model_id = f'google-gla:{gemini_model}'

# API 키 유효성 검사
api_key_valid = api_key and 'YOUR_API_KEY' not in api_key
print(f"API 키 설정 확인: {'O' if api_key_valid else 'X'}")
if not api_key_valid:
    print("[주의] .env 파일에서 GEMINI_API_KEY를 실제 API 키로 설정해주세요!")
print(f"모델 확인: {model_id}")

youtube_api_key_valid = youtube_api_key and 'YOUR_API_KEY' not in youtube_api_key
print(f"유튜브 API 키 설정 확인: {'O' if youtube_api_key_valid else 'X'}")
if not api_key_valid:
    print("[주의] .env 파일에서 YOUTUBE_API_KEY를 실제 API 키로 설정해주세요!")

# API 호출 간격 (초) - 무료 플랜에 맞게 조정
API_DELAY = 3

API 키 설정 확인: O
모델 확인: google-gla:gemini-3.1-flash-lite-preview
유튜브 API 키 설정 확인: O

In [7]:

# =============================================================
# IT 기업리스트
# 생성된 데이터 프레임: it_channel_list
# 생성된 csv 파일 이름: IT채널정보조회.csv
# =============================================================
with open('./data/checkpoint_IT(배치처리).json', encoding='utf-8') as f:
    it_data = json.load(f) # Ai Agent가 정리한 IT기업의 채널 리스트 로드

it_records = [] # 데이터를 담을 빈 리스트 생성

# channels에 들어있는 dict 확장
for company in it_data:
    company_name = company['company_name']
    has_official = company['has_official']
    
    for ch in company['channels']:
        it_records.append({
            'company_name': company_name,
            'has_official': has_official,
            'channel_id': ch.get('channel_id'),
            'channel_name': ch.get('channel_name'),
            'channel_handle': ch.get('channel_handle'),
            'channel_url': ch.get('channel_url'),
            'channel_reason': ch.get('channel_reason')
        })

it_channel_list = pd.DataFrame(it_records)
it_channel_list.to_csv('./data/IT채널정보조회.csv')
it_channel_list.head()

# =============================================================
# 작성된 기업 리스트를 기반으로 수기로 하나하나 검증 중 . . .
# 완료!
# ============================================================= 

# 기업 채널 리스트 가져오기
it_channel_list2 = pd.read_csv('./data/IT리스트 정리.csv', encoding='euc-kr')

# 채널이 없는 기업 제외
it_channel_list2 = it_channel_list2.loc[it_channel_list2['channel_name'].notna(), ['company_name', 'channel_name', 'channel_id', 'channel_handle']]

# 정리된 채널 개수 확인
print('정리된 기업 채널 개수 :' , len(it_channel_list2['company_name']), '개')

정리된 기업 채널 개수 : 49 개

In [8]:

# =============================================================
# FOOD 기업리스트
# 생성된 데이터 프레임: food_channel_list
# 생성된 csv 파일 이름: FOOD채널정보조회.csv
# =============================================================

with open('./data/checkpoint_FOOD(배치처리).json', encoding='utf-8') as f:
    food_data = json.load(f) # Ai Agent가 정리한 FOOD기업의 채널 리스트 로드

food_records = [] # 데이터를 담을 빈 리스트 생성

# channels에 들어있는 dict 확장
for company in food_data:
    company_name = company['company_name']
    has_official = company['has_official']
    
    for ch in company['channels']:
        food_records.append({
            'company_name': company_name,
            'has_official': has_official,
            'channel_id': ch.get('channel_id'),
            'channel_name': ch.get('channel_name'),
            'channel_handle': ch.get('channel_handle'),
            'channel_url': ch.get('channel_url'),
            'channel_reason': ch.get('channel_reason')
        })

food_channel_list = pd.DataFrame(food_records)
food_channel_list.to_csv('./data/FOOD채널정보조회.csv')
food_channel_list.head()

# =============================================================
# 작성된 기업 리스트를 기반으로 수기로 하나하나 검증 중 . . .
# 완료!
# ============================================================= 

# 기업 채널리스트 가져오기
food_channel_list2 = pd.read_csv('./data/Book(실제 검증 채널).csv', encoding='utf-8-sig')

# 채널이 없는 기업 제외
food_channel_list2 = food_channel_list2.loc[food_channel_list2['channel_name'].notna(), ['company_name', 'channel_name', 'channel_id', 'channel_handle']]

# 정리된 채널 개수 확인
print('정리된 기업 채널 개수', len(food_channel_list2['company_name']), '개')

정리된 기업 채널 개수 70 개

---
#### 채널 정보 수집
   수집 목적:
   1. 채널 정보를 분석하여 사용할 최종 채널 리스트를 선정하기 위함.
   2. 이후 영상정보 검색시 채널 id 정보가 필요.

---

In [9]:
# =============================================================
# 채널 정보 불러오기 API : get_channel_info(arg1, arg2, arg3, arg4)
# arg1: 채널 정보를 불러올 때 사용할 유튜브 API키 입니다. (필수)
# arg2: 정보를 불러올 채널의 핸들명 입니다. (arg2, arg3 중 하나만 선택 입력)
# arg3: 정보를 불러올 채널의 핸들명 입니다. (arg2, arg3 중 하나만 선택 입력)
# arg4: 채널의 정보를 담을 리스트 변수명 입니다. 함수가 동작되기 전에 미리 생성되어 있어야 합니다.
# 
# [불러올 정보]
# 1. 채널 아이디(channel_id): 채널이 가지고 있는 고유 아이디 값입니다.
#   - 이후에 유튜브 검색 API 함수에서 쓰입니다. (채널 별 영상 아이디를 가져올 거임)
# 2. 채널 이름(title): 불러올 채널의 이름입니다.
# 3. 채널 설명(description): 채널에 대한 설명입니다.
# 4. 구독자 수(subscriber_count): 채널의 구독자 수입니다.
# 5. 총 조회수(view_count): 채널 모든 영상의 조회수를 합한 값입니다.
# 6. 총 영상수(video_count): 채널이 업로드한 공개된 영상의 개수입니다. (비공개 영상 포함 X)
# 7. 채널 썸네일(thumbnails): 채널의 썸네일입니다. url형식으로 제공됩니다.
# 8. 채널 개설일(created_date): 채널의 개설 날짜입니다.
# 
# 사용할 API: 유튜브 채널 API
#   - 비용: 채널 1개 당 1 유닛
#
# ※ 주의사항
#   - 이 함수는 handle의 리스트나, channel_id의 리스트를 받아서 한꺼번에 출력할 수 없습니다.
#   - 따라서 handle, channel_id는 함수에 한개씩만 들어가야 합니다. (리스트 넣지 말라는 얘기입니다.)
#   - 여러 개의 기업 채널에 대해서 정보를 얻고 싶다면, 반복문 속에 함수를 넣으십시오.
#   - 이 함수는 사용한 유닛량을 알려주지 않습니다. 정보를 얻고자 하는 채널의 수와 유닛량이 같다는 점을 참고해주십시오.
# =============================================================

def get_channel_info(api_key, handle=None, channel_id=None, list_name=None):
    url = 'https://www.googleapis.com/youtube/v3/channels'
    
    params = {
        'part': 'snippet,statistics,brandingSettings',
        'key':api_key
    }
    
    if handle:
        params['forHandle'] = handle
    elif channel_id:
        params['id'] = channel_id
    else:
        raise ValueError('handle 또는 channel_id 중 반드시 하나는 입력해야 합니다.')
    
    if list_name == None:
        raise ValueError('채널 정보를 받을 리스트를 입력해주세요')
    r = requests.get(url, params=params, timeout=30)
    r.raise_for_status()
    data = r.json()
    
    if not data.get('items'):
        return None
    ch = data['items'][0]
    temp ={
        'channel_id': ch['id'], # 채널 아이디
        'title': ch['snippet']['title'], #채널 이름
        'description': ch['snippet'].get('description'), #채널 설명
        'subscriber_count': ch.get('statistics', {}).get('subscriberCount'), # 구독자 수
        'view_count': ch.get('statistics',{}).get('viewCount'), # 채널 총 조회수
        'video_count': ch.get('statistics',{}).get('videoCount'), #채널 총 영상 수
        'thumbnails': ch['snippet'].get('thumbnails').get('default').get('url'), # 채널 프로필 사진?
        'created_date': ch['snippet'].get('publishedAt') # 채널 생성 날짜
    }
    list_name.append(temp)
    return list_name

In [136]:
# =============================================================
# 남은 토큰 관리를 위한 남은 토큰 수 입력
#   - https://console.cloud.google.com/iam-admin/quotas?hl=ko
#   - youtube api 키와 연결된 프로젝트 선택
#   - 서비스 Youtube Data API v3의 현재 사용량 확인.
# =============================================================
print('API 사용량 확인: https://console.cloud.google.com/iam-admin/quotas?hl=ko')
total_unit = 10000 - int(input('이미 사용하신 사용량을 입력해주세요. 예) 256 :'))
print('현재 남은 유닛 수 :', total_unit)

API 사용량 확인: https://console.cloud.google.com/iam-admin/quotas?hl=ko
현재 남은 유닛 수 : 5911

In [11]:
# =============================================================
# IT 기업의 유튜브 채널 정보 수집 시작
# =============================================================
it_handle_list = it_channel_list2['channel_handle'].to_list() # 정제된 IT 채널 리스트를 가져옴

print('='*50)
print('현재 남은 유닛 수 :', total_unit)
print('사용 예정 유튜브 API 유닛 :', len(it_handle_list), 'units')

it_list = [] # it 채널의 정보를 담을 리스트 생성
unit= 0 # 유닛 수 계산 시작!
for handle in it_handle_list:
    get_channel_info(youtube_api_key, handle=handle, list_name=it_list)
    unit += 1
total_unit = total_unit - unit
print()
print('실제 사용된 유튜브 API 유닛: ', unit, 'units')
print('남은 유닛 수: ', total_unit)
print('='*50)

# IT 채널 정보 리스트 데이터프레임으로 변환
it_channel = pd.DataFrame(it_list)
print()
print('수집 결과:')
display(it_channel)
# csv로 저장
it_channel.to_csv('./data/IT채널정보조회.csv', encoding='utf-8-sig', index=False)

==================================================
현재 남은 유닛 수 : 10000
사용 예정 유튜브 API 유닛 : 49 units

실제 사용된 유튜브 API 유닛:  49 units
남은 유닛 수:  9951
==================================================

수집 결과:

,channel_id,title,description,subscriber_count,view_count,video_count,thumbnails,created_date
0,UCA5vKQkvC9zlTDOSNtoMdCQ,SK telecom,SK telecom 공식 YouTube 채널,1130000,1312713263,2705,https://yt3.ggpht.com/ytc/AIdro_m_9Gd-5ejb35YE...,2011-01-12T06:00:00Z
1,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"AI NOW & NEXT\n오늘날 AI로 이룬 혁신을 경험하고, 내일의 도약을 위한...",5320,192302,324,https://yt3.ggpht.com/BUovhY65Fkq3930DuKeBjwJB...,2022-08-04T08:01:36.337173Z
2,UCp3BSINVC7Ggj4kChEUiy7Q,LG유플러스 (LG Uplus),LG U+ 공식 Youtube 채널 \n,660000,1940783234,3713,https://yt3.ggpht.com/MXGutyn0ZJqNgLb5bPGj514z...,2011-12-19T07:47:10Z
3,UCVaIGU8ch9zG42j-rAG6VoA,삼성SDS,AI 풀스택 역량으로 기업의 AX를 선도하는 업무 혁신 파트너\n삼성SDS 공식 Y...,43200,74703491,1137,https://yt3.ggpht.com/v7Jgiy1VlR5ps-jDUHkpnzgf...,2016-10-04T07:31:53Z
4,UCqz8F0bdoDiyzgdYPZAdA-Q,LG CNS,Global AX 전문기업 LG CNS의 공식 유튜브 채널입니다.,76200,68772684,473,https://yt3.ggpht.com/gm9Yi3503swI8kz0XgMxY-xZ...,2012-05-16T04:55:12Z
5,UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,SK 브로드밴드 공식 유튜브 채널입니다\n,75600,178840834,4330,https://yt3.ggpht.com/ojNY0Wvjfp63Lazv7n4DDAOo...,2014-06-20T06:54:37Z
6,UCjyYouHWnID_L4QaQ6U4voQ,네이버 NAVER,네이버 공식 유튜브 채널입니다.,32600,288221425,862,https://yt3.ggpht.com/D-DsROA_yjJi-B1x4nnHXXws...,2012-11-22T12:07:43Z
7,UCBjvBJgIp3NGkrTBEfWBUVw,카카오,일상에 스며든 카카오의 다양한 이야기를 전합니다. 카카오 공식 유튜브 채널.,132000,254316346,910,https://yt3.ggpht.com/SSvyEl7-5J4DlWtbrHfeERIs...,2012-03-26T03:51:31Z
8,UCRBtxwx23bzxyr5R9vFRYhw,현대오토에버,여기는 현대오토에버 공식 YouTube 채널입니다.,10200,3747730,147,https://yt3.ggpht.com/L2QnWR1xkuWsogbZ91hIx6CY...,2019-10-29T05:34:14.878126Z
9,UCqqoiebjYnMqfhx-4f1awKg,Microsoft Korea,Microsoft 목표와 가치는 전세계의 사람과 기업이 잠재력을 최대한 발휘할 수 ...,18600,70757914,1845,https://yt3.ggpht.com/MRNhR0pURHfaJW1zLqGwGc7-...,2011-03-18T07:38:13Z
10,UCcFA2TC568rGp94OqMq3Nig,두나무 (Dunamu),"블록체인 및 핀테크 전문 기업, 두나무의 공식 채널입니다. \nhttps://dun...",151,741560,14,https://yt3.ggpht.com/Ly4SD65RKZXmvnEZsxla7afQ...,2022-11-08T05:33:24.840414Z
11,UCZHb3OEEJ0WkizEH9ErlgvA,Dell Technologies,Welcome to Dell Technologies' official YouTube...,47200,242192458,1199,https://yt3.ggpht.com/FNcLs-Wgkhb7ThCfRl7kg060...,2016-08-05T09:55:02Z
12,UC2wPiIf2xSXGTJNqo8UOY9g,네이버클라우드 l NAVER Cloud,"앞서가는 클라우드의 모든 것, 네이버 클라우드 ☁\n\n네이버 클라우드 플랫폼(NA...",14000,2255754,653,https://yt3.ggpht.com/cThadcW1wOQDycH764qZPBZc...,2017-04-03T09:39:28Z
13,UCwfd3z7HQcVAbwPiZw6JNRw,Synopsys SIG Korea,안녕하세요? 시높시스 SIG (Software Integrity Group) Kor...,5,36,2,https://yt3.ggpht.com/_A2V9syQtxSQfvhEOTwvaqpy...,2023-03-09T06:13:35.629477Z
14,UC7JJk_THjnffYi4xEh54AiQ,Kakao Entertainment,,1190,0,0,https://yt3.ggpht.com/ytc/AIdro_lruG4PSGf43BPi...,2021-01-27T02:45:53.40723Z
15,UCpCNaKju3d8YNq4trfwcJrA,Oracle Korea,오라클은 포괄적이고 총체적으로 통합된 클라우드 애플리케이션과 플랫폼 서비스 스택을 ...,4080,2027057,829,https://yt3.ggpht.com/ytc/AIdro_nNKOlLiApor92J...,2015-01-14T06:55:30Z
16,UCn41TnmQX9Ccswo89wDBiyg,롯데이노베이트,고객의 비즈니스 전환을 선도하는 기업\nBusiness Transformation ...,1170,196470,138,https://yt3.ggpht.com/AVDLd_Vevglh5CJn5RvWF7eQ...,2014-03-14T06:04:29Z
17,UCQNv-1JeNQ9I_xKlLD6QmhA,kt cloud,"대한민국 1등 클라우드, kt cloud의 다양한 서비스 및 기능을 만나보실 수 있...",12300,456469,293,https://yt3.ggpht.com/sG7YOG7DozqJ8EOHsiu7UXZB...,2016-05-02T14:11:28Z
18,UCz-j1tzeMCqvOX0YNkOXIAw,[CJ OliveNetworks] CJ올리브네트웍스,[CJ올리브네트웍스 공식계정]\n디지털 기술과 데이터를 기반으로 공간과 일상의 변화...,1340,242418,103,https://yt3.ggpht.com/LhtEqdwyRd07Dx0IBhMq4yY6...,2019-07-03T23:29:08Z
19,UC6fYG3jaeK2ucyX6YYTWglg,KG이니시스,"1998년 설립된 KG이니시스는 국내 최대 전자지급결제대행업체로, 인터넷쇼핑몰의 결...",106,69701,6,https://yt3.ggpht.com/ytc/AIdro_kfIgc9vuoc0FXf...,2018-07-03T05:44:54Z
20,UCmWvEmIve2QHxqgWXAblahA,KT DS,Cloud와 AI 전문 SW 기업 (주)케이티디에스 입니다.,1480,389423,190,https://yt3.ggpht.com/olq2Fy4DoLFb5H-q3z0lqLaz...,2023-01-19T02:33:34.10329Z
21,UCDT2efYTZ8y516QjrfsDQSA,SHINSEGAE I&C,리테일 산업에 IT기술을 더하면? 신세계아이앤씨의 쉽고 재미있는 리테일테크 스토리를...,943,932798,69,https://yt3.ggpht.com/4z9k0juEyoYK2y6mEGBdUXIS...,2019-12-03T04:33:05.124289Z
22,UCXyGqs4y58arFQ6uBduhnsQ,DB Inc.솔루션사업그룹,,3,164,3,https://yt3.ggpht.com/ytc/AIdro_n6uXwQUZQrJSqg...,2024-05-15T23:09:31.716094Z
23,UCQ2qPELH8lcS-jRi4o-GR5Q,번호안내 114,"대한민국 전화번호를 책임지는! 언제 어디서나, 02-114입니다. 24시간 365일...",85,9771,15,https://yt3.ggpht.com/ytc/AIdro_kvohxUiVMaOwCe...,2018-10-19T01:46:03Z
24,UCgtGQjfrfO_uAnH6JcB1MTA,ETEVERS GROUP 에티버스그룹,에티버스그룹의 공식 유튜브 채널입니다!\nChallenge for Transform...,1280,487549,272,https://yt3.ggpht.com/h2DsgPMiz6WnuvglKVbnjmC0...,2020-05-08T01:34:56.568369Z
25,UCK08M2075Y5TOIc8l0aNIQA,LINE KOREA,,13600,15185814,90,https://yt3.ggpht.com/ytc/AIdro_mH3OZn6rdemCEQ...,2014-02-07T05:25:38Z
26,UCtY-kbAYmWfVOqunQv2Wp3w,나이스페이먼츠,,5,524,1,https://yt3.ggpht.com/ytc/AIdro_l3Bz6doyOqmxnb...,2021-11-10T03:14:52.996109Z
27,UCNucE-FsBf3RITeGbsE3RKw,kt is,Total Marketing Service & Biz Support 기업,67,9767,14,https://yt3.ggpht.com/ytc/AIdro_lptnEMC_bj6-pd...,2021-03-22T07:06:20.131511Z
28,UCsdkfl1-goECoNJUp4aMJ7Q,세무신고는 이지샵,,3990,3328221,243,https://yt3.ggpht.com/ytc/AIdro_lFvIK3fB62-3O7...,2014-11-04T02:04:29Z
29,UCB3YZT-IHFywklzOtnB6GGg,나이스정보통신,"NICE정보통신 공식 YOUTUBE 계정입니다.\nVAN, PG, TAXREFUND...",146,25208,29,https://yt3.ggpht.com/oEENg4-gZgPUiNQmHNY7WKyM...,2019-04-29T04:28:50Z
30,UCh2nkYoiq6hae8ePxaZUgkw,빗썸 Bithumb Official,"당신의 안전한 금융 파트너, 빗썸의 공식 유튜브 채널입니다. \n",70900,34593484,1257,https://yt3.ggpht.com/-wqva-xDJjTdszWMnLKUdPqY...,2017-09-21T12:32:15Z
31,UCuDsOOa9CtAWwv7_rmuL14g,카카오모빌리티,We move life\n우리의 기술로 생활을 움직입니다.\n\n편리한 이동이 가치...,6730,31944589,241,https://yt3.ggpht.com/ZxVtDIbWGLs3vX7B_w-Nfk8C...,2017-10-20T01:13:47Z
32,UCoGxUVOIOxtg2V7HALB5o2A,만나플러스,시간에 가치를 더하는\n만나플러스\n,262,35026,38,https://yt3.ggpht.com/cT6uymMm8tCQcW1gp_XhsCM_...,2022-06-14T04:41:15.428269Z
33,UCm0COQdmdRLN23D4gUK3FAA,코스콤,코스콤 유튜브에 방문해 주셔서 감사합니다.\n코스콤은 코스콤 5.0시대를 맞아 금융...,1740,146682,164,https://yt3.ggpht.com/M2bC3vMUhqveSTADBUfjmb1j...,2019-05-09T08:24:34Z
34,UCsc2G8g0k-H15yYuQQv7AYQ,더존TV,"✨Get Fun, Gain Insight '더존TV'\n모두를 위한 단 하나의 인사...",51000,1928836,162,https://yt3.ggpht.com/5wbT-EEpiUlmmwLlBnITpgv7...,2025-12-24T04:53:18.756064Z
35,UCdc_SRhKUlH3grljQXA0skw,Google Korea,,95100,577958674,628,https://yt3.ggpht.com/wBZS4tfRv4QEQWWmQ2VA9ylW...,2007-08-13T01:46:32Z
36,UCsY3aR2FYK4SbM2tBLksWtQ,다우오피스,"올인원 업무플랫폼, '다우오피스' 공식 유튜브 채널입니다. 😀\n직장인들을 위한 콘...",2370,2636225,600,https://yt3.ggpht.com/MGmllFKya8zvALiBb6qcHCRb...,2014-01-14T06:47:47Z
37,UCSvOg4rSu395lPz6uMqBekw,kt M모바일,190만 고객의 선택! 압도적 1등 알뜰폰 kt M모바일의 공식 유튜브입니다. \n...,12900,50331376,331,https://yt3.ggpht.com/-t9DNlJUQAHs3tlrQg6pW7QD...,2014-11-26T08:59:10Z
38,UCjpcrwZnzmLdSrxVcdZd0cQ,아이티센,세상 모든 서비스에 디지털 가치를 부여하는 IT 선도 기업,1320,274017,148,https://yt3.ggpht.com/9KQ_UqP1Z9nCnk4Yv1XURCfX...,2021-07-21T01:43:33.371158Z
39,UCrdvKtWTpBfOx9kFCQ6aK3A,BizTechi_ERP,Global No.1 Solution SAP를 활용한 기업경영환경의 혁신과 성장을 ...,42,5233,15,https://yt3.ggpht.com/Q_KEZHJjW6Y2F5Yg4Qv6dlHF...,2018-10-29T01:35:44Z
40,UCRGEUnlW_qBi3ZDohvP-ylQ,농협정보시스템,농협정보시스템 공식 유튜브 채널입니다,37,1910,2,https://yt3.ggpht.com/ytc/AIdro_mr-WyPcf2Y4UVf...,2016-09-23T05:45:13Z
41,UCsfezAG3HiKjf7OrYTdNZxg,신한DS_오픈스튜디오,,668,41418,71,https://yt3.ggpht.com/c0zs0JsGxLj0y_XlWCkobGuy...,2020-08-13T06:07:21.048803Z
42,UC8RTcqBjB7I9lD_4l8cmwHg,이테크 클라우드,,79,1110,10,https://yt3.ggpht.com/1lxJgEyL_RkJ_kOL17xq3bJt...,2021-03-22T06:57:28.485546Z
43,UC_7nyGIBuYk6HBBBftbn3kg,NOL,NOL(야놀자) 플랫폼 공식 웹사이트 \n☞ https://nol.yanolja.c...,36600,104512630,152,https://yt3.ggpht.com/LowY7r6RgPTITwWMqM4jzhWN...,2013-05-30T05:27:55Z
44,UCWaLVmBvB2ytgSXvtDBKQiw,미디어로그영화,MediaLog = Media + Dialogue\n영화로 소통하는 미디어로그입니다.,43700,47541238,1108,https://yt3.ggpht.com/ytc/AIdro_l98kiVolj84NPV...,2013-05-13T00:20:01Z
45,UCZHb3OEEJ0WkizEH9ErlgvA,Dell Technologies,Welcome to Dell Technologies' official YouTube...,47200,242192458,1199,https://yt3.ggpht.com/FNcLs-Wgkhb7ThCfRl7kg060...,2016-08-05T09:55:02Z
46,UCMaDyFlagYlsolLLfWHu7Dw,숲 (SOOP),"자유로운 소통, 무한한 연결. SOOP(숲) 공식 채널입니다.\n\nSOOP은 '누...",124000,70766488,5024,https://yt3.ggpht.com/TNh2TiRdXlv6mZPFVWEApllp...,2013-12-05T08:06:12Z
47,UCNUz9CIAlWDtaLWvFWzgsww,티머니,더 편한 이동과 결제를 위한 플랫폼 기업\n티머니(Tmoney) 공식 채널입니다.\n,4420,101042912,209,https://yt3.ggpht.com/4kA3G7zuYn2WkvAYxRnKHh1V...,2013-04-15T05:29:13Z
48,UCsfezAG3HiKjf7OrYTdNZxg,신한DS_오픈스튜디오,,668,41418,71,https://yt3.ggpht.com/c0zs0JsGxLj0y_XlWCkobGuy...,2020-08-13T06:07:21.048803Z

In [12]:
# =============================================================
# 식품 기업의 유튜브 채널 정보 수집 시작
# =============================================================
food_handle_list = food_channel_list2['channel_handle'].to_list() # 정제된 IT 채널 리스트를 가져옴

print('='*50)
print('현재 남은 유닛 수 :', total_unit)
print('사용 예정 유튜브 API 유닛 :', len(food_handle_list), 'units')

food_list = [] # it 채널의 정보를 담을 리스트 생성
unit= 0 # 유닛 수 계산 시작!
for handle in food_handle_list:
    get_channel_info(youtube_api_key, handle=handle, list_name=food_list)
    unit += 1
total_unit = total_unit - unit
print()
print('실제 사용된 유튜브 API 유닛: ', unit, 'units')
print('남은 유닛 수: ', total_unit)
print('='*50)

# IT 채널 정보 리스트 데이터프레임으로 변환
food_channel = pd.DataFrame(food_list)
print()
print('수집 결과:')
display(food_channel)
# csv로 저장
food_channel.to_csv('./data/FOOD채널정보조회.csv', encoding='utf-8-sig', index=False)

==================================================
현재 남은 유닛 수 : 9951
사용 예정 유튜브 API 유닛 : 70 units

실제 사용된 유튜브 API 유닛:  70 units
남은 유닛 수:  9881
==================================================

수집 결과:

,channel_id,title,description,subscriber_count,view_count,video_count,thumbnails,created_date
0,UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],"편의점의 새로운 정의!\n트렌드의 중심, 재미의 기준을 만들지😎✌️""\n매일 새로운...",927000,305247518,1173,https://yt3.ggpht.com/ytc/AIdro_mI4fk2-pjTlfnJ...,2012-06-05T11:33:04Z
1,UCnL1m_iPeN8vX7zFHoB4SYg,테헤란로405,테헤란로405에서 좋은 친구 BGF의 주요 소식을 살펴보세요!\n-\n편의점 CU를...,2120,987118,501,https://yt3.ggpht.com/XgW8KshcFJNgLiN92DYhQ3KQ...,2017-03-03T10:34:35Z
2,UCl0HemfAt7dShJRf59_cuGQ,GS25 l 이리오너라,GS25 공식 유튜브 채널📻\n,1060000,223076645,2580,https://yt3.ggpht.com/AajkhhUfGCTlIBM8YvvfZmWK...,2012-12-26T06:54:54Z
3,UChD4kH8BcI49njXGL5-makg,GS리테일 뉴스룸,GS리테일 뉴스룸 공식 유튜브 채널입니다.\n최신 뉴스와 다양한 소식들을 영상으로 ...,2950,1044778,167,https://yt3.ggpht.com/dRpIX9kTKHJJXBJwtWoyXtBB...,2015-05-18T08:16:28Z
4,UCG_gfzGVpsxGwYuFgH8-tNA,대상 DAESANG,더 많은 것들을 존중의 대상으로 DAESANG\n#Respect for more #...,18500,330712588,254,https://yt3.ggpht.com/UGJpLrZkEdbCDTFulkdMEeaH...,2015-12-10T08:58:42Z
5,UCfv1dkNKCFUtZouvp3DhS3g,대상그룹 DAESANG 디튜브,대상그룹(DAESANG GROUP) 공식 소통 채널\n‘대상주식회사’의 식품 이야기...,10800,5760859,277,https://yt3.ggpht.com/JNGLkJj-SitafANGlfbseU-j...,2020-09-04T01:25:26.250343Z
6,UCDryA2PIGnbs9NYn_63rISw,CJ제일제당,CJ제일제당 공식 유튜브 채널입니다. \n,491000,34922991,204,https://yt3.ggpht.com/ULAliXxe7B5_ysZS8vIsPs18...,2011-01-26T00:52:39Z
7,UCOV_BpGzvmH7ZtjQOWg0bSQ,제당슈만,⭐제당슈만⭐ CJ제일제당이 당신을 🔥슈퍼스타🔥로 만들어 드립니다!\nCJ제일제당의 ...,20900,6641901,216,https://yt3.ggpht.com/Yk3vnP2gHzidyACXSqtTo1LU...,2020-05-15T11:50:40.345514Z
8,UCGmLtNZFTL6PiKsz3Vpdgbw,비비고 (bibigo),bibigo Official YouTube Channel\n\n,88100,275870592,307,https://yt3.ggpht.com/nQgCSi2mTp99T8VaSEH5MVyZ...,2013-04-02T11:37:09Z
9,UCFXwXfbr4b1HHl-YKCOaydA,맛깔스튜디오 by롯데웰푸드,맛있는 거 말고 재밌는 거도 기깔나게 잘합니다.\n롯데웰푸드의 맛깔나는 컨텐츠 제작...,147000,490980699,1311,https://yt3.ggpht.com/LJScwH9HDweKeTnwo8UAMcVd...,2011-11-23T07:54:50Z
10,UCpvT-53Ki7d9Z0PWKC6fGOA,롯데웰푸드 모락모락,모락모락 온기가 느껴지는 \n갓 지은 롯데웰푸드 콘텐츠 한끼🍴 \n,138000,137205606,625,https://yt3.ggpht.com/Emiy4Wt0qQd8VDKpwF_HeQz1...,2013-03-14T00:43:52Z
11,UCaxvyTYdWaDXupmgj5ttDUQ,Starbucks Korea,"""커피 이상의 특별한 경험을 소개합니다""\n스타벅스는 커피를 넘어, 사람과 사람을 ...",178000,58477777,807,https://yt3.ggpht.com/ytc/AIdro_morPijMJBwDTgc...,2007-06-19T23:26:27Z
12,UCbEEgpyRxXd6rbM_xhApb_Q,727스튜디오,Original Contents by STARBUCKS KOREA\n\nⓒ 727S...,126000,15193131,240,https://yt3.ggpht.com/4JG-2UP2kJp_pgaL6Tdxj1_q...,2025-01-14T05:06:10.93402Z
13,UCzGara7SUTKXruclCD4eA5g,농심 nongshim,맛있는 상상이 가득한 농심 공식 유튜브 채널 입니다.,44100,1309586458,1459,https://yt3.ggpht.com/2vDg5LPC9z_lExgRYWCFs6XQ...,2009-06-25T06:18:44Z
14,UCzKFT7cBIKO9Dapikf6e3ow,롯데칠성 LOTTE CHILSUNG,롯데칠성 유튜브 공식 채널입니다. \n다양한 영상 컨텐츠를 소개해 드립니다.\n앞으...,126000,680456492,541,https://yt3.ggpht.com/WopSa_1tJT2lQthlRuak2pwT...,2013-03-12T03:31:37Z
15,UC-WFvgdXXmZPj4pDI8GFbzQ,칠성레이블,칠성사이다가 선사하는 콘텐츠 시리즈!\n\n칠성사이다가 기획한 칠성레이블은\n평범한...,103000,70513554,266,https://yt3.ggpht.com/EBrCDOTLtaagP0mjTvgPgbn6...,2021-12-23T09:19:44.012307Z
16,UCHvCHuXTg6yfQQ1QCeDQMLg,오뚜기 Daily,오뚜기 공식 유튜브 채널(Otoki Official Youtube Channel),76200,227362029,826,https://yt3.ggpht.com/Hz_EJNq4FBpNf_hpOfKVi2yQ...,2012-09-14T01:34:19Z
17,UCGEaz9UlmXmQ2YCEDIAc1iA,ottoginoodle,맛으로 행복한 세상! 오뚜기 라면 이야기에 오신것을 환영합니다.\n\n뚜기네의 재밌...,11600,62503633,250,https://yt3.ggpht.com/ytc/AIdro_kPxov_YKhpPf92...,2011-12-07T01:42:35Z
18,UCSQ0lVqv57JVw1lOdJ2vTVA,이마트24 | ALLDAY HIGHLIGHT,"모든 순간이 하이라이트\nALLDAY HIGHLIGHT, 이마트24\n",143000,75815729,651,https://yt3.ggpht.com/PEHYGu8okwfvvk2-pTRhPmHl...,2020-09-24T00:06:25.081438Z
19,UCmvqXRPTfMgkKF3MFWylMqQ,HITEJINRO,당신의 인생을 더 큰 즐거움과 에너지로 채우는 하이트진로 공식 유튜브입니다.,125000,1282984323,880,https://yt3.ggpht.com/ubxjIFIFMFCCxi1H3Nj-7gTS...,2009-10-29T06:36:25Z
20,UClgbMkn177O0xNOEcR9rtug,하이트진로음료,,2900,48478607,219,https://yt3.ggpht.com/rMCqFHSwiET2uJo-03eJxu3p...,2013-06-20T06:53:57Z
21,UCX0cSM0jY9PmtGZixR75u1g,더반찬,No1. 온라인 푸드마켓 더반찬 \nwww.thebanchan.co.kr,397,618622,51,https://yt3.ggpht.com/ytc/AIdro_lHUOA1q_DPQguZ...,2016-10-18T01:54:59Z
22,UCPz4i66EweVQPddqYq7uULg,서울우유 seoulmilk,서울우유 협동조합의 공식 유튜브입니다.\n\n,15300,98573915,283,https://yt3.ggpht.com/UVN0WEXK3va2ZpEADDFelk8Y...,2010-11-24T02:39:38Z
23,UCs_L1_g_MeTHhuRhJEkF_xA,동원F&B(Dongwon),동원F&B 공식 채널입니다. (Dongwon F&B official )\n,37800,624856879,514,https://yt3.ggpht.com/FH56yK3ukI5SjQysrh9uurmC...,2011-07-11T04:11:05Z
24,UCULxh7_uMrbCn0IR_H1h3fg,동원몰 (dongwonmall),💙동원몰 공식 유튜브 채널💛\n다양한 동원몰 소식은 \n⬇️아래 링크에서 확인⬇️,70,133185,32,https://yt3.ggpht.com/ytc/AIdro_mptxWV4S7R-4st...,2012-01-27T00:43:19Z
25,UCC3eqZIo6lqZQQAN9MO0LQA,동원TV,동원그룹의 최신 소식과 유익한 볼거리가 가득한 곳! 여기는 동원그룹 공식 유튜브 채...,24100,317254534,1045,https://yt3.ggpht.com/JWWnneUCTFTzf5cMguzUzN8b...,2013-04-03T12:52:46Z
26,UCxHML2F6f8c5L7N2-0gF6Vw,삼양그룹,💡생활의 잠재력을 깨우고\n🌐인류의 미래를 바꾸는 \n💙삼양그룹 공식 인스타그램\n...,6900,269350697,354,https://yt3.ggpht.com/TQNeALOjJ4jGXfNJO1SOx6Kf...,2013-04-16T04:48:36Z
27,UClEdrjHVDXEOsll343sECmQ,큐원 알룰로스,"더 나은 달콤함의 시작\nBetter Sweet, One Choice, 큐원 알룰로스\n",17400,4618178,101,https://yt3.ggpht.com/1xOjNkRZWGiJInBBKVlCLEVL...,2015-07-28T05:45:03Z
28,UCMqZKRBemgZ0_1uLT2yAF9w,상쾌환 EASY TOMORROW,,1430,105773077,137,https://yt3.ggpht.com/OBZBKMisqoAWKG0KR_ODg7_R...,2019-01-14T11:34:22Z
29,UCGgQBs1IgNkwMYbnu26S1yg,파리바게뜨TV,놀고 먹는것에 진심인 사람들의 집합체 🍞🥖🥪🍬\n맛있는 즐거움으로 꽉 찬\n파리바게...,24700,151278167,575,https://yt3.ggpht.com/ytc/AIdro_nHRY5WmHpDGQjZ...,2014-06-16T08:46:37Z
30,UClYaslphHkJ3faHzJrU6ZSw,오비맥주,안녕하세요!\n여기는 오비맥주 공식 YouTube 채널입니다.,1500,1520682,35,https://yt3.ggpht.com/ytc/AIdro_nbT41LfpXIHJ-j...,2019-03-22T01:23:30Z
31,UCUQhyOLi8uFTmiFRmndjQxw,카스 CASS,"신선하고 톡 쏘는 맥주, 젊음의 활력과 에너지를 느낄 수 있는 대한민국 젊음의 대표...",83100,238320344,497,https://yt3.ggpht.com/Fufyjor6JyuU3onwTV9QAQkF...,2014-04-21T07:53:11Z
32,UCFRMEa0vlRfrgcQpnryE-TA,한맥 HANMAC,\n100% 국내산 고품질 쌀로 완성한\n상쾌한 풍미의 코리안 테이스트\n\n한국인...,932,63154505,94,https://yt3.ggpht.com/NoNVNCOHFoS2ViM-c9ZOK5ke...,2020-08-13T02:24:17.881209Z
33,UCowoImtEdqWGyBIRqt6L2dw,Stella Artois Korea,스텔라 아르투아 공식 유튜브 채널입니다. 음주는 책임있게. \n\t\n* 본 페이지...,5180,54931047,176,https://yt3.ggpht.com/1EBgazONM_RXFamXWm9li8Lp...,2015-06-08T07:48:24Z
34,UC-9HdRV-OzriZ1Q09bT304w,BUDWEISER KOREA,버드와이저 공식 유튜브 채널입니다. 음주는 책임있게.\n\n* 본 페이지의 콘텐츠는...,20800,58813645,431,https://yt3.ggpht.com/CDJxXuduCEMnjjIImQwE7KT2...,2017-06-03T10:08:46Z
35,UCOx-g_rEMW3oD8g-bQaLWkQ,Hoegaardenkr,도심 속에서 호가든을 느끼다.\n호가든에 오신 걸 환영합니다 🌿\n\n𝗪𝗲𝗹𝗰𝗼𝗺𝗲...,793,11092013,137,https://yt3.ggpht.com/xO6pBYAofv02TIlnLbWa4Rsv...,2018-09-11T09:56:45Z
36,UCYPk6gQRP0W2ApSem8qsW2g,구스아일랜드,구스아일랜드 공식 유튜브 채널입니다. 음주는 책임있게.\n\n본 페이지의 콘텐츠는 ...,170,3526195,93,https://yt3.ggpht.com/ytc/AIdro_mj0dE9rfy5Sdqs...,2018-09-10T08:48:03Z
37,UCbyV_HczPmqn2LthdcBIl2Q,커피라는 행복 맥심,,35400,913320980,868,https://yt3.ggpht.com/OV9SIS-26rHeYBLxdR2WywK2...,2013-10-03T12:56:18Z
38,UCIAFN5e9KzBu_F3dBDbmmVg,"세상에서 가장 작은 카페, 카누",,3250,347268601,327,https://yt3.ggpht.com/KU-a2Ss17Q113DZAJ-J5YCvG...,2022-12-26T02:15:16.71179Z
39,UCtFDX5H24C2igmDOdAJdS9Q,동서식품 유튜브,,18000,57672769,114,https://yt3.ggpht.com/wmjtHXOFc69OLqGslyT2i5io...,2014-05-21T01:45:41Z
40,UCt0Pnki9ZDDYx6auEtClYLQ,매일유업 | Maeil,매일유업의 공식 Youtube 입니다.,72900,318397942,1024,https://yt3.ggpht.com/XBGVTwpqwFjYd_y3hrEarY3N...,2010-09-03T05:51:06Z
41,UCzGbclHB9ZcrbcV4qg11C1A,셀렉스,"대한민국 1등 단백질, 셀렉스 공식 유튜브 채널입니다.\n",118000,69333755,171,https://yt3.ggpht.com/vBgT4prOdblpX9cSvjB8SyhD...,2022-03-18T07:03:41.518059Z
42,UC88W-nkd_7G9S7u-2xlX4DQ,삼립,보기만 해도 빵🥖빵🍞 터지는 삼립 공식 유튜브,4330,53102006,204,https://yt3.ggpht.com/LK3-fEwOU_YzesUxIH-ZsxFK...,2017-03-28T07:16:12Z
43,UCiyg3rAdPOJN4eKAgAs5FOQ,SPC그룹,"일상을 맛있게 행복하게, Happiness in every bite\n",5580,7639925,413,https://yt3.ggpht.com/xx8ZYgZxHElh9Sd3Gh-2nNPL...,2016-12-23T06:27:54Z
44,UCzCxSb_RYZuaiaP3u9QNR_A,Coca-Cola Korea,Real-Magic 코카-콜라의 공식 YouTube 채널입니다!,116000,763721794,727,https://yt3.ggpht.com/3gq979lNuPnYbsQJA7ZimgNN...,2011-02-15T09:06:14Z
45,UCC-RQrzmKSAV70txxsdXWqQ,팜스코TV,"(주)팜스코\nBeyond No.1, Everyday with Farmsco\nww...",3520,359092,302,https://yt3.ggpht.com/bnS0qpIZrhDa9CJzfAA-5BCW...,2019-06-12T05:43:11Z
46,UC4xGgCpoPfLHcuPeUbnMibA,사조대림,먹잘알들의 PICK👀\n믿고 먹는 사조대림!\n,1270,47141462,258,https://yt3.ggpht.com/ffn5eGjHgQP90uYCLCG7wZU3...,2022-01-26T05:52:42.197434Z
47,UCEKRI0fipK4LEgV98nI2CQA,버거킹,,51100,410851437,363,https://yt3.ggpht.com/kTGFMGRb__0Rodj-WPawVCFg...,2013-08-13T09:41:34Z
48,UCDjdk0ufvcvV08hAm_vF06Q,투썸플레이스,,82900,137440409,291,https://yt3.ggpht.com/GbVbtd__BYN_kIyMCywMiwYI...,2017-11-30T07:09:02Z
49,UCYnYhuh-L3ApSQ5A-zM3QkQ,빕스VIPS,,889,19818056,81,https://yt3.ggpht.com/MNQZn5AuHOKsis9HAO4T7hbF...,2013-12-30T00:31:01Z
50,UC9Hu-7OguU6HyWaxP_GBYcA,Samyangfoods삼양식품,SQUARE🟧 THE CIRCLE🟠\n불가능의 룰을 깨다\n,17700,282033233,255,https://yt3.ggpht.com/ytc/AIdro_l4o6EV2Hs-eL5p...,2011-05-24T06:31:26Z
51,UCWuIxsTBinJzNf4sQKy7FxA,킴스클럽 공식,,160,270229,60,https://yt3.ggpht.com/CLeokySMmN7wy_IkzkxcnW6T...,2015-11-01T11:22:37Z
52,UCtAHe2OINYIyGOTLDSCzFFg,아웃백 스테이크하우스,"우리들의 PLAYGROUND, 아웃백 그라운드🎈\n",84700,141933697,255,https://yt3.ggpht.com/ytc/AIdro_mdq6uNipbCy7a6...,2011-06-29T05:46:21Z
53,UCqXNBZbGHHS-0nwWvEWXf0A,코레일유통TV,🚄철도 모빌리티 서비스 기업 코레일유통❤️\n,1010,201127,100,https://yt3.ggpht.com/ytc/AIdro_msfYs7VrHQzkW3...,2020-04-02T07:01:42.156416Z
54,UCmSdD90HfUqyR3VNLys03EQ,이랜드이츠,,6,70532,9,https://yt3.ggpht.com/ytc/AIdro_l1Ei_UOn3gRmgf...,2025-01-01T07:51:01.79617Z
55,UCc76iFK6R2u2sqAunMZc8jw,더카페,🔽더카페 성공창업 문의🔽\nhttps://thecaffeopen.com\n\n대기업...,411,1412227,40,https://yt3.ggpht.com/7oCKQYLiGqQS3thAK_1kY1UE...,2022-05-23T07:54:35.677133Z
56,UCvRDrKfRaqYRSBjtj80Q1iQ,KFC Korea,,5120,30089883,174,https://yt3.ggpht.com/Jpt4-yILYIHYiNLqSOYTL2Qz...,2015-10-02T05:43:05Z
57,UCabcfEPMYK0rvbGIl3Gr3Ag,엠즈씨드주식회사,커피전문점 Paul Bassett 공식 YouTube 채널에 오신 것을 환영합니다.,31200,805276,33,https://yt3.ggpht.com/ytc/AIdro_k_6I392knvUBZm...,2015-04-05T14:44:45Z
58,UCbquzcEXtjLAKKlGQ4hLC-w,다담몰,,311,429689,10,https://yt3.ggpht.com/XBovUJb6yUdq4BDKYNTzVbgc...,2021-07-15T02:56:46.101064Z
59,UCrDYPLah4QRsqEZVvWQ6t7g,도미노피자,도미노피자 공식 유튜브 채널입니다.,20200,171092042,287,https://yt3.ggpht.com/_oV6lN8faYGHsjkU5uQVJCzt...,2010-11-29T00:22:40Z
60,UC9_GC5aoZJMz5MAH9e8x9Yg,ENTAS,대한민국 대표 외식문화기업 엔타스\n\n엔타스 그룹은 1991년 창업 이래 꾸준하고...,22,3882,13,https://yt3.ggpht.com/Dtm7uKrRhlF_D8Yc_R18zLQz...,2025-02-13T15:41:10.261329Z
61,UCnMNvrjrdtl_b_5rgvCn21Q,🍦Buza Company🍦,From 🇰🇷 to 🇦🇪🇸🇦🇧🇭🇰🇼🇴🇲 and 🌏\nIntroducing the h...,182,82861,82,https://yt3.ggpht.com/lAJRm9JMzvFiuIzSFUnBN2v7...,2021-08-15T12:39:56.026374Z
62,UCr0W7lsBivPQN5mB2_IntCg,그레인온,,114,4739577,33,https://yt3.ggpht.com/qxt1glZKqzVAyk42Pf-d-VKA...,2023-08-28T06:28:51.294443Z
63,UCuJkoRqYKKCwagZhmz6my-g,gongcha_korea,공들여 더하는 행복 공차.\nhttps://www.gong-cha.co.kr/bra...,14500,30743423,177,https://yt3.ggpht.com/TN6SSFmDwkGEV7UUKaICIR_u...,2016-09-22T04:16:24Z
64,UCy85dXvlDH-9H9puNRRGuxA,유사나헬스사이언스코리아,"유사나는 최고의 과학을 기반으로 개발 하고, 이를 바탕으로 직접 판매를 통해 우수한...",11800,1532669,592,https://yt3.ggpht.com/JnDmz84yPDvCNbWbKubIBjN3...,2013-09-26T16:29:24Z
65,UCvGz1yRdYIyq1wsVrdubFdg,63 스카이라인 다이닝,63 스카이라인 다이닝 공식 채널입니다.\n\n서울의 랜드 마크인 63빌딩에서\n즐...,421,139049,58,https://yt3.ggpht.com/-tf3IeHvN9EpqMASNf_uCdsH...,2020-10-19T02:36:24.92673Z
66,UCIAd6tBRFaU5dVJZflutneQ,CUCHARA_official,"STAY SAFE, STAY HEALTHY\n쿠차라는 신선한 재료로 매일 조리하는 ...",5,1288,4,https://yt3.ggpht.com/sTMC3EdFh7mTN0J7mm1w7LEF...,2021-07-26T06:19:41.020417Z
67,UCcf7JZQJuaxkgxaJvLP5ehw,Amoje food,,66,55087,58,https://yt3.ggpht.com/ytc/AIdro_kwMxDL9vQxTlM2...,2013-06-14T02:46:07Z
68,UCFqPOabewS-V-InoIsilfPg,매드포갈릭 Mad for Garlic,"모두의 다이닝, K-Cultured 이탈리안 레스토랑 '매드포갈릭'의 공식 유튜브 ...",285,1711428,5,https://yt3.ggpht.com/5OeI_1Wlq5As-4U2NOt8lx54...,2015-03-05T08:38:47Z
69,UCkY-OZQGn8e7loIO7Z9wHXQ,강강술래푸드,가정에서도 만나세요.\n강강술래에서 경험했던 맛을 가정에서도 그대로\n느끼실 수 있...,130,30373,67,https://yt3.ggpht.com/1Z0mMbXKodbr_EwaT99vsgjo...,2020-11-09T02:39:34.281239Z

---
#### 채널 선정기준
    - 채널 정보 데이터 EDA를 통해 선정 기준 정립

---

In [ ]:
# =======================================================================
# 1차 채널 선정 기준 정하기
# =======================================================================
# 
# channel_list(arg1, arg2)
# 
# arg1: 데이터프레임이름
# arg2: 저장할 경로 (예: './data/test.csv')
# 
# 1. 구독자 1만 명 미만 채널 제거 : 마이크로 인플루언서 최소 기준
# 2. 채널 나이 3년 미만 채널 제거 : 계절성을 반영하기 위한 기준
# 3. 연 평균 4회 미만 영상 업로드 채널 제거 : 4회 미만 계절성 반영 불가
# 
#
# =======================================================================

def channel_list(ch_data, save_path=None):
    
    # 숫자형 컬럼 정수로 변환
    ch_data['subscriber_count'] = ch_data['subscriber_count'].astype(int)
    ch_data['video_count'] = ch_data['video_count'].astype(int)
    ch_data['view_count'] = ch_data['view_count'].astype(int)
    
    # 1. 구독자 1만 명 미만 채널 제거
    ch_data = ch_data[ch_data['subscriber_count']>= 10000] 
    
    # 2. 채널 나이 3년 미만 채널 제거
    ch_data['year'] = pd.to_datetime(ch_data['created_date'], errors='coerce', format='mixed', utc=True).dt.year
    ch_data['channel_age'] = 2026 - ch_data['year']
    ch_data = ch_data[ch_data['channel_age'] >= 3]
    
    # # 3. 연 평균 4회 미만 영상 업로드 채널 제거 -> IT는 이 조건 있으나 없으나 동일. F&B는 이 조건 추가시 폴바셋 채널 삭제 https://www.youtube.com/channel/UCabcfEPMYK0rvbGIl3Gr3Ag
    # videos_thr = ch_data['channel_age'] * 4
    # ch_data = ch_data[ch_data['video_count'] >= videos_thr]
    
    # CSV 파일로 저장
    ch_data.to_csv(save_path, index=False, encoding='utf-8-sig')
    return ch_data

In [101]:
# =======================================================================
# 1차 채널 선정 : IT 채널 리스트 : it_filtered_channel_list
# =======================================================================
it_filtered_channel_list = channel_list(it_channel, './data/IT_Filtered_Channel_list.csv')
len(it_filtered_channel_list)

20

In [102]:
# =======================================================================
# 1차 채널 선정 : FOOD 채널 리스트 : food_filtered_channel_list
# =======================================================================
food_filtered_channel_list = channel_list(food_channel, './data/FOOD_Filtered_Channel_list.csv')
len(food_filtered_channel_list)

36

---
#### 채널 영상정보 검색
    - 채널이 가지고 있는 영상의 Video_id를 수집
    - 이후에 진행할 영상 상세정보 불러오기에 사용
---

In [ ]:
# =======================================================================
# 채널의 uploads playlist를 이용해 영상 정보를 수집 : get_playlist_video_info(arg1, arg2, arg3, arg4)
#
# arg1: 유튜브 API 키 (필수)
# arg2: 유튜브 채널 ID (필수)
# arg3: 가져올 최대 영상 개수 (기본값: 50)
# arg4: 저장할 csv 경로 (필수)
#
# 비용: 1회 당 2유닛
#   channels: 
#
# [수집할 정보]
# - channel_id: 채널의 고유 아이디 값
# - video_id: 영상의 고유 아이디 값
# - published_at: 
# - title
# - description
# =======================================================================

def get_playlist_video_info(api_key, channel_id=None, max_results=50, save_path=None):
    
    if save_path is None:
        raise ValueError("저장할 경로를 입력해주세요. 예: save_path='./data/youtube_data.csv'")

    if not channel_id:
        raise ValueError("channel_id를 입력해주세요")

    # 기존 CSV에 저장된 video_id 불러오기
    existing_video_ids = set()

    if os.path.exists(save_path):
        existing_df = pd.read_csv(save_path)
        if 'video_id' in existing_df.columns:
            existing_video_ids = set(existing_df['video_id'].dropna().astype(str))

    # 채널의 uploads playlist ID 가져오기
    url = 'https://www.googleapis.com/youtube/v3/channels'
    channel_params = {
        'part': 'contentDetails',
        'id': channel_id,
        'key': api_key
    }

    r = requests.get(url, params=channel_params, timeout=30)
    print(r.url)

    if not r.ok:
        print('status_code:', r.status_code)
        try:
            print('error_json:', r.json())
        except Exception:
            print('error_text:', r.text)
        return []

    channel_data = r.json()
    items = channel_data.get('items', [])

    if not items:
        print('채널 정보를 찾을 수 없습니다.')
        return []
    
    # 업로드된 플레이리스트 아이디 가져오기 
    uploads_playlist_id = (
        items[0]
        .get('contentDetails', {})
        .get('relatedPlaylists', {})
        .get('uploads')
    )

    if not uploads_playlist_id:
        print('uploads playlist ID를 찾을 수 없습니다.')
        return []
    
    # playlistItems로 영상 정보 수집
    playlist_url = 'https://www.googleapis.com/youtube/v3/playlistItems'
    all_items = []
    next_page_token = None

    while len(all_items) < max_results:
        remain = max_results - len(all_items)
        request_count = min(50, remain)

        playlist_params = {
            'part': 'snippet',
            'playlistId': uploads_playlist_id,
            'maxResults': request_count,
            'key': api_key
        }

        if next_page_token:
            playlist_params['pageToken'] = next_page_token

        r = requests.get(playlist_url, params=playlist_params, timeout=30)
        print(r.url)

        if not r.ok:
            print('status_code:', r.status_code)
            try:
                print('error_json:', r.json())
            except Exception:
                print('error_text:', r.text)
            break

        data = r.json()
        items = data.get('items', [])

        if not items:
            break

        for video in items:
            snippet = video.get('snippet', {})
            resource_id = snippet.get('resourceId', {})
            video_id = resource_id.get('videoId')

            if not video_id:
                continue

            video_id = str(video_id)

            # 중복이면 건너뛰기만 함 (중단 X)
            if video_id in existing_video_ids:
                continue

            all_items.append({
                'channel_id': snippet.get('channelId'),
                'video_id': video_id,
                'published_at': snippet.get('publishedAt'),
                'title': snippet.get('title'),
                'description': snippet.get('description')
            })

            # 중복 방지용 set에도 즉시 추가
            existing_video_ids.add(video_id)

            if len(all_items) >= max_results:
                break

        next_page_token = data.get('nextPageToken')
        if not next_page_token:
            break


    # 4. CSV 저장

    if all_items:
        new_df = pd.DataFrame(all_items)
    
        if not os.path.exists(save_path):
            new_df.to_csv(save_path, index=False, encoding='utf-8-sig')
        else:
            new_df.to_csv(save_path, mode='a', header=False, index=False, encoding='utf-8-sig')
    
    return all_items

In [ ]:
# =======================================================================
# 유닛비용 미리 계산
# =======================================================================

print('가지고 있는 유닛 수: ', total_unit)
total_video_count = np.sum(it_filtered_channel_list['video_count'])
total_spend_unit = int(np.ceil(total_video_count / 50))*2
print('총 영상 수 :', total_video_count)
print('예상 유닛 비용: ',total_spend_unit)

가지고 있는 유닛 수:  6059
총 영상 수 : 28056
예상 유닛 비용:  1124

In [119]:
# =======================================================================
# IT 기업 채널의 영상정보 수집 API
# =======================================================================

print('가지고 있는 유닛 수: ', total_unit)

for channel_id in it_filtered_channel_list['channel_id'].to_list()[2:]:
    
    video_count = it_filtered_channel_list.loc[
        it_filtered_channel_list['channel_id'] == channel_id,
        'video_count'
    ].iloc[0]
    
    get_playlist_video_info(
        youtube_api_key,
        channel_id=channel_id,
        max_results=video_count,
        save_path='./data/IT_video_ids.csv'
    )
    
    print(f"{channel_id} 채널의 영상 수 : {video_count}")
    
    spend_unit = int(np.ceil(video_count / 50))*2
    total_unit -= spend_unit
    
    print('현재 남은 유닛 수 :', total_unit)

가지고 있는 유닛 수:  6944
https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=UCVaIGU8ch9zG42j-rAG6VoA&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNESWlFRUUzUmpkQ1F6azNPRU0wUlRjeU1FSQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNHUWlFRFl6TXpBNVFrTTRNak5HUkRZMU1FTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKWUJJaEEyTmpVNVJETTRSRVk0TVRreU4wWkc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNZ0JJaEJDT1VFek1UVTFNakU1UXpnM01UQTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQb0JJaEF3TVVKQ01qSTNNRUpFTmpRd1FqaEM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLd0NJaEF5UkVFNE5UZzVORUUxUVVFNE5qSXo
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNONENJaEEyUXpSRk56bEdNMFUwTURVeVJERTE
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKQURJaEF3UlVaRk1qRTJORVJCTmtWQ05EUXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNSURJaEE0UlVFMVJVWkZSRUZGTkVZeU5qQkI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQUURJaEExTXpWRlJETXpOa1l4TkRReE5rWTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLWUVJaEF4UkVJME5UVXhNMFkwTjBWQ00wVXo
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOZ0VJaEExTWtaRE0wSXdPVU5CTlRnNE1qSXg
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJb0ZJaEEwTWtReE5FVkJOak5FT1VZeE5EWTM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMd0ZJaEF4UmpFNU5EazVRakl6TnpjMk1qZzU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPNEZJaEJCTnpGRk1UZ3pRVGd5TVVNek1ETXg
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLQUdJaEJDUWpWRU4wUTBORFpHUWpSR1JqRTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOSUdJaEE0TVRjMVJUZENSRE5GTmpNeU1rTTU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJUUhJaEJDTVVZd1JURTFSakZDUVVJMU16bEM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMWUhJaEE1UWpneFFqaERSakUzTWpFeU1rUXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPZ0hJaEF5UkRWQ05VUkJPVGMwTXpJMk1UWTM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKb0lJaEE0TWpnMk1FSTJOMEpETWpSRFJUSTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUVaIGU8ch9zG42j-rAG6VoA&maxResults=37&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNd0lJaEJDUkRJM01qVkdNakpFTnpZeVJUVkQ
UCVaIGU8ch9zG42j-rAG6VoA 채널의 영상 수 : 1137
현재 남은 유닛 수 : 6921
https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=UCqz8F0bdoDiyzgdYPZAdA-Q&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNESWlFRFpHT0RoRk9Ea3hOalF3TlVaRE5ESQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNHUWlFRUU1UlRReFFqVTRRak15UmpNM1JVWQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKWUJJaEEyTmpOR1JqbEdNRGcwT0RJek5rRTE
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNZ0JJaEJCT0RrME5EQXpPVGMyUlRSRE9ERkM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQb0JJaEJDTkRFeU1rRTFOamt5TTBFNFFUTXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLd0NJaEJFUTBZMVFrTXpORGd4UWpOQ01qRTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNONENJaEExTURVME1qY3hRVGMxTVVFMVFqazE
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKQURJaEEwUVRnMFJVTkJOVU5GTXpORE1FUTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUqz8F0bdoDiyzgdYPZAdA-Q&maxResults=23&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNSURJaEF5UkRFMlEwSTBSa0kwUVVGRE9FWkI
UCqz8F0bdoDiyzgdYPZAdA-Q 채널의 영상 수 : 473
현재 남은 유닛 수 : 6911
https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=UCwR9k7QggFEfeHkvTR31JcA&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNESWlFRUkxUkRJek5VRTNRamszUVRJNU5ETQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNHUWlFRE0zT0RaQk56azNNRU16T1RCRFJEYw
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKWUJJaEExT0RZMU5VSTFPVFpGTnpFek1rWXo
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNZ0JJaEJEUkVNMU9FVTRPVGd3UVRnMFFUa3g
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQb0JJaEEwT0RKQ1JUTXhRek5GTWpWRFF6VXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLd0NJaEJCTTBZd1EwUkNSRVUwTlVJNE9VSkY
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNONENJaEJDTWtGR00wTXpNVGM1T0RRME1USTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKQURJaEJDT0RkQk1UVTNNemN6T0VaQ01rUTU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNSURJaEJCUmpZeFF6QTBRekkxTlVNMU5UazA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQUURJaEJDTVRaR1JqbEVNemhCT0RsRE5rUTI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLWUVJaEF6UVRjek5qYzVNemc1TlRVek9URkc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOZ0VJaEJFT0RVME1VSkdSRFJETXpNeVJFTXc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJb0ZJaEEyTkRVeU56RXdNMEZFUTBSRk9UWkQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMd0ZJaEJDUWpjek9EQXlOVGs0UWpoRlJFRXc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPNEZJaEJGTURKQ056SkVOa00xUWpBMU56ZzU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLQUdJaEF5UmtZM1FqWkdPRE0xTXpaRk1UaEI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOSUdJaEEzUmtNM1JURkdSVVJFTWpJM05EazQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJUUhJaEJCUWpFeFF6WXdOemt6UmtRMVFqVTI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMWUhJaEEwTmpjek56QTRRa1JHTUVJMk0wVkU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPZ0hJaEJGUTBaQk1ERTVOVUpGTjBOQk16a3c
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKb0lJaEJFTVRZNE1EUkNSams1UlVVM05VSTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNd0lJaEF5TWpORU9UWkdSRFF6T1VRM1JqTTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQNElJaEJETlRJNU1rSTVSa0kxUlRnMVJFVkI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMQUpJaEJFUkRVMk9VTXdNVVE0UkRZeVFqRkQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPSUpJaEF6TURsRlJVRkdRVE5DTlVaR1JVWkc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKUUtJaEF5TXpReFJUVTVPRVkwTXpjNVEwUXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNWUtJaEJCUXprek9UZEROVGMwTUVVeU56RXc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQZ0tJaEJGTXpVeFJrUTBNRUl6T1VKRE1EUkY
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLb0xJaEJFTlRjME1qZzBOMEU1UkRRek1FWXc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOd0xJaEF4TTBKRlJqQTBSVGhGUmpjeVFqWkQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJNE1JaEE1UTBORk5VUTVSRFU1T1RnNU0wUTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNQU1JaEE1UVVJd05FTkRSa0l4UmtFM05ERXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQSU1JaEEzUTBFeFJETXhNa0l4TURsQk5VRXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLUU5JaEF5UTBVMFFrRXpRekl5TjBFNE1qRTI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOWU5JaEEzUkRCRk5FWXhRVU14TWpkQ05EZzE
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJZ09JaEE1TUVFNE1FUTFPRFE0UkRrNE1qaEI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMb09JaEJCUWpZd01EVXpNa1E1TmtSR09EWXo
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPd09JaEF4UmpoQ09FTXpNakpHTkRCRE1qUTU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKNFBJaEJCT0VKQlF6RkRRVUZEUkRjMk5qZEU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOQVBJaEJFT1VFek0wRTJOakl3UlRFek16VTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJSVFJaEEzUmpsRE1UYzJOVE00TkRVMU0wWTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMUVFJaEJDTWpZNE1UWTBSa1k0TmpnelJVWkM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPWVFJaEF6TTBJMk1EZERNa0UzTlRreU16UTU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKZ1JJaEF3TVRkRFFqazRPRVk1UXpOR1F6QkY
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNb1JJaEF5T1VVNFJUSkRSVEZCUTBJM04wUkI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQd1JJaEF4T1VNeE5rVkNSVFJETVVZMVJERTI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLNFNJaEF5TmtaQ016bEJPVFpGT1VaQk9EVTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPQVNJaEF5UXpReVFUTXlNa0UxUkRnMk5FTXc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKSVRJaEF6T1RVek9FTkJRamd4TkRoQlJVVXg
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNUVRJaEE0UTBVd1JqWXlRMEUxTWpVeFEwVkc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQWVRJaEF4T0RJd1Jqa3hNRU5FTnpoQ056Rkc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLZ1VJaEJFT1RFek1VRkRRa0pGTlRJd1JrSTU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOb1VJaEJFT1VWRU1rWkdRVFk1TUVSRU1FWkQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJd1ZJaEJDUXpWRk9UZEVSRGN4TlRBd01rSkM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMNFZJaEF3TlVaQk1rTTBNelpGTnpJNVEwUkI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUwR9k7QggFEfeHkvTR31JcA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQQVZJaEEzT0RSR05EWkZSREkzTTBFeE5rVXc

In [ ]:
# =======================================================================
# 유닛 비용 계산
# =======================================================================

print('가지고 있는 유닛 수: ', total_unit)
total_video_count = np.sum(food_filtered_channel_list['video_count'])
total_spend_unit = int(np.ceil(total_video_count / 50))*2
print('총 영상 수 :', total_video_count)
print('예상 유닛 비용: ',total_spend_unit)

가지고 있는 유닛 수:  6059
총 영상 수 : 21197
예상 유닛 비용:  848

In [129]:
# =======================================================================
# FOOD 기업 채널의 영상정보 수집 API
# =======================================================================

print('가지고 있는 유닛 수: ', total_unit)

for channel_id in food_filtered_channel_list['channel_id'].to_list():
    
    video_count = food_filtered_channel_list.loc[
        food_filtered_channel_list['channel_id'] == channel_id,
        'video_count'
    ].iloc[0]
    
    get_playlist_video_info(
        youtube_api_key,
        channel_id=channel_id,
        max_results=video_count,
        save_path='./data/FOOD_video_ids.csv'
    )
    
    print(f"{channel_id} 채널의 영상 수 : {video_count}")
    
    spend_unit = int(np.ceil(video_count / 50))*2
    total_unit -= spend_unit
    
    print('현재 남은 유닛 수 :', total_unit)

가지고 있는 유닛 수:  6503
https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=UCsM07dUwo0WOWhFbVsG8K6A&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNESWlFREpEUmpZM056VkdSVU5ETnpCRE5UQQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNHUWlFREEzTTBOQ1JrTTBNMEU1TVVRek1rTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKWUJJaEJHT0RSR01UUkZOVVZGUWtKRk56UXo
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNZ0JJaEEyTnpKRFJrTkRRekk0TlRkQk5rUTI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQb0JJaEJCUVRFNU56SkVORUV6TlVRMFFqWkM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLd0NJaEJCUmpCQk5UTTRNamN4TmpSQ09ERkQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNONENJaEEyUkVFeU1qWkJOa0pGUVVWRk9FUkI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKQURJaEEzTkVNMVFVWkVOekkyTVRsRU5qQXo
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNSURJaEE0TlVNMlJqWkJOa0pGTmtSQ1FUQXo
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQUURJaEJEUlVSQk9UZzRNVGc0TWpSRU5UWTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLWUVJaEF3UlRrNU1qWXhNamt5TXpCR1F6Y3k
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOZ0VJaEF3TjBaRlJqa3pOVUl6T1RZNE9URkY
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJb0ZJaEJHUlRVeU5VWXlNMEU0UWpaQ09UWXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMd0ZJaEJHUTBVek56TkJSVFl3TVRJd09UZ3c
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPNEZJaEEyT1RkRVFUUTFRVE5HTVRRNU0wUkI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLQUdJaEJHUTBNeE1FWkJNVU5HTjBNeFJrWTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOSUdJaEExUkRNMlF6UXdSa0k1UWtFNE9EVTM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJUUhJaEJEUmtZMU1VUXhSVEpDUmtJNU16QkU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMWUhJaEJHTWtKRk9UTXlRemd3TTBGRFFqRkQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPZ0hJaEF3UkRBMVJqWXlORFpEUWpGRFFUa3g
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKb0lJaEF6UVVVMU5qVkVNVGMyTVRrMlFrTTM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNd0lJaEJDUlVJNE1qVkVOVGxHTmpZM1EwVkM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUsM07dUwo0WOWhFbVsG8K6A&maxResults=23&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQNElJaEE1UTBNek16STFNa0V3TURKR1FUVkU
UCsM07dUwo0WOWhFbVsG8K6A 채널의 영상 수 : 1173
현재 남은 유닛 수 : 6479
https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=UCl0HemfAt7dShJRf59_cuGQ&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNESWlFRVE1TmtFM01VUTBNRGhGTmtJMk5UUQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNHUWlFRVJFTmpVMk5EbENRVE5CUkRRNE1VTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKWUJJaEF6TnpVek9FSTVRVVpETVRORU9EQkM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNZ0JJaEJCUkVVMk16Y3lNRUU1UlRjM05FSTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQb0JJaEF3UkVFeE9VSkNNRVkyTlRJek1ESkM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLd0NJaEF6TlVVeU5rUTRPRU5GTmtGQ1JEQkY
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNONENJaEEzTUVVMU5EQkNOVEk1TlRRNE1VUTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKQURJaEJCUlRoR1FrRkRSakpEUlVGRU16RTU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNSURJaEJGTmtZd1JUQXlRa1EyUWpJMU5qZEU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQUURJaEJCUVVNd1JVTkVNVEZFT0VJeVFUTkQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLWUVJaEJETmpnd016aEVNelpDTXpJM016bEI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOZ0VJaEEyTjBRM09EazJOVGMyTnpZNVFqSkc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJb0ZJaEJCUVVVNE1FUTJSakk1UmpoR1FqTXo
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMd0ZJaEJDUkVGRk16WkRRVGM0T1RjM00wSTE
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPNEZJaEEyTkRNd01UY3lPRVl5TVRFeE5URTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLQUdJaEEzTmpRNU1UWkZNemcwUmpZelFqYzQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOSUdJaEExTlRJNU1URTNOemt6UVRJeVFUWXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJUUhJaEF6T1VWRlJqWkJPRGxHTXpGR09UazE
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMWUhJaEEyTWpJM1FqVkVNRFpHTURRNE5qQXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPZ0hJaEJFTXpBd01FTTVSREpHTmprM1JqSTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKb0lJaEF6T0RZd056TkVNemhHUTBOQlJEUTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNd0lJaEJEUkRWRVEwWTFORE5DTjBVek9EVTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQNElJaEJDT0VZek5qVkdORVV6UlVNeU1FVkU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMQUpJaEEwT0ROR1FVTXdPRUpFUlVZM1JVUXo
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPSUpJaEEzUmpZd1FqYzBOa05DUWtJMU9UaEY
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKUUtJaEE0UlVWRk56UTVSakZCTUVRNU5FSXc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNWUtJaEJDUlVZNVEwUkJSVUpFT1RORU1UQkI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQZ0tJaEF4UmprNE5UUTNOVU5FTkRVNE5ESTA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLb0xJaEF3TmpNek1EY3pOVVU0UlVRM1JVSkc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOd0xJaEExTlRreE5EVkZOemM1TlVKRk0wVTU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJNE1JaEF4UmtaRk5UTXpPRFpHTWtaRE5FWkM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNQU1JaEE1TWtVeU1rVTRNMFk1UVVJelEwRkQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQSU1JaEJGTURBMU9UVkdSVFpHUVRkRk1VWXg
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLUU5JaEF3UWpBNU9VRXdRalpGUWpGQ05qZzA
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOWU5JaEExUmpnMk1ESXpPVVJFUmpnek1rWTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJZ09JaEF4UmpGQ00wWXlPVFF4TWpJelEwVXc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMb09JaEJHTjBKQlF6ZENORUl3TURjeU1EWTI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPd09JaEEzUkRORk16STJRMFE0TVRSRlJURkY
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKNFBJaEExTXpsRk9EWkRNVEpCTkROQk1qSTM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNOQVBJaEJGTUVaQk9UWTNSa1JEUVRCR016QkY
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNJSVFJaEEzUlVZNE1EUkVRekV6UXpZd1FUazQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNMUVFJaEJDUlRSRU9UWTFSVUV5T0RFMVEwWkI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPWVFJaEE0UmpkRU5qazFSamM0UVVNNE5ESkY
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKZ1JJaEF3T0RoRU1UWTNPVEZDUmtVek5FRXc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNb1JJaEF4UlRnNVJFRTFPREZDUTBRMlEwWTE
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQd1JJaEF4TWtKQlJFSTVSRUZETkRnM1FUUTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNLNFNJaEExUVRWR1FqbERRVFpFUVRjMk5UVTQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNPQVNJaEE0T1VNNU5EUkdSa1JHTnpaRk5UWTU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKSVRJaEEzTTBRNU1EUXpNa1F4TlRBNFFrUXc
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNUVRJaEEzTjBJeU5rUkZSRU16TXpjMVFUQXk
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUl0HemfAt7dShJRf59_cuGQ&maxResults=30&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQWVRJaEJCUkVORU5qbERSVFF5TURRM05UTXo
UCl0HemfAt7dShJRf59_cuGQ 채널의 영상 수 : 2580
현재 남은 유닛 수 : 6427
https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=UCG_gfzGVpsxGwYuFgH8-tNA&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUG_gfzGVpsxGwYuFgH8-tNA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUG_gfzGVpsxGwYuFgH8-tNA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNESWlFRUZDUmpjeU9FVXdRVVpHTnpoRVFrWQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUG_gfzGVpsxGwYuFgH8-tNA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNHUWlFRGd4TmpsRU1rWkdRa1F5TVRRMVF6WQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUG_gfzGVpsxGwYuFgH8-tNA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKWUJJaEF6UkRVMk5VUkdRekpHTVRoQk9UZEQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUG_gfzGVpsxGwYuFgH8-tNA&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNZ0JJaEF4TVRnelJFTkRRelJFT0VGQ1FUYzU
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUG_gfzGVpsxGwYuFgH8-tNA&maxResults=4&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQb0JJaEJFTkVGRE1UQkVORUUzTnpnNE5FSTE
UCG_gfzGVpsxGwYuFgH8-tNA 채널의 영상 수 : 254
현재 남은 유닛 수 : 6421
https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=UCfv1dkNKCFUtZouvp3DhS3g&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUfv1dkNKCFUtZouvp3DhS3g&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUfv1dkNKCFUtZouvp3DhS3g&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNESWlFRFEzUkRnNE5VUkZPRU15TnpKQlJqSQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUfv1dkNKCFUtZouvp3DhS3g&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaHlBUOkNHUWlFRU15UXprMlF6SkVRemM0TURSRk1ERQ
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUfv1dkNKCFUtZouvp3DhS3g&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNKWUJJaEJHT0VNNFFrWTFNRUk0TVRRM05ERTM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUfv1dkNKCFUtZouvp3DhS3g&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNNZ0JJaEJDTkRKRU9ERTBSVEkyT0RBNE9UZEM
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUfv1dkNKCFUtZouvp3DhS3g&maxResults=27&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&pageToken=EAAaH1BUOkNQb0JJaEExTlRoRU5ETkVSRFkyT0RaRFEwVTU
UCfv1dkNKCFUtZouvp3DhS3g 채널의 영상 수 : 277
현재 남은 유닛 수 : 6415
https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=UCDryA2PIGnbs9NYn_63rISw&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI
https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=UUDryA2PIGnbs9NYn_63rISw&maxResults=50&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI

---
#### 영상 상세 정보 출력
    - 이제 본 분석에 사용될 영상의 상세 정보를 가져온다.

---

In [ ]:
# =======================================================================
# 영상 상세 정보 불러오기 : get_video_info(arg1, arg2, arg3)
# arg1: 영상 상세정보를 가져올 유튜브 API키 입니다. (필수)
# arg2: 영상 상세정보를 가져올 Video_id의 리스트입니다. (필수)
# arg3: 영상 상세정보를 저장할 경로입니다. (필수. 예: save_path = './data/test.csv')
#
#   - 비용: 영상 50개 당 1 유닛
#
# [불러올 정보]
# 1. 영상 아이디(video_id): 영상이 가지고 있는 고유 아이디 값입니다.
# 2. 영상 제목(title): 영상 제목
# 3. 채널 아이디(channel_id): 해당 영상을 업로드한 채널의 고유 아이디 값입니다.
# 4. 채널 이름(channel_title): 해당 영상을 업로드한 채널의 이름입니다.
# 5. 영상 설명(description): 업로더가 작성한 해당 영상의 설명입니다.
# 6. 영상 업로드 날짜(upload_date): 영상이 업로드된 날짜입니다.
# 7. 영상 키워드 태그 목록(tags): 영상의 키워드 태그 목록입니다.
# 8. 영상 카테고리 아이디(category_id): 영상이 속해있는 카테고리의 고유값 입니다.
# 9. 조회수(view_count): 해당 영상의 조회수입니다.
# 10. 좋아요 수(like_count): 해당 영상의 좋아요 수 입니다.
# 11. 댓글 수(comment_count): 해당 영상의 댓글 수 입니다.
# 12. 영상 길이(duration): 해당 영상의 길이입니다. (형식: PT#H#M#S, T: 일, H: 시간, M: 분, S: 초)
# 13. 고화질 여부(definition): 영상을 고화질로 시청할 수 있는지 여부입니다. (hd(High Definition): 고화질 시청 가능, sd(Standard Definition): 일반화질 시청)
# 14. 동영상 라이선스(license): 동영상 라이선스 정보입니다. creativeCommon: 출처를 표시하면 영상의 재편집/재배포가 가능, youtube: 영상 재편집/재배포 불가능
# 15. 임베딩 가능 여부(emabeddable): 영상을 다른 웹사이트에 퍼갈 수 있는지 여부 (광고 영상을 전광판이나 특정 홈페이지에서 계속 송출한다면 조회수가 올라가지 않을까?)
# 16. 유료 PPL 여부(has_paid_product_placement): 유료 PPL 사용 여부 (True/False)
# 17. 썸네일 이미지 url(thumbnail): 고화질 썸네일 이미지의 url을 가져옵니다.
# 18. 썸네일 높이(thumbnail_h): 고화질 썸네일 이미지의 높이를 가져옵니다.
# 19. 썸네일 너비(thumbnail_w): 고화질 썸네일 이미지의 너비를 가져옵니다.
# =======================================================================

def get_video_info(api_key, video_ids=None, save_path=None):
    
    # 영상 정보 수집 API url 가져오기
    url = 'https://www.googleapis.com/youtube/v3/videos'
    all_results = []
    
    if not video_ids:
        print('video_ids가 없습니다.')
        return pd.DataFrame()
    
    if save_path is None:
        raise ValueError('파일을 저장할 경로를 입력해주세요.')
    
    # 기존 video_id 불러오기
    existing_video_ids = set()
    
    if save_path and os.path.exists(save_path):
        existing_df = pd.read_csv(save_path)
        if 'video_id' in existing_df.columns:
            existing_video_ids = set(existing_df['video_id'].dropna().astype(str)) # video_id 결측없이/문자형/set(중복 없음, 순서없음, 집합개념) 형태로 가져오기
    
    # 중복 제거 & 리스트로 변환
    video_ids = [str(v) for v in video_ids if v] # 만약 영상 아이디가 video_ids에 포함되고, 값이 존재한다면 문자열로 변환된 영상 아이디를 출력 반복
    video_ids = list(dict.fromkeys(video_ids))
    
    # 이미 저장된 video_id 제외
    if existing_video_ids:
        video_ids = [vid for vid in video_ids if vid not in existing_video_ids]
    
    # 불러올 video_id가 없을 때
    if not video_ids:
        print('새로 수집할 video_id가 없습니다.')
        return pd.DataFrame()
    
    for i in range(0, len(video_ids), 50):
        batch_ids = video_ids[i:i+50]
        
        params = {
            'part': 'snippet,statistics,contentDetails,status,paidProductPlacementDetails',
            'id': ','.join(batch_ids),
            'key': api_key
        }
    
        r = requests.get(url, params=params, timeout=30)
    
        if not r.ok:
            print('status_code :', r.status_code)
            try:
                print('error_json :', r.json())
            except Exception:
                print('error_text :', r.text)
            break
        
        data = r.json()
        items = data.get('items', [])
        
        for item in items:
            snippet = item.get('snippet', {})
            statistics = item.get('statistics',{})
            content_details = item.get('contentDetails', {})
            status = item.get('status', {})
            ppl = item.get('paidProductPlacementDetails', {})
            # file_details = item.get('fileDetails', {})
            # processing_details = item.get('processingDetails',{})
            # suggestions = item.get('suggestions', {})
            
            all_results.append({
                'video_id' : item.get('id'), # 영상 아이디
                'title' : snippet.get('title'), # 영상 제목
                'channel_id' : snippet.get('channelId'), # 채널 아이디
                'channel_title' : snippet.get('channelTitle'), # 채널 이름
                'description' : snippet.get('description'), # 영상 설명
                'upload_date' : snippet.get('publishedAt'), # 영상 업로드 날짜
                'tags' : ', '.join(snippet.get('tags', [])), # 영상 키워드 태그 목록
                'category_id' : snippet.get('categoryId'), # 영상의 카테고리 아이디
                'view_count' : statistics.get('viewCount'), # 영상의 조회수(Shorts 영상은 최소 시청조건 없음. 재생 또는 다시보기 시작되는 횟수 반환)
                'like_count' : statistics.get('likeCount'), # 영상에 좋아요를 표시한 사용자 수
                'comment_count' : statistics.get('commentCount'), # 영상의 댓글 개수
                'duration' : content_details.get('duration'), # 영상 길이 (PT#H#M#S 형식)
                'definition' : content_details.get('definition'), # 영상을 고화질로 시청할 수 있는지 여부 (hd, sd 형식)
                # 'content_rating' : content_details.get('contentRating'), # 다양한 평가 기준에 따라 동영상이 받은 평가
                # 'kmrb_rating' : content_details.get('contentRating', {}).get('kmrbRating'), # 대한민국 영상물등급위원회(KMRB) 등급(예: 전체 관람가)
                'license' : status.get('license'), # 동영상 라이선스 (creativeCommon: 타인의 영상 재편집, 재배포 가능, 출처 표기 / youtube: 재사용/수정 불가)
                'embeddable' : status.get('embeddable'), # 영상을 다른 웹사이트에 퍼갈 수 있는가?
                'has_paid_product_placement' : ppl.get('hasPaidProductPlacement'), # 유료 PPL이 사용되는 경우 true, 아니면 False
                # 'width_pixels' : file_details.get('videoStream[]', []).get('widthPixels'), # 콘텐츠 가로 너비
                # 'height_pixels' : file_details.get('videoStream[]', []).get('heightPixels'), # 콘텐츠 세로 높이
                # 'aspect_ratio' : file_details.get('videoStream[]', []).get('aspectRatio'), # 콘텐츠 가로세로 비율
                # 'vendor' : file_details.get('videoStream[]', []).get('vendor'), # 동영상 공급업체 코드
                # 'tag_suggestions_availability' : processing_details.get('tagSuggestionsAvailability'), # 동영상에 키워드 추천을 사용할 수 있는지 여부 (동영상을 더 쉽게 찾을 수 있도록 동영상의 메타데이터에 태그 추가 가능.)
                # 'tag' : suggestions.get('tagSuggestions[]', []).get('tag'), # 영상에 추천된 키워드 태그 
                # 'category_restiricts' : suggestions.get('tagSuggestions[]', []).get('categoryRestricts[]'), # 태그와 관련된 동영상 카테고리 집합
                # 'caption' : content_details.get('caption'), # 자막을 사용할 수 있는지 여부(bool)
                'thumbnail' : snippet.get('thumbnails', {}).get('high',{}).get('url'), # 영상 썸네일(고해상도)
                'thumbnail_h' : snippet.get('thumbnails', {}).get('high',{}).get('height'), # 영상 썸네일 높이
                'thumbnail_w' : snippet.get('thumbnails', {}).get('high',{}).get('width'), # 영상 썸네일 높이
            })
        
    # 영상정보 결과 데이터 프레임으로 저장
    df= pd.DataFrame(all_results)
    
    # 파일로 저장.
    if save_path and not df.empty: # 경로가 존재하고, 데이터 프레임이 비어있지 않다면,
        os.makedirs(os.path.dirname(save_path), exist_ok=True) if os.path.dirname(save_path) else None
        
        if not os.path.exists(save_path):
            df.to_csv(save_path, index=False, encoding='utf-8-sig')
        else:
            df.to_csv(save_path, mode='a', header=False, index=False, encoding='utf-8-sig')
    return df

In [ ]:
# =======================================================================
# 유닛 비용 산출 및 가져올 영상 수 정의 : main_video_info(arg1, arg2, arg3, arg4, arg5)
# 
# arg1: 유튜브 API 키
# arg2: 유튜브 API 키 (예비1)
# arg3: 유튜브 API 키 (예비2)
# arg4: 영상 아이디 리스트
# arg5: csv 파일 저장 경로 (예: save_path = './data/result/data1.csv')
#
# [설명]
# 가진 유닛에 맞게 비용을 산출하여 영상 상세정보를 가져오는 함수로 상세정보를 가져오는 함수입니다.
# 이 함수는 이미 해당경로에 불러온 영상 상세정보를 필터링하여 중복을 방지하는 기능도 포함하고 있습니다.
# 남은 유닛 수를 자동으로 가져올 수 없으므로 수동으로 체크해서 가져오셔야 합니다.
# =======================================================================
def main_video_info(youtube_api_key=None, youtube_api_key2=None, youtube_api_key3=None, video_ids=None, save_path=None):
        
    if save_path is None:
        raise ValueError('파일을 저장할 경로를 입력해주세요')
    
    if video_ids is None:
        raise ValueError('영상 아이디 리스트를 입력해주세요.')
    
    # 사용 가능한 유닛 수 계산
    print('='*25, '시작', '='*25)
    print('남은 유닛 수 확인 : https://console.cloud.google.com/iam-admin/quotas?hl=ko')
    
    unit1 = unit2 = unit3 = 0
    if youtube_api_key is not None:
        unit1 = 10000 - int(input('첫 번째 API의 사용한 유닛 수를 입력해주세요(사용량 입력): '))
    if youtube_api_key2 is not None:
        unit2 = 10000 - int(input('두 번째 API의 사용한 유닛 수를 입력해주세요(사용량 입력): '))
    if youtube_api_key3 is not None:
        unit3 = 10000 - int(input('세 번째 API의 사용한 유닛 수를 입력해주세요(사용량 입력): '))
    
    if (youtube_api_key is None) and (youtube_api_key2 is None) and (youtube_api_key3 is None):
        raise ValueError('유튜브 API 키를 입력해주세요.')
    
    total_units = unit1 + unit2 + unit3
    if total_units == 0:
        print('사용 가능한 유닛이 없습니다.')
        return
    
    for api_key in [youtube_api_key, youtube_api_key2, youtube_api_key3]:
        # api_key 있는 것만 사용
        if api_key is None:
            continue
        # 이미 저장 완료된 video_id 가져오기
        existing_video_ids = set()
        if save_path and os.path.exists(save_path):
            existing_df = pd.read_csv(save_path)
            if 'video_id' in existing_df.columns:
                existing_video_ids = set(existing_df['video_id'].dropna().astype(str)) # video_id 가져오기 완료
    
        # 중복 제거된 video_ids 다시 산출
        video_ids = [x for x in video_ids if x not in existing_video_ids]
        
        if len(video_ids) == 0:
            break
        # 조회 가능한 데이터 수
        print('가지고 있는 유닛 수: ', total_units)
        print('총 video_id 개수: ', len(video_ids))
        possible = total_units * 50
        
        print(f'{len(video_ids)}개의 영상 중 {possible}개의 영상이 조회가 가능합니다.')
        get_videos = 0
        while total_units > 0:
            # 조회 가능한 영상 수인지 확인하기
            get_videos = input(f'{len(video_ids)}개의 영상 중 몇 개의 영상을 조회하시겠습니까? (종료: N) :')
            if get_videos == 'N':
                break
            else:
                get_videos =int(get_videos)
                
            if np.ceil(get_videos / 50) > total_units:
                print('가지고 있는 유닛 수로 조회하기엔 영상이 너무 많습니다.')
                get_videos = 0
            
            if total_units == 0:
                break
            
            if get_videos == 0:
                break
            print(f'예상 비용 : {np.ceil(get_videos/50)} 유닛')
            video_list = video_ids[0:get_videos]
            
            get_video_info(api_key=api_key, video_ids=video_list, save_path=save_path)
            total_units = total_units - (np.ceil(get_videos/50))
            
            video_ids = [x for x in video_ids if x not in video_list]
            
            print(f'남은 유닛: {total_units}')
            if total_units <= 0:
                break
        if total_units <= 0:
            break
    return print(f'추출이 완료되었습니다. 파일 경로: {save_path}')

In [ ]:
# =======================================================================
# IT 영상 상세정보 남은 토큰 수에 맞게 가져오기
# =======================================================================
it_videos = pd.read_csv('./data/IT_video_ids.csv')
video_ids = it_videos['video_id'].to_list()
main_video_info(youtube_api_key=youtube_api_key, youtube_api_key2=youtube_api_key2, youtube_api_key3=youtube_api_key3, video_ids=video_ids, save_path='./data/results/it_video_info.csv')

========================= 시작 =========================
남은 유닛 수 확인 : https://console.cloud.google.com/iam-admin/quotas?hl=ko
가지고 있는 유닛 수:  25000
총 video_id 개수:  26843
26843개의 영상 중 1250000개의 영상이 조회가 가능합니다.
예상 비용 : 537.0 유닛
남은 유닛: 24463.0
추출이 완료되었습니다. 파일 경로: ./data/results/it_video_info.csv

In [ ]:
# =======================================================================
# FOOD 영상 상세정보 남은 토큰 수에 맞게 가져오기
# =======================================================================
food_videos = pd.read_csv('./data/FOOD_video_ids.csv')
video_ids = food_videos['video_id'].to_list()
main_video_info(youtube_api_key=youtube_api_key, youtube_api_key2=youtube_api_key2, youtube_api_key3=youtube_api_key3, video_ids=video_ids, save_path='./data/results/food_video_info.csv')

========================= 시작 =========================
남은 유닛 수 확인 : https://console.cloud.google.com/iam-admin/quotas?hl=ko
가지고 있는 유닛 수:  25000
총 video_id 개수:  21193
21193개의 영상 중 1250000개의 영상이 조회가 가능합니다.
예상 비용 : 424.0 유닛
남은 유닛: 24576.0
추출이 완료되었습니다. 파일 경로: ./data/results/food_video_info.csv

In [2]:
it_video_info = pd.read_csv('./data/results/it_video_info.csv')
food_video_info = pd.read_csv('./data/results/food_video_info.csv')
print(len(it_video_info))
print(len(food_video_info))

26843
21193