In [ ]:

# ========================================
# 필요한 라이브러리를 불러옵니다
# ========================================

import os
import time
import platform
from pprint import pprint
from typing import List, Literal, Optional


import requests
import json
import pandas as pd
import numpy as np
import time

import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from pydantic_ai import Agent, ModelRetry
from pydantic_ai.models.google import GoogleModelSettings
from concurrent.futures import ThreadPoolExecutor, as_completed

# 운영체제별 한글 폰트 설정
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'NanumGothic'

# 마이너스 기호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

# 출력 짤림 방지
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 50)

# .env 파일에서 API 키 로드
load_dotenv()
api_key = os.getenv('GEMINI_API_KEY')
gemini_model = os.getenv('GEMINI_MODEL', 'gemini-3.1-flash-lite-preview')
youtube_api_key = os.getenv('YOUTUBE_API_KEY')
youtube_api_key2 = os.getenv('YOUTUBE_API_KEY2')
youtube_api_key3 = os.getenv('YOUTUBE_API_KEY3')

# PydanticAI는 GEMINI_API_KEY 환경변수를 자동으로 인식합니다
# 모델 ID 형식: 'google-gla:{모델명}'
model_id = f'google-gla:{gemini_model}'

# API 키 유효성 검사
api_key_valid = api_key and 'YOUR_API_KEY' not in api_key
print(f"API 키 설정 확인: {'O' if api_key_valid else 'X'}")
if not api_key_valid:
    print("[주의] .env 파일에서 GEMINI_API_KEY를 실제 API 키로 설정해주세요!")
print(f"모델 확인: {model_id}")

youtube_api_key_valid = youtube_api_key and 'YOUR_API_KEY' not in youtube_api_key
print(f"유튜브 API 키 설정 확인: {'O' if youtube_api_key_valid else 'X'}")
if not api_key_valid:
    print("[주의] .env 파일에서 YOUTUBE_API_KEY를 실제 API 키로 설정해주세요!")

# API 호출 간격 (초) - 무료 플랜에 맞게 조정
API_DELAY = 3

API 키 설정 확인: O
모델 확인: google-gla:gemini-3.1-flash-lite-preview
유튜브 API 키 설정 확인: O

In [2]:

# =============================================================
# IT 기업리스트
# 생성된 데이터 프레임: it_channel_list
# 생성된 csv 파일 이름: IT채널정보조회.csv
# =============================================================
with open('./data/checkpoint_IT(배치처리).json', encoding='utf-8') as f:
    it_data = json.load(f) # Ai Agent가 정리한 IT기업의 채널 리스트 로드

it_records = [] # 데이터를 담을 빈 리스트 생성

# channels에 들어있는 dict 확장
for company in it_data:
    company_name = company['company_name']
    has_official = company['has_official']
    
    for ch in company['channels']:
        it_records.append({
            'company_name': company_name,
            'has_official': has_official,
            'channel_id': ch.get('channel_id'),
            'channel_name': ch.get('channel_name'),
            'channel_handle': ch.get('channel_handle'),
            'channel_url': ch.get('channel_url'),
            'channel_reason': ch.get('channel_reason')
        })

it_channel_list = pd.DataFrame(it_records)
it_channel_list.to_csv('./data/IT채널정보조회.csv')
it_channel_list.head()

# =============================================================
# 작성된 기업 리스트를 기반으로 수기로 하나하나 검증 중 . . .
# 완료!
# ============================================================= 

# 기업 채널 리스트 가져오기
it_channel_list2 = pd.read_csv('./data/IT리스트 정리.csv', encoding='euc-kr')

# 채널이 없는 기업 제외
it_channel_list2 = it_channel_list2.loc[it_channel_list2['channel_name'].notna(), ['company_name', 'channel_name', 'channel_id', 'channel_handle']]

# 정리된 채널 개수 확인
print('정리된 기업 채널 개수 :' , len(it_channel_list2['company_name']), '개')

정리된 기업 채널 개수 : 49 개

In [3]:

# =============================================================
# FOOD 기업리스트
# 생성된 데이터 프레임: food_channel_list
# 생성된 csv 파일 이름: FOOD채널정보조회.csv
# =============================================================

with open('./data/checkpoint_FOOD(배치처리).json', encoding='utf-8') as f:
    food_data = json.load(f) # Ai Agent가 정리한 FOOD기업의 채널 리스트 로드

food_records = [] # 데이터를 담을 빈 리스트 생성

# channels에 들어있는 dict 확장
for company in food_data:
    company_name = company['company_name']
    has_official = company['has_official']
    
    for ch in company['channels']:
        food_records.append({
            'company_name': company_name,
            'has_official': has_official,
            'channel_id': ch.get('channel_id'),
            'channel_name': ch.get('channel_name'),
            'channel_handle': ch.get('channel_handle'),
            'channel_url': ch.get('channel_url'),
            'channel_reason': ch.get('channel_reason')
        })

food_channel_list = pd.DataFrame(food_records)
food_channel_list.to_csv('./data/FOOD채널정보조회.csv')
food_channel_list.head()

# =============================================================
# 작성된 기업 리스트를 기반으로 수기로 하나하나 검증 중 . . .
# 완료!
# ============================================================= 

# 기업 채널리스트 가져오기
food_channel_list2 = pd.read_csv('./data/Book(실제 검증 채널).csv', encoding='utf-8-sig')

# 채널이 없는 기업 제외
food_channel_list2 = food_channel_list2.loc[food_channel_list2['channel_name'].notna(), ['company_name', 'channel_name', 'channel_id', 'channel_handle']]

# 정리된 채널 개수 확인
print('정리된 기업 채널 개수', len(food_channel_list2['company_name']), '개')

정리된 기업 채널 개수 70 개

---
#### 채널 정보 수집
   수집 목적:
   1. 채널 정보를 분석하여 사용할 최종 채널 리스트를 선정하기 위함.
   2. 이후 영상정보 검색시 채널 id 정보가 필요.

---

In [ ]:
# =============================================================
# 남은 토큰 관리를 위한 남은 토큰 수 입력
#   - https://console.cloud.google.com/iam-admin/quotas?hl=ko
#   - youtube api 키와 연결된 프로젝트 선택
#   - 서비스 Youtube Data API v3의 현재 사용량 확인.
# =============================================================
print('API 사용량 확인: https://console.cloud.google.com/iam-admin/quotas?hl=ko')
total_unit = 10000 - int(input('이미 사용하신 사용량을 입력해주세요. 예) 256 :'))
print('현재 남은 유닛 수 :', total_unit)

In [33]:

# =============================================================
# 채널 정보 불러오기 API : get_channel_info(arg1, arg2, arg3, arg4)
# arg1: 채널 정보를 불러올 때 사용할 유튜브 API키 입니다. (필수)
# arg2: 정보를 불러올 채널의 핸들명 입니다. (arg2, arg3 중 하나만 선택 입력)
# arg3: 정보를 불러올 채널의 핸들명 입니다. (arg2, arg3 중 하나만 선택 입력)
# arg4: 채널의 정보를 담을 리스트 변수명 입니다. 함수가 동작되기 전에 미리 생성되어 있어야 합니다.
# 
# [불러올 정보]
# 1. 채널 아이디(channel_id): 채널이 가지고 있는 고유 아이디 값입니다.
#   - 이후에 유튜브 검색 API 함수에서 쓰입니다. (채널 별 영상 아이디를 가져올 거임)
# 2. 채널 이름(title): 불러올 채널의 이름입니다.
# 3. 채널 설명(description): 채널에 대한 설명입니다.
# 4. 구독자 수(subscriber_count): 채널의 구독자 수입니다.
# 5. 총 조회수(view_count): 채널 모든 영상의 조회수를 합한 값입니다.
# 6. 총 영상수(video_count): 채널이 업로드한 공개된 영상의 개수입니다. (비공개 영상 포함 X)
# 7. 채널 썸네일(thumbnails): 채널의 썸네일입니다. url형식으로 제공됩니다.
# 8. 채널 개설일(created_date): 채널의 개설 날짜입니다.
# 
# 사용할 API: 유튜브 채널 API
#   - 비용: 채널 1개 당 1 유닛
#
# ※ 주의사항
#   - 이 함수는 handle의 리스트나, channel_id의 리스트를 받아서 한꺼번에 출력할 수 없습니다.
#   - 따라서 handle, channel_id는 함수에 한개씩만 들어가야 합니다. (리스트 넣지 말라는 얘기입니다.)
#   - 여러 개의 기업 채널에 대해서 정보를 얻고 싶다면, 반복문 속에 함수를 넣으십시오.
#   - 이 함수는 사용한 유닛량을 알려주지 않습니다. 정보를 얻고자 하는 채널의 수와 유닛량이 같다는 점을 참고해주십시오.
# =============================================================

def get_channel_info(api_key, handle=None, channel_id=None, list_name=None):
    url = 'https://www.googleapis.com/youtube/v3/channels'
    
    params = {
        'part': 'snippet,statistics,brandingSettings',
        'key':api_key
    }
    
    if handle:
        params['forHandle'] = handle
    elif channel_id:
        params['id'] = channel_id
    else:
        raise ValueError('handle 또는 channel_id 중 반드시 하나는 입력해야 합니다.')
    
    if list_name == None:
        raise ValueError('채널 정보를 받을 리스트를 입력해주세요')
    r = requests.get(url, params=params, timeout=30)
    r.raise_for_status()
    data = r.json()
    
    if not data.get('items'):
        return None
    ch = data['items'][0]
    temp ={
        'channel_id': ch['id'], # 채널 아이디
        'title': ch['snippet']['title'], #채널 이름
        'description': ch['snippet'].get('description'), #채널 설명
        'subscriber_count': ch.get('statistics', {}).get('subscriberCount'), # 구독자 수
        'view_count': ch.get('statistics',{}).get('viewCount'), # 채널 총 조회수
        'video_count': ch.get('statistics',{}).get('videoCount'), #채널 총 영상 수
        'thumbnails': ch['snippet'].get('thumbnails').get('default').get('url'), # 채널 프로필 사진?
        'created_date': ch['snippet'].get('publishedAt') # 채널 생성 날짜
    }
    list_name.append(temp)
    return list_name

In [32]:
# =============================================================
# IT 기업의 유튜브 채널 정보 수집 시작
# =============================================================
it_handle_list = it_channel_list2['channel_handle'].to_list() # 정제된 IT 채널 리스트를 가져옴

print('='*50)
print('현재 남은 유닛 수 :', total_unit)
print('사용 예정 유튜브 API 유닛 :', len(it_handle_list), 'units')

it_list = [] # it 채널의 정보를 담을 리스트 생성
unit= 0 # 유닛 수 계산 시작!
for handle in it_handle_list:
    get_channel_info(youtube_api_key, handle=handle, list_name=it_list)
    unit += 1
total_unit = total_unit - unit
print()
print('실제 사용된 유튜브 API 유닛: ', unit, 'units')
print('남은 유닛 수: ', total_unit)
print('='*50)

# IT 채널 정보 리스트 데이터프레임으로 변환
it_channel = pd.DataFrame(it_list)
print()
print('수집 결과:')
display(it_channel)
# csv로 저장
it_channel.to_csv('./data/IT채널정보조회.csv', encoding='utf-8-sig')

==================================================
현재 남은 유닛 수 : 7200
사용 예정 유튜브 API 유닛 : 49 units
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200
남은 유튜브 유닛:  7200

실제 사용된 유튜브 API 유닛:  49 units
남은 유닛 수:  7151
==================================================

수집 결과:

,channel_id,title,description,subscriber_count,view_count,video_count,thumbnails,created_date
0,UCA5vKQkvC9zlTDOSNtoMdCQ,SK telecom,SK telecom 공식 YouTube 채널,1130000,1313042518,2705,https://yt3.ggpht.com/ytc/AIdro_m_9Gd-5ejb35YE...,2011-01-12T06:00:00Z
1,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"AI NOW & NEXT\n오늘날 AI로 이룬 혁신을 경험하고, 내일의 도약을 위한...",5320,192389,324,https://yt3.ggpht.com/BUovhY65Fkq3930DuKeBjwJB...,2022-08-04T08:01:36.337173Z
2,UCp3BSINVC7Ggj4kChEUiy7Q,LG유플러스 (LG Uplus),LG U+ 공식 Youtube 채널 \n,660000,1942109825,3713,https://yt3.ggpht.com/MXGutyn0ZJqNgLb5bPGj514z...,2011-12-19T07:47:10Z
3,UCVaIGU8ch9zG42j-rAG6VoA,삼성SDS,AI 풀스택 역량으로 기업의 AX를 선도하는 업무 혁신 파트너\n삼성SDS 공식 Y...,43200,74705486,1137,https://yt3.ggpht.com/v7Jgiy1VlR5ps-jDUHkpnzgf...,2016-10-04T07:31:53Z
4,UCqz8F0bdoDiyzgdYPZAdA-Q,LG CNS,Global AX 전문기업 LG CNS의 공식 유튜브 채널입니다.,76200,68795597,473,https://yt3.ggpht.com/gm9Yi3503swI8kz0XgMxY-xZ...,2012-05-16T04:55:12Z
5,UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,SK 브로드밴드 공식 유튜브 채널입니다\n,75600,179249506,4330,https://yt3.ggpht.com/ojNY0Wvjfp63Lazv7n4DDAOo...,2014-06-20T06:54:37Z
6,UCjyYouHWnID_L4QaQ6U4voQ,네이버 NAVER,네이버 공식 유튜브 채널입니다.,32600,288223085,862,https://yt3.ggpht.com/D-DsROA_yjJi-B1x4nnHXXws...,2012-11-22T12:07:43Z
7,UCBjvBJgIp3NGkrTBEfWBUVw,카카오,일상에 스며든 카카오의 다양한 이야기를 전합니다. 카카오 공식 유튜브 채널.,132000,254319875,910,https://yt3.ggpht.com/SSvyEl7-5J4DlWtbrHfeERIs...,2012-03-26T03:51:31Z
8,UCRBtxwx23bzxyr5R9vFRYhw,현대오토에버,여기는 현대오토에버 공식 YouTube 채널입니다.,10200,3748078,147,https://yt3.ggpht.com/L2QnWR1xkuWsogbZ91hIx6CY...,2019-10-29T05:34:14.878126Z
9,UCqqoiebjYnMqfhx-4f1awKg,Microsoft Korea,Microsoft 목표와 가치는 전세계의 사람과 기업이 잠재력을 최대한 발휘할 수 ...,18600,71104335,1845,https://yt3.ggpht.com/MRNhR0pURHfaJW1zLqGwGc7-...,2011-03-18T07:38:13Z
10,UCcFA2TC568rGp94OqMq3Nig,두나무 (Dunamu),"블록체인 및 핀테크 전문 기업, 두나무의 공식 채널입니다. \nhttps://dun...",151,741560,14,https://yt3.ggpht.com/Ly4SD65RKZXmvnEZsxla7afQ...,2022-11-08T05:33:24.840414Z
11,UCZHb3OEEJ0WkizEH9ErlgvA,Dell Technologies,Welcome to Dell Technologies' official YouTube...,47300,242314751,1200,https://yt3.ggpht.com/FNcLs-Wgkhb7ThCfRl7kg060...,2016-08-05T09:55:02Z
12,UC2wPiIf2xSXGTJNqo8UOY9g,네이버클라우드 l NAVER Cloud,"앞서가는 클라우드의 모든 것, 네이버 클라우드 ☁\n\n네이버 클라우드 플랫폼(NA...",14000,2255939,653,https://yt3.ggpht.com/cThadcW1wOQDycH764qZPBZc...,2017-04-03T09:39:28Z
13,UCwfd3z7HQcVAbwPiZw6JNRw,Synopsys SIG Korea,안녕하세요? 시높시스 SIG (Software Integrity Group) Kor...,5,36,2,https://yt3.ggpht.com/_A2V9syQtxSQfvhEOTwvaqpy...,2023-03-09T06:13:35.629477Z
14,UC7JJk_THjnffYi4xEh54AiQ,Kakao Entertainment,,1190,0,0,https://yt3.ggpht.com/ytc/AIdro_lruG4PSGf43BPi...,2021-01-27T02:45:53.40723Z
15,UCpCNaKju3d8YNq4trfwcJrA,Oracle Korea,오라클은 포괄적이고 총체적으로 통합된 클라우드 애플리케이션과 플랫폼 서비스 스택을 ...,4080,2027097,829,https://yt3.ggpht.com/ytc/AIdro_nNKOlLiApor92J...,2015-01-14T06:55:30Z
16,UCn41TnmQX9Ccswo89wDBiyg,롯데이노베이트,고객의 비즈니스 전환을 선도하는 기업\nBusiness Transformation ...,1170,196605,139,https://yt3.ggpht.com/AVDLd_Vevglh5CJn5RvWF7eQ...,2014-03-14T06:04:29Z
17,UCQNv-1JeNQ9I_xKlLD6QmhA,kt cloud,"대한민국 1등 클라우드, kt cloud의 다양한 서비스 및 기능을 만나보실 수 있...",12300,456521,293,https://yt3.ggpht.com/sG7YOG7DozqJ8EOHsiu7UXZB...,2016-05-02T14:11:28Z
18,UCz-j1tzeMCqvOX0YNkOXIAw,[CJ OliveNetworks] CJ올리브네트웍스,[CJ올리브네트웍스 공식계정]\n디지털 기술과 데이터를 기반으로 공간과 일상의 변화...,1340,242758,103,https://yt3.ggpht.com/LhtEqdwyRd07Dx0IBhMq4yY6...,2019-07-03T23:29:08Z
19,UC6fYG3jaeK2ucyX6YYTWglg,KG이니시스,"1998년 설립된 KG이니시스는 국내 최대 전자지급결제대행업체로, 인터넷쇼핑몰의 결...",106,69704,6,https://yt3.ggpht.com/ytc/AIdro_kfIgc9vuoc0FXf...,2018-07-03T05:44:54Z
20,UCmWvEmIve2QHxqgWXAblahA,KT DS,Cloud와 AI 전문 SW 기업 (주)케이티디에스 입니다.,1480,389465,190,https://yt3.ggpht.com/olq2Fy4DoLFb5H-q3z0lqLaz...,2023-01-19T02:33:34.10329Z
21,UCDT2efYTZ8y516QjrfsDQSA,SHINSEGAE I&C,리테일 산업에 IT기술을 더하면? 신세계아이앤씨의 쉽고 재미있는 리테일테크 스토리를...,943,948764,69,https://yt3.ggpht.com/4z9k0juEyoYK2y6mEGBdUXIS...,2019-12-03T04:33:05.124289Z
22,UCXyGqs4y58arFQ6uBduhnsQ,DB Inc.솔루션사업그룹,,3,164,3,https://yt3.ggpht.com/ytc/AIdro_n6uXwQUZQrJSqg...,2024-05-15T23:09:31.716094Z
23,UCQ2qPELH8lcS-jRi4o-GR5Q,번호안내 114,"대한민국 전화번호를 책임지는! 언제 어디서나, 02-114입니다. 24시간 365일...",85,9771,15,https://yt3.ggpht.com/ytc/AIdro_kvohxUiVMaOwCe...,2018-10-19T01:46:03Z
24,UCgtGQjfrfO_uAnH6JcB1MTA,ETEVERS GROUP 에티버스그룹,에티버스그룹의 공식 유튜브 채널입니다!\nChallenge for Transform...,1280,487860,272,https://yt3.ggpht.com/h2DsgPMiz6WnuvglKVbnjmC0...,2020-05-08T01:34:56.568369Z
25,UCK08M2075Y5TOIc8l0aNIQA,LINE KOREA,,13600,15185933,90,https://yt3.ggpht.com/ytc/AIdro_mH3OZn6rdemCEQ...,2014-02-07T05:25:38Z
26,UCtY-kbAYmWfVOqunQv2Wp3w,나이스페이먼츠,,5,525,1,https://yt3.ggpht.com/ytc/AIdro_l3Bz6doyOqmxnb...,2021-11-10T03:14:52.996109Z
27,UCNucE-FsBf3RITeGbsE3RKw,kt is,Total Marketing Service & Biz Support 기업,67,9773,14,https://yt3.ggpht.com/ytc/AIdro_lptnEMC_bj6-pd...,2021-03-22T07:06:20.131511Z
28,UCsdkfl1-goECoNJUp4aMJ7Q,세무신고는 이지샵,,3990,3328329,243,https://yt3.ggpht.com/ytc/AIdro_lFvIK3fB62-3O7...,2014-11-04T02:04:29Z
29,UCB3YZT-IHFywklzOtnB6GGg,나이스정보통신,"NICE정보통신 공식 YOUTUBE 계정입니다.\nVAN, PG, TAXREFUND...",146,25212,29,https://yt3.ggpht.com/oEENg4-gZgPUiNQmHNY7WKyM...,2019-04-29T04:28:50Z
30,UCh2nkYoiq6hae8ePxaZUgkw,빗썸 Bithumb Official,"당신의 안전한 금융 파트너, 빗썸의 공식 유튜브 채널입니다. \n",71000,34598986,1259,https://yt3.ggpht.com/-wqva-xDJjTdszWMnLKUdPqY...,2017-09-21T12:32:15Z
31,UCuDsOOa9CtAWwv7_rmuL14g,카카오모빌리티,We move life\n우리의 기술로 생활을 움직입니다.\n\n편리한 이동이 가치...,6730,31945442,241,https://yt3.ggpht.com/ZxVtDIbWGLs3vX7B_w-Nfk8C...,2017-10-20T01:13:47Z
32,UCoGxUVOIOxtg2V7HALB5o2A,만나플러스,시간에 가치를 더하는\n만나플러스\n,262,35033,38,https://yt3.ggpht.com/cT6uymMm8tCQcW1gp_XhsCM_...,2022-06-14T04:41:15.428269Z
33,UCm0COQdmdRLN23D4gUK3FAA,코스콤,코스콤 유튜브에 방문해 주셔서 감사합니다.\n코스콤은 코스콤 5.0시대를 맞아 금융...,1740,146713,164,https://yt3.ggpht.com/M2bC3vMUhqveSTADBUfjmb1j...,2019-05-09T08:24:34Z
34,UCsc2G8g0k-H15yYuQQv7AYQ,더존TV,"✨Get Fun, Gain Insight '더존TV'\n모두를 위한 단 하나의 인사...",52100,1945792,165,https://yt3.ggpht.com/5wbT-EEpiUlmmwLlBnITpgv7...,2025-12-24T04:53:18.756064Z
35,UCdc_SRhKUlH3grljQXA0skw,Google Korea,,95100,580899949,631,https://yt3.ggpht.com/wBZS4tfRv4QEQWWmQ2VA9ylW...,2007-08-13T01:46:32Z
36,UCsY3aR2FYK4SbM2tBLksWtQ,다우오피스,"올인원 업무플랫폼, '다우오피스' 공식 유튜브 채널입니다. 😀\n직장인들을 위한 콘...",2370,2636489,600,https://yt3.ggpht.com/MGmllFKya8zvALiBb6qcHCRb...,2014-01-14T06:47:47Z
37,UCSvOg4rSu395lPz6uMqBekw,kt M모바일,190만 고객의 선택! 압도적 1등 알뜰폰 kt M모바일의 공식 유튜브입니다. \n...,12900,50334438,332,https://yt3.ggpht.com/-t9DNlJUQAHs3tlrQg6pW7QD...,2014-11-26T08:59:10Z
38,UCjpcrwZnzmLdSrxVcdZd0cQ,아이티센,세상 모든 서비스에 디지털 가치를 부여하는 IT 선도 기업,1320,274417,150,https://yt3.ggpht.com/9KQ_UqP1Z9nCnk4Yv1XURCfX...,2021-07-21T01:43:33.371158Z
39,UCrdvKtWTpBfOx9kFCQ6aK3A,BizTechi_ERP,Global No.1 Solution SAP를 활용한 기업경영환경의 혁신과 성장을 ...,42,5233,15,https://yt3.ggpht.com/Q_KEZHJjW6Y2F5Yg4Qv6dlHF...,2018-10-29T01:35:44Z
40,UCRGEUnlW_qBi3ZDohvP-ylQ,농협정보시스템,농협정보시스템 공식 유튜브 채널입니다,37,1910,2,https://yt3.ggpht.com/ytc/AIdro_mr-WyPcf2Y4UVf...,2016-09-23T05:45:13Z
41,UCsfezAG3HiKjf7OrYTdNZxg,신한DS_오픈스튜디오,,668,41419,71,https://yt3.ggpht.com/c0zs0JsGxLj0y_XlWCkobGuy...,2020-08-13T06:07:21.048803Z
42,UC8RTcqBjB7I9lD_4l8cmwHg,이테크 클라우드,,79,1110,10,https://yt3.ggpht.com/1lxJgEyL_RkJ_kOL17xq3bJt...,2021-03-22T06:57:28.485546Z
43,UC_7nyGIBuYk6HBBBftbn3kg,NOL,NOL(야놀자) 플랫폼 공식 웹사이트 \n☞ https://nol.yanolja.c...,36600,104518861,152,https://yt3.ggpht.com/LowY7r6RgPTITwWMqM4jzhWN...,2013-05-30T05:27:55Z
44,UCWaLVmBvB2ytgSXvtDBKQiw,미디어로그영화,MediaLog = Media + Dialogue\n영화로 소통하는 미디어로그입니다.,43700,47542288,1108,https://yt3.ggpht.com/ytc/AIdro_l98kiVolj84NPV...,2013-05-13T00:20:01Z
45,UCZHb3OEEJ0WkizEH9ErlgvA,Dell Technologies,Welcome to Dell Technologies' official YouTube...,47300,242314751,1200,https://yt3.ggpht.com/FNcLs-Wgkhb7ThCfRl7kg060...,2016-08-05T09:55:02Z
46,UCMaDyFlagYlsolLLfWHu7Dw,숲 (SOOP),"자유로운 소통, 무한한 연결. SOOP(숲) 공식 채널입니다.\n\nSOOP은 '누...",124000,70772273,5024,https://yt3.ggpht.com/TNh2TiRdXlv6mZPFVWEApllp...,2013-12-05T08:06:12Z
47,UCNUz9CIAlWDtaLWvFWzgsww,티머니,더 편한 이동과 결제를 위한 플랫폼 기업\n티머니(Tmoney) 공식 채널입니다.\n,4430,101044009,209,https://yt3.ggpht.com/4kA3G7zuYn2WkvAYxRnKHh1V...,2013-04-15T05:29:13Z
48,UCsfezAG3HiKjf7OrYTdNZxg,신한DS_오픈스튜디오,,668,41419,71,https://yt3.ggpht.com/c0zs0JsGxLj0y_XlWCkobGuy...,2020-08-13T06:07:21.048803Z

In [7]:
# =============================================================
# 식품 기업의 유튜브 채널 정보 수집 시작
# =============================================================
food_handle_list = food_channel_list2['channel_handle'].to_list() # 정제된 IT 채널 리스트를 가져옴

print('='*50)
print('현재 남은 유닛 수 :', total_unit)
print('사용 예정 유튜브 API 유닛 :', len(food_handle_list), 'units')

food_list = [] # it 채널의 정보를 담을 리스트 생성
unit= 0 # 유닛 수 계산 시작!
for handle in food_handle_list:
    get_channel_info(youtube_api_key, handle=handle, list_name=food_list)
    unit += 1
total_unit = total_unit - unit
print()
print('실제 사용된 유튜브 API 유닛: ', unit, 'units')
print('남은 유닛 수: ', total_unit)
print('='*50)

# IT 채널 정보 리스트 데이터프레임으로 변환
food_channel = pd.DataFrame(food_list)
print()
print('수집 결과:')
display(food_channel)
# csv로 저장
food_channel.to_csv('./data/FOOD채널정보조회.csv', encoding='utf-8-sig')

==================================================
현재 남은 유닛 수 : 9751
사용 예정 유튜브 API 유닛 : 70 units

실제 사용된 유튜브 API 유닛:  70 units
남은 유닛 수:  9681
==================================================

수집 결과:

,channel_id,title,description,subscriber_count,view_count,video_count,thumbnails,created_date
0,UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],"편의점의 새로운 정의!\n트렌드의 중심, 재미의 기준을 만들지😎✌️""\n매일 새로운...",927000,305247518,1173,https://yt3.ggpht.com/ytc/AIdro_mI4fk2-pjTlfnJ...,2012-06-05T11:33:04Z
1,UCnL1m_iPeN8vX7zFHoB4SYg,테헤란로405,테헤란로405에서 좋은 친구 BGF의 주요 소식을 살펴보세요!\n-\n편의점 CU를...,2120,986927,501,https://yt3.ggpht.com/XgW8KshcFJNgLiN92DYhQ3KQ...,2017-03-03T10:34:35Z
2,UCl0HemfAt7dShJRf59_cuGQ,GS25 l 이리오너라,GS25 공식 유튜브 채널📻\n,1060000,222994020,2580,https://yt3.ggpht.com/AajkhhUfGCTlIBM8YvvfZmWK...,2012-12-26T06:54:54Z
3,UChD4kH8BcI49njXGL5-makg,GS리테일 뉴스룸,GS리테일 뉴스룸 공식 유튜브 채널입니다.\n최신 뉴스와 다양한 소식들을 영상으로 ...,2950,1043786,167,https://yt3.ggpht.com/dRpIX9kTKHJJXBJwtWoyXtBB...,2015-05-18T08:16:28Z
4,UCG_gfzGVpsxGwYuFgH8-tNA,대상 DAESANG,더 많은 것들을 존중의 대상으로 DAESANG\n#Respect for more #...,18500,330712382,254,https://yt3.ggpht.com/UGJpLrZkEdbCDTFulkdMEeaH...,2015-12-10T08:58:42Z
5,UCfv1dkNKCFUtZouvp3DhS3g,대상그룹 DAESANG 디튜브,대상그룹(DAESANG GROUP) 공식 소통 채널\n‘대상주식회사’의 식품 이야기...,10800,5755529,277,https://yt3.ggpht.com/JNGLkJj-SitafANGlfbseU-j...,2020-09-04T01:25:26.250343Z
6,UCDryA2PIGnbs9NYn_63rISw,CJ제일제당,CJ제일제당 공식 유튜브 채널입니다. \n,491000,34922991,204,https://yt3.ggpht.com/ULAliXxe7B5_ysZS8vIsPs18...,2011-01-26T00:52:39Z
7,UCOV_BpGzvmH7ZtjQOWg0bSQ,제당슈만,⭐제당슈만⭐ CJ제일제당이 당신을 🔥슈퍼스타🔥로 만들어 드립니다!\nCJ제일제당의 ...,20900,6641901,216,https://yt3.ggpht.com/Yk3vnP2gHzidyACXSqtTo1LU...,2020-05-15T11:50:40.345514Z
8,UCGmLtNZFTL6PiKsz3Vpdgbw,비비고 (bibigo),bibigo Official YouTube Channel\n\n,88100,275870330,307,https://yt3.ggpht.com/nQgCSi2mTp99T8VaSEH5MVyZ...,2013-04-02T11:37:09Z
9,UCFXwXfbr4b1HHl-YKCOaydA,맛깔스튜디오 by롯데웰푸드,맛있는 거 말고 재밌는 거도 기깔나게 잘합니다.\n롯데웰푸드의 맛깔나는 컨텐츠 제작...,147000,490800635,1311,https://yt3.ggpht.com/LJScwH9HDweKeTnwo8UAMcVd...,2011-11-23T07:54:50Z
10,UCpvT-53Ki7d9Z0PWKC6fGOA,롯데웰푸드 모락모락,모락모락 온기가 느껴지는 \n갓 지은 롯데웰푸드 콘텐츠 한끼🍴 \n,138000,137205606,625,https://yt3.ggpht.com/Emiy4Wt0qQd8VDKpwF_HeQz1...,2013-03-14T00:43:52Z
11,UCaxvyTYdWaDXupmgj5ttDUQ,Starbucks Korea,"""커피 이상의 특별한 경험을 소개합니다""\n스타벅스는 커피를 넘어, 사람과 사람을 ...",178000,58477777,807,https://yt3.ggpht.com/ytc/AIdro_morPijMJBwDTgc...,2007-06-19T23:26:27Z
12,UCbEEgpyRxXd6rbM_xhApb_Q,727스튜디오,Original Contents by STARBUCKS KOREA\n\nⓒ 727S...,126000,15193131,240,https://yt3.ggpht.com/4JG-2UP2kJp_pgaL6Tdxj1_q...,2025-01-14T05:06:10.93402Z
13,UCzGara7SUTKXruclCD4eA5g,농심 nongshim,맛있는 상상이 가득한 농심 공식 유튜브 채널 입니다.,44100,1309586458,1459,https://yt3.ggpht.com/2vDg5LPC9z_lExgRYWCFs6XQ...,2009-06-25T06:18:44Z
14,UCzKFT7cBIKO9Dapikf6e3ow,롯데칠성 LOTTE CHILSUNG,롯데칠성 유튜브 공식 채널입니다. \n다양한 영상 컨텐츠를 소개해 드립니다.\n앞으...,126000,678985201,541,https://yt3.ggpht.com/WopSa_1tJT2lQthlRuak2pwT...,2013-03-12T03:31:37Z
15,UC-WFvgdXXmZPj4pDI8GFbzQ,칠성레이블,칠성사이다가 선사하는 콘텐츠 시리즈!\n\n칠성사이다가 기획한 칠성레이블은\n평범한...,103000,70477245,266,https://yt3.ggpht.com/EBrCDOTLtaagP0mjTvgPgbn6...,2021-12-23T09:19:44.012307Z
16,UCHvCHuXTg6yfQQ1QCeDQMLg,오뚜기 Daily,오뚜기 공식 유튜브 채널(Otoki Official Youtube Channel),76200,227338519,826,https://yt3.ggpht.com/Hz_EJNq4FBpNf_hpOfKVi2yQ...,2012-09-14T01:34:19Z
17,UCGEaz9UlmXmQ2YCEDIAc1iA,ottoginoodle,맛으로 행복한 세상! 오뚜기 라면 이야기에 오신것을 환영합니다.\n\n뚜기네의 재밌...,11600,62502192,250,https://yt3.ggpht.com/ytc/AIdro_kPxov_YKhpPf92...,2011-12-07T01:42:35Z
18,UCSQ0lVqv57JVw1lOdJ2vTVA,이마트24 | ALLDAY HIGHLIGHT,"모든 순간이 하이라이트\nALLDAY HIGHLIGHT, 이마트24\n",143000,75815729,651,https://yt3.ggpht.com/PEHYGu8okwfvvk2-pTRhPmHl...,2020-09-24T00:06:25.081438Z
19,UCmvqXRPTfMgkKF3MFWylMqQ,HITEJINRO,당신의 인생을 더 큰 즐거움과 에너지로 채우는 하이트진로 공식 유튜브입니다.,125000,1282984323,880,https://yt3.ggpht.com/ubxjIFIFMFCCxi1H3Nj-7gTS...,2009-10-29T06:36:25Z
20,UClgbMkn177O0xNOEcR9rtug,하이트진로음료,,2900,48478607,219,https://yt3.ggpht.com/rMCqFHSwiET2uJo-03eJxu3p...,2013-06-20T06:53:57Z
21,UCX0cSM0jY9PmtGZixR75u1g,더반찬,No1. 온라인 푸드마켓 더반찬 \nwww.thebanchan.co.kr,397,618622,51,https://yt3.ggpht.com/ytc/AIdro_lHUOA1q_DPQguZ...,2016-10-18T01:54:59Z
22,UCPz4i66EweVQPddqYq7uULg,서울우유 seoulmilk,서울우유 협동조합의 공식 유튜브입니다.\n\n,15300,98573915,283,https://yt3.ggpht.com/UVN0WEXK3va2ZpEADDFelk8Y...,2010-11-24T02:39:38Z
23,UCs_L1_g_MeTHhuRhJEkF_xA,동원F&B(Dongwon),동원F&B 공식 채널입니다. (Dongwon F&B official )\n,37800,624856879,514,https://yt3.ggpht.com/FH56yK3ukI5SjQysrh9uurmC...,2011-07-11T04:11:05Z
24,UCULxh7_uMrbCn0IR_H1h3fg,동원몰 (dongwonmall),💙동원몰 공식 유튜브 채널💛\n다양한 동원몰 소식은 \n⬇️아래 링크에서 확인⬇️,70,133185,32,https://yt3.ggpht.com/ytc/AIdro_mptxWV4S7R-4st...,2012-01-27T00:43:19Z
25,UCC3eqZIo6lqZQQAN9MO0LQA,동원TV,동원그룹의 최신 소식과 유익한 볼거리가 가득한 곳! 여기는 동원그룹 공식 유튜브 채...,24100,317032572,1045,https://yt3.ggpht.com/JWWnneUCTFTzf5cMguzUzN8b...,2013-04-03T12:52:46Z
26,UCxHML2F6f8c5L7N2-0gF6Vw,삼양그룹,💡생활의 잠재력을 깨우고\n🌐인류의 미래를 바꾸는 \n💙삼양그룹 공식 인스타그램\n...,6900,269339391,354,https://yt3.ggpht.com/TQNeALOjJ4jGXfNJO1SOx6Kf...,2013-04-16T04:48:36Z
27,UClEdrjHVDXEOsll343sECmQ,큐원 알룰로스,"더 나은 달콤함의 시작\nBetter Sweet, One Choice, 큐원 알룰로스\n",17400,4618146,101,https://yt3.ggpht.com/1xOjNkRZWGiJInBBKVlCLEVL...,2015-07-28T05:45:03Z
28,UCMqZKRBemgZ0_1uLT2yAF9w,상쾌환 EASY TOMORROW,,1430,105773077,137,https://yt3.ggpht.com/OBZBKMisqoAWKG0KR_ODg7_R...,2019-01-14T11:34:22Z
29,UCGgQBs1IgNkwMYbnu26S1yg,파리바게뜨TV,놀고 먹는것에 진심인 사람들의 집합체 🍞🥖🥪🍬\n맛있는 즐거움으로 꽉 찬\n파리바게...,24700,151278167,575,https://yt3.ggpht.com/ytc/AIdro_nHRY5WmHpDGQjZ...,2014-06-16T08:46:37Z
30,UClYaslphHkJ3faHzJrU6ZSw,오비맥주,안녕하세요!\n여기는 오비맥주 공식 YouTube 채널입니다.,1500,1520682,35,https://yt3.ggpht.com/ytc/AIdro_nbT41LfpXIHJ-j...,2019-03-22T01:23:30Z
31,UCUQhyOLi8uFTmiFRmndjQxw,카스 CASS,"신선하고 톡 쏘는 맥주, 젊음의 활력과 에너지를 느낄 수 있는 대한민국 젊음의 대표...",83100,238132327,497,https://yt3.ggpht.com/Fufyjor6JyuU3onwTV9QAQkF...,2014-04-21T07:53:11Z
32,UCFRMEa0vlRfrgcQpnryE-TA,한맥 HANMAC,\n100% 국내산 고품질 쌀로 완성한\n상쾌한 풍미의 코리안 테이스트\n\n한국인...,932,63087644,94,https://yt3.ggpht.com/NoNVNCOHFoS2ViM-c9ZOK5ke...,2020-08-13T02:24:17.881209Z
33,UCowoImtEdqWGyBIRqt6L2dw,Stella Artois Korea,스텔라 아르투아 공식 유튜브 채널입니다. 음주는 책임있게. \n\t\n* 본 페이지...,5180,54930995,176,https://yt3.ggpht.com/1EBgazONM_RXFamXWm9li8Lp...,2015-06-08T07:48:24Z
34,UC-9HdRV-OzriZ1Q09bT304w,BUDWEISER KOREA,버드와이저 공식 유튜브 채널입니다. 음주는 책임있게.\n\n* 본 페이지의 콘텐츠는...,20800,58812456,431,https://yt3.ggpht.com/CDJxXuduCEMnjjIImQwE7KT2...,2017-06-03T10:08:46Z
35,UCOx-g_rEMW3oD8g-bQaLWkQ,Hoegaardenkr,도심 속에서 호가든을 느끼다.\n호가든에 오신 걸 환영합니다 🌿\n\n𝗪𝗲𝗹𝗰𝗼𝗺𝗲...,793,11092003,137,https://yt3.ggpht.com/xO6pBYAofv02TIlnLbWa4Rsv...,2018-09-11T09:56:45Z
36,UCYPk6gQRP0W2ApSem8qsW2g,구스아일랜드,구스아일랜드 공식 유튜브 채널입니다. 음주는 책임있게.\n\n본 페이지의 콘텐츠는 ...,170,3526195,93,https://yt3.ggpht.com/ytc/AIdro_mj0dE9rfy5Sdqs...,2018-09-10T08:48:03Z
37,UCbyV_HczPmqn2LthdcBIl2Q,커피라는 행복 맥심,,35400,913320980,868,https://yt3.ggpht.com/OV9SIS-26rHeYBLxdR2WywK2...,2013-10-03T12:56:18Z
38,UCIAFN5e9KzBu_F3dBDbmmVg,"세상에서 가장 작은 카페, 카누",,3250,347268601,327,https://yt3.ggpht.com/KU-a2Ss17Q113DZAJ-J5YCvG...,2022-12-26T02:15:16.71179Z
39,UCtFDX5H24C2igmDOdAJdS9Q,동서식품 유튜브,,18000,57672769,114,https://yt3.ggpht.com/wmjtHXOFc69OLqGslyT2i5io...,2014-05-21T01:45:41Z
40,UCt0Pnki9ZDDYx6auEtClYLQ,매일유업 | Maeil,매일유업의 공식 Youtube 입니다.,72900,318397942,1024,https://yt3.ggpht.com/XBGVTwpqwFjYd_y3hrEarY3N...,2010-09-03T05:51:06Z
41,UCzGbclHB9ZcrbcV4qg11C1A,셀렉스,"대한민국 1등 단백질, 셀렉스 공식 유튜브 채널입니다.\n",118000,69333755,171,https://yt3.ggpht.com/vBgT4prOdblpX9cSvjB8SyhD...,2022-03-18T07:03:41.518059Z
42,UC88W-nkd_7G9S7u-2xlX4DQ,삼립,보기만 해도 빵🥖빵🍞 터지는 삼립 공식 유튜브,4330,53102006,204,https://yt3.ggpht.com/LK3-fEwOU_YzesUxIH-ZsxFK...,2017-03-28T07:16:12Z
43,UCiyg3rAdPOJN4eKAgAs5FOQ,SPC그룹,"일상을 맛있게 행복하게, Happiness in every bite\n",5580,7639925,413,https://yt3.ggpht.com/xx8ZYgZxHElh9Sd3Gh-2nNPL...,2016-12-23T06:27:54Z
44,UCzCxSb_RYZuaiaP3u9QNR_A,Coca-Cola Korea,Real-Magic 코카-콜라의 공식 YouTube 채널입니다!,116000,763721794,727,https://yt3.ggpht.com/3gq979lNuPnYbsQJA7ZimgNN...,2011-02-15T09:06:14Z
45,UCC-RQrzmKSAV70txxsdXWqQ,팜스코TV,"(주)팜스코\nBeyond No.1, Everyday with Farmsco\nww...",3520,359038,302,https://yt3.ggpht.com/bnS0qpIZrhDa9CJzfAA-5BCW...,2019-06-12T05:43:11Z
46,UC4xGgCpoPfLHcuPeUbnMibA,사조대림,먹잘알들의 PICK👀\n믿고 먹는 사조대림!\n,1270,47141402,258,https://yt3.ggpht.com/ffn5eGjHgQP90uYCLCG7wZU3...,2022-01-26T05:52:42.197434Z
47,UCEKRI0fipK4LEgV98nI2CQA,버거킹,,51100,410634145,363,https://yt3.ggpht.com/kTGFMGRb__0Rodj-WPawVCFg...,2013-08-13T09:41:34Z
48,UCDjdk0ufvcvV08hAm_vF06Q,투썸플레이스,,82900,137440409,291,https://yt3.ggpht.com/GbVbtd__BYN_kIyMCywMiwYI...,2017-11-30T07:09:02Z
49,UCYnYhuh-L3ApSQ5A-zM3QkQ,빕스VIPS,,889,19818056,81,https://yt3.ggpht.com/MNQZn5AuHOKsis9HAO4T7hbF...,2013-12-30T00:31:01Z
50,UC9Hu-7OguU6HyWaxP_GBYcA,Samyangfoods삼양식품,SQUARE🟧 THE CIRCLE🟠\n불가능의 룰을 깨다\n,17700,282026503,255,https://yt3.ggpht.com/ytc/AIdro_l4o6EV2Hs-eL5p...,2011-05-24T06:31:26Z
51,UCWuIxsTBinJzNf4sQKy7FxA,킴스클럽 공식,,160,270229,60,https://yt3.ggpht.com/CLeokySMmN7wy_IkzkxcnW6T...,2015-11-01T11:22:37Z
52,UCtAHe2OINYIyGOTLDSCzFFg,아웃백 스테이크하우스,"우리들의 PLAYGROUND, 아웃백 그라운드🎈\n",84700,141933697,255,https://yt3.ggpht.com/ytc/AIdro_mdq6uNipbCy7a6...,2011-06-29T05:46:21Z
53,UCqXNBZbGHHS-0nwWvEWXf0A,코레일유통TV,🚄철도 모빌리티 서비스 기업 코레일유통❤️\n,1010,201127,100,https://yt3.ggpht.com/ytc/AIdro_msfYs7VrHQzkW3...,2020-04-02T07:01:42.156416Z
54,UCmSdD90HfUqyR3VNLys03EQ,이랜드이츠,,6,70532,9,https://yt3.ggpht.com/ytc/AIdro_l1Ei_UOn3gRmgf...,2025-01-01T07:51:01.79617Z
55,UCc76iFK6R2u2sqAunMZc8jw,더카페,🔽더카페 성공창업 문의🔽\nhttps://thecaffeopen.com\n\n대기업...,411,1412227,40,https://yt3.ggpht.com/7oCKQYLiGqQS3thAK_1kY1UE...,2022-05-23T07:54:35.677133Z
56,UCvRDrKfRaqYRSBjtj80Q1iQ,KFC Korea,,5110,30089883,174,https://yt3.ggpht.com/Jpt4-yILYIHYiNLqSOYTL2Qz...,2015-10-02T05:43:05Z
57,UCabcfEPMYK0rvbGIl3Gr3Ag,엠즈씨드주식회사,커피전문점 Paul Bassett 공식 YouTube 채널에 오신 것을 환영합니다.,31200,805253,33,https://yt3.ggpht.com/ytc/AIdro_k_6I392knvUBZm...,2015-04-05T14:44:45Z
58,UCbquzcEXtjLAKKlGQ4hLC-w,다담몰,,311,429689,10,https://yt3.ggpht.com/XBovUJb6yUdq4BDKYNTzVbgc...,2021-07-15T02:56:46.101064Z
59,UCrDYPLah4QRsqEZVvWQ6t7g,도미노피자,도미노피자 공식 유튜브 채널입니다.,20200,171091643,287,https://yt3.ggpht.com/_oV6lN8faYGHsjkU5uQVJCzt...,2010-11-29T00:22:40Z
60,UC9_GC5aoZJMz5MAH9e8x9Yg,ENTAS,대한민국 대표 외식문화기업 엔타스\n\n엔타스 그룹은 1991년 창업 이래 꾸준하고...,22,3878,13,https://yt3.ggpht.com/Dtm7uKrRhlF_D8Yc_R18zLQz...,2025-02-13T15:41:10.261329Z
61,UCnMNvrjrdtl_b_5rgvCn21Q,🍦Buza Company🍦,From 🇰🇷 to 🇦🇪🇸🇦🇧🇭🇰🇼🇴🇲 and 🌏\nIntroducing the h...,182,82861,82,https://yt3.ggpht.com/lAJRm9JMzvFiuIzSFUnBN2v7...,2021-08-15T12:39:56.026374Z
62,UCr0W7lsBivPQN5mB2_IntCg,그레인온,,114,4739577,33,https://yt3.ggpht.com/qxt1glZKqzVAyk42Pf-d-VKA...,2023-08-28T06:28:51.294443Z
63,UCuJkoRqYKKCwagZhmz6my-g,gongcha_korea,공들여 더하는 행복 공차.\nhttps://www.gong-cha.co.kr/bra...,14500,30557122,177,https://yt3.ggpht.com/TN6SSFmDwkGEV7UUKaICIR_u...,2016-09-22T04:16:24Z
64,UCy85dXvlDH-9H9puNRRGuxA,유사나헬스사이언스코리아,"유사나는 최고의 과학을 기반으로 개발 하고, 이를 바탕으로 직접 판매를 통해 우수한...",11800,1532669,592,https://yt3.ggpht.com/JnDmz84yPDvCNbWbKubIBjN3...,2013-09-26T16:29:24Z
65,UCvGz1yRdYIyq1wsVrdubFdg,63 스카이라인 다이닝,63 스카이라인 다이닝 공식 채널입니다.\n\n서울의 랜드 마크인 63빌딩에서\n즐...,421,139049,58,https://yt3.ggpht.com/-tf3IeHvN9EpqMASNf_uCdsH...,2020-10-19T02:36:24.92673Z
66,UCIAd6tBRFaU5dVJZflutneQ,CUCHARA_official,"STAY SAFE, STAY HEALTHY\n쿠차라는 신선한 재료로 매일 조리하는 ...",5,1288,4,https://yt3.ggpht.com/sTMC3EdFh7mTN0J7mm1w7LEF...,2021-07-26T06:19:41.020417Z
67,UCcf7JZQJuaxkgxaJvLP5ehw,Amoje food,,66,55087,58,https://yt3.ggpht.com/ytc/AIdro_kwMxDL9vQxTlM2...,2013-06-14T02:46:07Z
68,UCFqPOabewS-V-InoIsilfPg,매드포갈릭 Mad for Garlic,"모두의 다이닝, K-Cultured 이탈리안 레스토랑 '매드포갈릭'의 공식 유튜브 ...",285,1711428,5,https://yt3.ggpht.com/5OeI_1Wlq5As-4U2NOt8lx54...,2015-03-05T08:38:47Z
69,UCkY-OZQGn8e7loIO7Z9wHXQ,강강술래푸드,가정에서도 만나세요.\n강강술래에서 경험했던 맛을 가정에서도 그대로\n느끼실 수 있...,130,30373,67,https://yt3.ggpht.com/1Z0mMbXKodbr_EwaT99vsgjo...,2020-11-09T02:39:34.281239Z

---
#### 채널 선정기준
    - 채널 정보 데이터 EDA를 통해 선정 기준 정립

---

In [ ]:
# =======================================================================
# 1차 채널 선정 기준 정하기
# =======================================================================
# 
# channel_list(arg1, arg2)
# 
# arg1: 데이터프레임이름
# arg2: 저장할 경로 (예: './data/test.csv')
# 
# 1. 구독자 1만 명 미만 채널 제거 : 마이크로 인플루언서 최소 기준
# 2. 채널 나이 3년 미만 채널 제거 : 계절성을 반영하기 위한 기준
#
# =======================================================================

def channel_list(ch_data, save_path=None):
    
    # 숫자형 컬럼 정수로 변환
    ch_data['subscriber_count'] = ch_data['subscriber_count'].astype(int)
    ch_data['video_count'] = ch_data['video_count'].astype(int)
    ch_data['view_count'] = ch_data['view_count'].astype(int)
    
    # 1. 구독자 1만 명 미만 채널 제거
    ch_data = ch_data[ch_data['subscriber_count']>= 10000] 
    
    # 2. 채널 나이 3년 미만 채널 제거
    ch_data['year'] = pd.to_datetime(ch_data['created_date'], errors='coerce', format='mixed', utc=True).dt.year
    ch_data['channel_age'] = 2026 - ch_data['year']
    ch_data = ch_data[ch_data['channel_age'] >= 3]
    
    # # 3. 연 평균 4회 미만 영상 업로드 채널 제거 -> IT는 이 조건 있으나 없으나 동일. F&B는 이 조건 추가시 폴바셋 채널 삭제 https://www.youtube.com/channel/UCabcfEPMYK0rvbGIl3Gr3Ag
    # videos_thr = ch_data['channel_age'] * 4
    # ch_data = ch_data[ch_data['video_count'] >= videos_thr]
    
    # CSV 파일로 저장
    ch_data.to_csv(save_path, index=False, encoding='utf-8-sig')
    return ch_data

In [ ]:
# =======================================================================
# 1차 채널 선정 : IT 채널 리스트 : it_filtered_channel_list
# =======================================================================
it_filtered_channel_list = channel_list(it_channel, './data/IT_Filtered_Channel_list.csv')
len(it_filtered_channel_list)

In [ ]:
# =======================================================================
# 1차 채널 선정 : FOOD 채널 리스트 : food_filtered_channel_list
# =======================================================================
food_filtered_channel_list = channel_list(food_channel, './data/FOOD_Filtered_Channel_list.csv')
len(food_filtered_channel_list)

---
#### 채널 영상정보 검색
    - 채널이 가지고 있는 영상의 Video_id를 수집
    - 이후에 진행할 영상 상세정보 불러오기에 사용
---

In [ ]:
# =======================================================================
# 채널의 uploads playlist를 이용해 영상 정보를 수집 : get_playlist_video_info(arg1, arg2, arg3, arg4)
#
# arg1: 유튜브 API 키 (필수)
# arg2: 유튜브 채널 ID (필수)
# arg3: 가져올 최대 영상 개수 (기본값: 50)
# arg4: 저장할 csv 경로 (필수)
#
# 비용: 1회 당 2유닛
#   channels: 
#
# [수집할 정보]
# - channel_id: 채널의 고유 아이디 값
# - video_id: 영상의 고유 아이디 값
# - published_at: 
# - title
# - description
# =======================================================================

def get_playlist_video_info(api_key, channel_id=None, max_results=50, save_path=None):
    
    if save_path is None:
        raise ValueError("저장할 경로를 입력해주세요. 예: save_path='./data/youtube_data.csv'")

    if not channel_id:
        raise ValueError("channel_id를 입력해주세요")

    # 기존 CSV에 저장된 video_id 불러오기
    existing_video_ids = set()

    if os.path.exists(save_path):
        existing_df = pd.read_csv(save_path)
        if 'video_id' in existing_df.columns:
            existing_video_ids = set(existing_df['video_id'].dropna().astype(str))

    # 채널의 uploads playlist ID 가져오기
    url = 'https://www.googleapis.com/youtube/v3/channels'
    channel_params = {
        'part': 'contentDetails',
        'id': channel_id,
        'key': api_key
    }

    r = requests.get(url, params=channel_params, timeout=30)
    print(r.url)

    if not r.ok:
        print('status_code:', r.status_code)
        try:
            print('error_json:', r.json())
        except Exception:
            print('error_text:', r.text)
        return []

    channel_data = r.json()
    items = channel_data.get('items', [])

    if not items:
        print('채널 정보를 찾을 수 없습니다.')
        return []
    
    # 업로드된 플레이리스트 아이디 가져오기 
    uploads_playlist_id = (
        items[0]
        .get('contentDetails', {})
        .get('relatedPlaylists', {})
        .get('uploads')
    )

    if not uploads_playlist_id:
        print('uploads playlist ID를 찾을 수 없습니다.')
        return []
    
    # playlistItems로 영상 정보 수집
    playlist_url = 'https://www.googleapis.com/youtube/v3/playlistItems'
    all_items = []
    next_page_token = None

    while len(all_items) < max_results:
        remain = max_results - len(all_items)
        request_count = min(50, remain)

        playlist_params = {
            'part': 'snippet',
            'playlistId': uploads_playlist_id,
            'maxResults': request_count,
            'key': api_key
        }

        if next_page_token:
            playlist_params['pageToken'] = next_page_token

        r = requests.get(playlist_url, params=playlist_params, timeout=30)
        print(r.url)

        if not r.ok:
            print('status_code:', r.status_code)
            try:
                print('error_json:', r.json())
            except Exception:
                print('error_text:', r.text)
            break

        data = r.json()
        items = data.get('items', [])

        if not items:
            break

        for video in items:
            snippet = video.get('snippet', {})
            resource_id = snippet.get('resourceId', {})
            video_id = resource_id.get('videoId')

            if not video_id:
                continue

            video_id = str(video_id)

            # 중복이면 건너뛰기만 함 (중단 X)
            if video_id in existing_video_ids:
                continue

            all_items.append({
                'channel_id': snippet.get('channelId'),
                'video_id': video_id,
                'published_at': snippet.get('publishedAt'),
                'title': snippet.get('title'),
                'description': snippet.get('description')
            })

            # 중복 방지용 set에도 즉시 추가
            existing_video_ids.add(video_id)

            if len(all_items) >= max_results:
                break

        next_page_token = data.get('nextPageToken')
        if not next_page_token:
            break


    # 4. CSV 저장

    if all_items:
        new_df = pd.DataFrame(all_items)
    
        if not os.path.exists(save_path):
            new_df.to_csv(save_path, index=False, encoding='utf-8-sig')
        else:
            new_df.to_csv(save_path, mode='a', header=False, index=False, encoding='utf-8-sig')
    
    return all_items

In [ ]:
# =======================================================================
# 유닛비용 미리 계산
# =======================================================================

print('가지고 있는 유닛 수: ', total_unit)
total_video_count = np.sum(it_filtered_channel_list['video_count'])
total_spend_unit = int(np.ceil(total_video_count / 50))*2
print('총 영상 수 :', total_video_count)
print('예상 유닛 비용: ',total_spend_unit)

In [ ]:
# =======================================================================
# IT 기업 채널의 영상정보 수집 API
# =======================================================================

print('가지고 있는 유닛 수: ', total_unit)

for channel_id in it_filtered_channel_list['channel_id'].to_list()[2:]:
    
    video_count = it_filtered_channel_list.loc[
        it_filtered_channel_list['channel_id'] == channel_id,
        'video_count'
    ].iloc[0]
    
    get_playlist_video_info(
        youtube_api_key,
        channel_id=channel_id,
        max_results=video_count,
        save_path='./data/IT_video_ids.csv'
    )
    
    print(f"{channel_id} 채널의 영상 수 : {video_count}")
    
    spend_unit = int(np.ceil(video_count / 50))*2
    total_unit -= spend_unit
    
    print('현재 남은 유닛 수 :', total_unit)

In [ ]:
# =======================================================================
# 유닛 비용 계산
# =======================================================================

print('가지고 있는 유닛 수: ', total_unit)
total_video_count = np.sum(food_filtered_channel_list['video_count'])
total_spend_unit = int(np.ceil(total_video_count / 50))*2
print('총 영상 수 :', total_video_count)
print('예상 유닛 비용: ',total_spend_unit)

In [ ]:
# =======================================================================
# FOOD 기업 채널의 영상정보 수집 API
# =======================================================================

print('가지고 있는 유닛 수: ', total_unit)

for channel_id in food_filtered_channel_list['channel_id'].to_list():
    
    video_count = food_filtered_channel_list.loc[
        food_filtered_channel_list['channel_id'] == channel_id,
        'video_count'
    ].iloc[0]
    
    get_playlist_video_info(
        youtube_api_key,
        channel_id=channel_id,
        max_results=video_count,
        save_path='./data/FOOD_video_ids.csv'
    )
    
    print(f"{channel_id} 채널의 영상 수 : {video_count}")
    
    spend_unit = int(np.ceil(video_count / 50))*2
    total_unit -= spend_unit
    
    print('현재 남은 유닛 수 :', total_unit)

---
#### 영상 상세 정보 출력
    - 이제 본 분석에 사용될 영상의 상세 정보를 가져온다.

---

In [ ]:
# =======================================================================
# 영상 상세 정보 불러오기 : get_video_info(arg1, arg2, arg3)
# arg1: 영상 상세정보를 가져올 유튜브 API키 입니다. (필수)
# arg2: 영상 상세정보를 가져올 Video_id의 리스트입니다. (필수)
# arg3: 영상 상세정보를 저장할 경로입니다. (필수. 예: save_path = './data/test.csv')
#
# [불러올 정보]
# 1. 영상 아이디(video_id): 영상이 가지고 있는 고유 아이디 값입니다.
# 2. 영상 제목(title): 영상 제목
# 3. 채널 아이디(channel_id): 해당 영상을 업로드한 채널의 고유 아이디 값입니다.
# 4. 채널 이름(channel_title): 해당 영상을 업로드한 채널의 이름입니다.
# 5. 영상 설명(description): 업로더가 작성한 해당 영상의 설명입니다.
# 6. 영상 업로드 날짜(upload_date): 영상이 업로드된 날짜입니다.
# 7. 영상 키워드 태그 목록(tags): 영상의 키워드 태그 목록입니다.
# 8. 영상 카테고리 아이디(category_id): 영상이 속해있는 카테고리의 고유값 입니다.
# 9. 조회수(view_count): 해당 영상의 조회수입니다.
# 10. 좋아요 수(like_count): 해당 영상의 좋아요 수 입니다.
# 11. 댓글 수(like_count): 해당 영상의 댓글 수 입니다.
# 12. 영상 길이(duration): 해당 영상의 길이입니다. (형식: PT#H#M#S, T: 일, H: 시간, M: 분, S: 초)
# 13. 고화질 여부(definition): 영상을 고화질로 시청할 수 있는지 여부입니다. (hd(High Definition): 고화질 시청 가능, sd(Standard Definition): 일반화질 시청)
# 14. 동영상 라이선스(license): 동영상 라이선스 정보입니다. creativeCommon: 출처를 표시하면 영상의 재편집/재배포가 가능, youtube: 영상 재편집/재배포 불가능
# 15. 임베딩 가능 여부(emabeddable): 영상을 다른 웹사이트에 퍼갈 수 있는지 여부 (광고 영상을 전광판이나 특정 홈페이지에서 계속 송출한다면 조회수가 올라가지 않을까?)
# 16. 유료 PPL 여부(has_paid_product_placement): 유료 PPL 사용 여부 (True/False)
# =======================================================================

def get_video_info(api_key, video_ids=None, save_path=None):
    
    # 영상 정보 수집 API url 가져오기
    url = 'https://www.googleapis.com/youtube/v3/videos'
    all_results = []
    
    if not video_ids:
        print('video_ids가 없습니다.')
        return pd.DataFrame()
    
    if save_path == None:
        raise ValueError('파일을 저장할 경로를 입력해주세요.')
    
    # 기존 video_id 불러오기
    existing_video_ids = set()
    
    if save_path and os.path.exists(save_path):
        existing_df = pd.read_csv(save_path)
        if 'video_id' in existing_df.columns:
            existing_video_ids = set(existing_df['video_id'].dropna().astype(str)) # video_id 결측없이/문자형/set(중복 없음, 순서없음, 집합개념) 형태로 가져오기
    
    # 중복 제거 & 리스트로 변환
    video_ids = [str(v) for v in video_ids if v] # 만약 영상 아이디가 video_ids에 포함되고, 값이 존재한다면 문자열로 변환된 영상 아이디를 출력 반복
    video_ids = list(dict.fromkeys(video_ids))
    
    # 이미 저장된 video_id 제외
    if existing_video_ids:
        video_ids = [vid for vid in video_ids if vid not in existing_video_ids]
    
    # 불러올 video_id가 없을 때
    if not video_ids:
        print('새로 수집할 video_id가 없습니다.')
        return pd.DataFrame()
    
    for i in range(0, len(video_ids), 50):
        batch_ids = video_ids[i:i+50]
        
        params = {
            'part': 'snippet,statistics,contentDetails,status,paidProductPlacementDetails',
            'id': ','.join(batch_ids),
            'key': api_key
        }
    
        r = requests.get(url, params=params, timeout=30)
    
        if not r.ok:
            print('status_code :', r.status_code)
            try:
                print('error_json :', r.json())
            except Exception:
                print('error_text :', r.text)
            break
        
        data = r.json()
        items = data.get('items', [])
        
        for item in items:
            snippet = item.get('snippet', {})
            statistics = item.get('statistics',{})
            content_details = item.get('contentDetails', {})
            status = item.get('status', {})
            ppl = item.get('paidProductPlacementDetails', {})
            # file_details = item.get('fileDetails', {})
            # processing_details = item.get('processingDetails',{})
            # suggestions = item.get('suggestions', {})
            
            all_results.append({
                'video_id' : item.get('id'), # 영상 아이디
                'title' : snippet.get('title'), # 영상 제목
                'channel_id' : snippet.get('channelId'), # 채널 아이디
                'channel_title' : snippet.get('channelTitle'), # 채널 이름
                'description' : snippet.get('description'), # 영상 설명
                'upload_date' : snippet.get('publishedAt'), # 영상 업로드 날짜
                'tags' : ', '.join(snippet.get('tags', [])), # 영상 키워드 태그 목록
                'category_id' : snippet.get('categoryId'), # 영상의 카테고리 아이디
                'view_count' : statistics.get('viewCount'), # 영상의 조회수(Shorts 영상은 최소 시청조건 없음. 재생 또는 다시보기 시작되는 횟수 반환)
                'like_count' : statistics.get('likeCount'), # 영상에 좋아요를 표시한 사용자 수
                'comment_count' : statistics.get('commentCount'), # 영상의 댓글 개수
                'duration' : content_details.get('duration'), # 영상 길이 (PT#H#M#S 형식)
                'definition' : content_details.get('definition'), # 영상을 고화질로 시청할 수 있는지 여부 (hd, sd 형식)
                # 'content_rating' : content_details.get('contentRating'), # 다양한 평가 기준에 따라 동영상이 받은 평가
                # 'kmrb_rating' : content_details.get('contentRating', {}).get('kmrbRating'), # 대한민국 영상물등급위원회(KMRB) 등급(예: 전체 관람가)
                'license' : status.get('license'), # 동영상 라이선스 (creativeCommon: 타인의 영상 재편집, 재배포 가능, 출처 표기 / youtube: 재사용/수정 불가)
                'embeddable' : status.get('embeddable'), # 영상을 다른 웹사이트에 퍼갈 수 있는가?
                'has_paid_product_placement' : ppl.get('hasPaidProductPlacement'), # 유료 PPL이 사용되는 경우 true, 아니면 False
                # 'width_pixels' : file_details.get('videoStream[]', []).get('widthPixels'), # 콘텐츠 가로 너비
                # 'height_pixels' : file_details.get('videoStream[]', []).get('heightPixels'), # 콘텐츠 세로 높이
                # 'aspect_ratio' : file_details.get('videoStream[]', []).get('aspectRatio'), # 콘텐츠 가로세로 비율
                # 'vendor' : file_details.get('videoStream[]', []).get('vendor'), # 동영상 공급업체 코드
                # 'tag_suggestions_availability' : processing_details.get('tagSuggestionsAvailability'), # 동영상에 키워드 추천을 사용할 수 있는지 여부 (동영상을 더 쉽게 찾을 수 있도록 동영상의 메타데이터에 태그 추가 가능.)
                # 'tag' : suggestions.get('tagSuggestions[]', []).get('tag'), # 영상에 추천된 키워드 태그 
                # 'category_restiricts' : suggestions.get('tagSuggestions[]', []).get('categoryRestricts[]'), # 태그와 관련된 동영상 카테고리 집합
                # 'caption' : content_details.get('caption'), # 자막을 사용할 수 있는지 여부(bool)
                # 'thumbnail' : snippet.get('thumbnails', {}).get('high',{}).get('url'), # 영상 썸네일(고해상도)
            })
        
    # 영상정보 결과 데이터 프레임으로 저장
    df= pd.DataFrame(all_results)
    
    # 파일로 저장.
    if save_path and not df.empty: # 경로가 존재하고, 데이터 프레임이 비어있지 않다면,
        os.makedirs(os.path.dirname(save_path), exist_ok=True) if os.path.dirname(save_path) else None
        
        if not os.path.exists(save_path):
            df.to_csv(save_path, index=False, encoding='utf-8-sig')
        else:
            df.to_csv(save_path, mode='a', header=False, index=False, encoding='utf-8-sig')
    return df

In [ ]:
# =======================================================================
# 유닛 비용 산출 및 가져올 영상 수 정의 : main_video_info(arg1, arg2, arg3, arg4, arg5)
# 
# arg1: 유튜브 API 키
# arg2: 유튜브 API 키 (예비1)
# arg3: 유튜브 API 키 (예비2)
# arg4: 영상 아이디 리스트
# arg5: csv 파일 저장 경로 (예: save_path = './data/result/data1.csv')
#
# [설명]
# 가진 유닛에 맞게 비용을 산출하여 영상 상세정보를 가져오는 함수로 상세정보를 가져오는 함수입니다.
# 이 함수는 이미 해당경로에 불러온 영상 상세정보를 필터링하여 중복을 방지하는 기능도 포함하고 있습니다.
# 남은 유닛 수를 자동으로 가져올 수 없으므로 수동으로 체크해서 가져오셔야 합니다.
# =======================================================================
def main_video_info(youtube_api_key=None, youtube_api_key2=None, youtube_api_key3=None, video_ids=None, save_path=None):
        
    if save_path is None:
        raise ValueError('파일을 저장할 경로를 입력해주세요')
    
    if video_ids is None:
        raise ValueError('영상 아이디 리스트를 입력해주세요.')
    
    # 사용 가능한 유닛 수 계산
    print('='*25, '시작', '='*25)
    print('남은 유닛 수 확인 : https://console.cloud.google.com/iam-admin/quotas?hl=ko')
    
    unit1 = unit2 = unit3 = 0
    if youtube_api_key is not None:
        unit1 = 10000 - int(input('첫 번째 API의 사용한 유닛 수를 입력해주세요(사용량 입력): '))
    if youtube_api_key2 is not None:
        unit2 = 10000 - int(input('두 번째 API의 사용한 유닛 수를 입력해주세요(사용량 입력): '))
    if youtube_api_key3 is not None:
        unit3 = 10000 - int(input('세 번째 API의 사용한 유닛 수를 입력해주세요(사용량 입력): '))
    
    if (youtube_api_key is None) and (youtube_api_key2 is None) and (youtube_api_key3 is None):
        raise ValueError('유튜브 API 키를 입력해주세요.')
    
    total_units = unit1 + unit2 + unit3
    if total_units == 0:
        print('사용 가능한 유닛이 없습니다.')
        return
    
    for api_key in [youtube_api_key, youtube_api_key2, youtube_api_key3]:
        # api_key 있는 것만 사용
        if api_key is None:
            continue
        # 이미 저장 완료된 video_id 가져오기
        existing_video_ids = set()
        if save_path and os.path.exists(save_path):
            existing_df = pd.read_csv(save_path)
            if 'video_id' in existing_df.columns:
                existing_video_ids = set(existing_df['video_id'].dropna().astype(str)) # video_id 가져오기 완료
    
        # 중복 제거된 video_ids 다시 산출
        video_ids = [x for x in video_ids if x not in existing_video_ids]
        
        if len(video_ids) == 0:
            break
        # 조회 가능한 데이터 수
        print('가지고 있는 유닛 수: ', total_units)
        print('총 video_id 개수: ', len(video_ids))
        possible = total_units * 50
        
        print(f'{len(video_ids)}개의 영상 중 {possible}개의 영상이 조회가 가능합니다.')
        get_videos = 0
        while total_units > 0:
            # 조회 가능한 영상 수인지 확인하기
            get_videos = input(f'{len(video_ids)}개의 영상 중 몇 개의 영상을 조회하시겠습니까? (종료: N) :')
            if get_videos == 'N':
                break
            else:
                get_videos =int(get_videos)
                
            if np.ceil(get_videos / 50) > total_units:
                print('가지고 있는 유닛 수로 조회하기엔 영상이 너무 많습니다.')
                get_videos = 0
            
            if total_units == 0:
                break
            
            if get_videos == 0:
                break
            print(f'예상 비용 : {np.ceil(get_videos/50)} 유닛')
            video_list = video_ids[0:get_videos]
            
            get_video_info(api_key=api_key, video_ids=video_list, save_path=save_path)
            total_units = total_units - (np.ceil(get_videos/50))
            
            video_ids = [x for x in video_ids if x not in video_list]
            
            print(f'남은 유닛: {total_units}')
            if total_units <= 0:
                break
        if total_units <= 0:
            break
    return print(f'추출이 완료되었습니다. 파일 경로: {save_path}')

In [ ]:
# =======================================================================
# IT 영상 상세정보 남은 토큰 수에 맞게 가져오기
# =======================================================================
it_videos = pd.read_csv('./data/IT_video_ids.csv')
video_ids = it_videos['video_id'].to_list()
main_video_info(youtube_api_key=youtube_api_key, youtube_api_key2=youtube_api_key2, youtube_api_key3=youtube_api_key3, video_ids=video_ids, save_path='./data/results/it_video_info.csv')

In [ ]:
# =======================================================================
# FOOD 영상 상세정보 남은 토큰 수에 맞게 가져오기
# =======================================================================
food_videos = pd.read_csv('./data/FOOD_video_ids.csv')
video_ids = food_videos['video_id'].to_list()
main_video_info(youtube_api_key=youtube_api_key, youtube_api_key2=youtube_api_key2, youtube_api_key3=youtube_api_key3, video_ids=video_ids, save_path='./data/results/food_video_info.csv')

In [2]:
# 저장된 IT 채널의 영상 상세정보 파일 가져오기
it_video_info = pd.read_csv('./data/results/it_video_info.csv')
print(len(it_video_info))

# 저장된 F&B 채널의 영상 상세정보 파일 가져오기
food_video_info = pd.read_csv('./data/results/food_video_info.csv')
print(len(food_video_info))

20435
21248

---
### 롱폼/숏폼 분류
- 롱폼과 숏폼을 구분해서 따로 분석할 계획
---

In [30]:
# =======================================================================
# 롱폼/숏폼 분류기 : who_long_short_form(arg1, arg2, arg3)
# arg1: DataFrame 변수 이름입니다. (무조건 데이터 프레임 형태)
# arg2: 파일을 저장할 경로입니다! (예: save_path = './data/example.csv')
# arg3: 일꾼의 수 입니다. (기본값: 20)
#
# [작동 원리]
# - Request를 이용하여 youtube/shorts/video_id 형태의 url을 입력하여 HTTP로 호출합니다.
# - 해당 url의 영상이 롱폼이라면 youtube/watch/v=video_id 형태로 변환되어 접속됩니다.
# - response.url을 이용하여 최종적으로 어떤 형식의 url으로 접속되었는지에 따라 롱폼/숏폼으로 구분합니다.
#
# 
# =======================================================================


def who_long_short_form(data=None, save_path=None, workers=20):
    # 1. 데이터 검증 및 준비
    if data is None or not isinstance(data, pd.DataFrame):
        raise ValueError('DataFrame의 이름을 입력해주세요')
    
    if 'video_id' not in data.columns:
        raise KeyError("해당 데이터프레임에 'video_id' 컬럼이 없습니다.")
    
    # 중복 제거된 비디오 ID 리스트 (속도 향상을 위해 고유값만 추출)
    video_ids = data['video_id'].dropna().unique().tolist()
    total_ids = len(video_ids)
    
    # --- 설정값 및 헤더 ---
    HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"}
    
    print(f"🚀 총 {total_ids}개 영상 병렬 분석 시작 (Workers: {workers})...\n")

    # [내부 함수] 개별 영상 분류 로직
    def classify_video(vid):
        url = f'https://www.youtube.com/shorts/{vid}'
        try:
            # allow_redirects=True로 설정하여 최종 URL 확인
            response = requests.get(url, timeout=10, headers=HEADERS)
            final_url = response.url
            raw_html = response.text.replace(" ", "")
            
            # 재생 불가 상태 체크
            if '"playabilityStatus":{"status":"ERROR"' in raw_html or '"playabilityStatus":{"status":"UNPLAYABLE"' in raw_html:
                verdict = 'error'
            elif '/watch' in final_url:
                verdict = 'longform'
            elif '/shorts' in final_url:
                verdict = 'shorts'
            else:
                verdict = 'unknown'
                
            return {'video_id': vid, 'verdict': verdict, 'final_url': final_url}
        
        except Exception as e:
            return {'video_id': vid, 'verdict': 'error', 'final_url': f'Error: {str(e)}'}

    # 2. 멀티쓰레딩 실행
    results = []
    with ThreadPoolExecutor(max_workers=workers) as executor:
        # 진행률 표시를 위해 as_completed 사용
        futures = {executor.submit(classify_video, vid): vid for vid in video_ids}
        
        for i, future in enumerate(as_completed(futures), 1):
            res = future.result()
            results.append(res)
            
            # IPYNB에서 너무 많은 출력을 방지하기 위해 50개마다 진행 상황 출력
            if i % 50 == 0 or i == total_ids:
                print(f"✅ 진행 상황: [{i}/{total_ids}] 완료")

    # 3. 결과 합치기 및 저장
    new_df = pd.DataFrame(results)
    merge_df = pd.merge(data, new_df, on='video_id', how='left')
    
    if save_path:
        os.makedirs(os.path.dirname(save_path) if os.path.dirname(save_path) else '.', exist_ok=True)
        merge_df.to_csv(save_path, index=False, encoding='utf-8-sig')
        print(f"\n💾 결과 저장 완료: {save_path}")
        
    return merge_df

# --- 사용 예시 ---
# food_video_info = pd.read_csv("your_data.csv")
# result_df = who_long_short_fast(food_video_info, save_path='./data/results/food_redirect.csv', workers=30)
# display(result_df.head())

In [ ]:
food_redirect = who_long_short_form(food_video_info, save_path='./data/results/food_redirect.csv', workers=30)
display(food_redirect.head())

🚀 총 21248개 영상 병렬 분석 시작 (Workers: 30)...

✅ 진행 상황: [50/21248] 완료
✅ 진행 상황: [100/21248] 완료
✅ 진행 상황: [150/21248] 완료
✅ 진행 상황: [200/21248] 완료
✅ 진행 상황: [250/21248] 완료
✅ 진행 상황: [300/21248] 완료
✅ 진행 상황: [350/21248] 완료
✅ 진행 상황: [400/21248] 완료
✅ 진행 상황: [450/21248] 완료
✅ 진행 상황: [500/21248] 완료
✅ 진행 상황: [550/21248] 완료
✅ 진행 상황: [600/21248] 완료
✅ 진행 상황: [650/21248] 완료
✅ 진행 상황: [700/21248] 완료
✅ 진행 상황: [750/21248] 완료
✅ 진행 상황: [800/21248] 완료
✅ 진행 상황: [850/21248] 완료
✅ 진행 상황: [900/21248] 완료
✅ 진행 상황: [950/21248] 완료
✅ 진행 상황: [1000/21248] 완료
✅ 진행 상황: [1050/21248] 완료
✅ 진행 상황: [1100/21248] 완료
✅ 진행 상황: [1150/21248] 완료
✅ 진행 상황: [1200/21248] 완료
✅ 진행 상황: [1250/21248] 완료
✅ 진행 상황: [1300/21248] 완료
✅ 진행 상황: [1350/21248] 완료
✅ 진행 상황: [1400/21248] 완료
✅ 진행 상황: [1450/21248] 완료
✅ 진행 상황: [1500/21248] 완료
✅ 진행 상황: [1550/21248] 완료
✅ 진행 상황: [1600/21248] 완료
✅ 진행 상황: [1650/21248] 완료
✅ 진행 상황: [1700/21248] 완료
✅ 진행 상황: [1750/21248] 완료
✅ 진행 상황: [1800/21248] 완료
✅ 진행 상황: [1850/21248] 완료
✅ 진행 상황: [1900/21248] 완료
✅ 진행 상황: [1950/21248] 완료
✅ 진행 상황: [2000/21248] 완료
✅ 진행 상황: [2050/21248] 완료
✅ 진행 상황: [2100/21248] 완료
✅ 진행 상황: [2150/21248] 완료
✅ 진행 상황: [2200/21248] 완료
✅ 진행 상황: [2250/21248] 완료
✅ 진행 상황: [2300/21248] 완료
✅ 진행 상황: [2350/21248] 완료
✅ 진행 상황: [2400/21248] 완료
✅ 진행 상황: [2450/21248] 완료
✅ 진행 상황: [2500/21248] 완료
✅ 진행 상황: [2550/21248] 완료
✅ 진행 상황: [2600/21248] 완료
✅ 진행 상황: [2650/21248] 완료
✅ 진행 상황: [2700/21248] 완료
✅ 진행 상황: [2750/21248] 완료
✅ 진행 상황: [2800/21248] 완료
✅ 진행 상황: [2850/21248] 완료
✅ 진행 상황: [2900/21248] 완료
✅ 진행 상황: [2950/21248] 완료
✅ 진행 상황: [3000/21248] 완료
✅ 진행 상황: [3050/21248] 완료
✅ 진행 상황: [3100/21248] 완료
✅ 진행 상황: [3150/21248] 완료
✅ 진행 상황: [3200/21248] 완료
✅ 진행 상황: [3250/21248] 완료
✅ 진행 상황: [3300/21248] 완료
✅ 진행 상황: [3350/21248] 완료
✅ 진행 상황: [3400/21248] 완료
✅ 진행 상황: [3450/21248] 완료
✅ 진행 상황: [3500/21248] 완료
✅ 진행 상황: [3550/21248] 완료
✅ 진행 상황: [3600/21248] 완료
✅ 진행 상황: [3650/21248] 완료
✅ 진행 상황: [3700/21248] 완료
✅ 진행 상황: [3750/21248] 완료
✅ 진행 상황: [3800/21248] 완료
✅ 진행 상황: [3850/21248] 완료
✅ 진행 상황: [3900/21248] 완료
✅ 진행 상황: [3950/21248] 완료
✅ 진행 상황: [4000/21248] 완료
✅ 진행 상황: [4050/21248] 완료
✅ 진행 상황: [4100/21248] 완료
✅ 진행 상황: [4150/21248] 완료
✅ 진행 상황: [4200/21248] 완료
✅ 진행 상황: [4250/21248] 완료
✅ 진행 상황: [4300/21248] 완료
✅ 진행 상황: [4350/21248] 완료
✅ 진행 상황: [4400/21248] 완료
✅ 진행 상황: [4450/21248] 완료
✅ 진행 상황: [4500/21248] 완료
✅ 진행 상황: [4550/21248] 완료
✅ 진행 상황: [4600/21248] 완료
✅ 진행 상황: [4650/21248] 완료
✅ 진행 상황: [4700/21248] 완료
✅ 진행 상황: [4750/21248] 완료
✅ 진행 상황: [4800/21248] 완료
✅ 진행 상황: [4850/21248] 완료
✅ 진행 상황: [4900/21248] 완료
✅ 진행 상황: [4950/21248] 완료
✅ 진행 상황: [5000/21248] 완료
✅ 진행 상황: [5050/21248] 완료
✅ 진행 상황: [5100/21248] 완료
✅ 진행 상황: [5150/21248] 완료
✅ 진행 상황: [5200/21248] 완료
✅ 진행 상황: [5250/21248] 완료
✅ 진행 상황: [5300/21248] 완료
✅ 진행 상황: [5350/21248] 완료
✅ 진행 상황: [5400/21248] 완료
✅ 진행 상황: [5450/21248] 완료
✅ 진행 상황: [5500/21248] 완료
✅ 진행 상황: [5550/21248] 완료
✅ 진행 상황: [5600/21248] 완료
✅ 진행 상황: [5650/21248] 완료
✅ 진행 상황: [5700/21248] 완료
✅ 진행 상황: [5750/21248] 완료
✅ 진행 상황: [5800/21248] 완료
✅ 진행 상황: [5850/21248] 완료
✅ 진행 상황: [5900/21248] 완료
✅ 진행 상황: [5950/21248] 완료
✅ 진행 상황: [6000/21248] 완료
✅ 진행 상황: [6050/21248] 완료
✅ 진행 상황: [6100/21248] 완료
✅ 진행 상황: [6150/21248] 완료
✅ 진행 상황: [6200/21248] 완료
✅ 진행 상황: [6250/21248] 완료
✅ 진행 상황: [6300/21248] 완료
✅ 진행 상황: [6350/21248] 완료
✅ 진행 상황: [6400/21248] 완료
✅ 진행 상황: [6450/21248] 완료
✅ 진행 상황: [6500/21248] 완료
✅ 진행 상황: [6550/21248] 완료
✅ 진행 상황: [6600/21248] 완료
✅ 진행 상황: [6650/21248] 완료
✅ 진행 상황: [6700/21248] 완료
✅ 진행 상황: [6750/21248] 완료
✅ 진행 상황: [6800/21248] 완료
✅ 진행 상황: [6850/21248] 완료
✅ 진행 상황: [6900/21248] 완료
✅ 진행 상황: [6950/21248] 완료
✅ 진행 상황: [7000/21248] 완료
✅ 진행 상황: [7050/21248] 완료
✅ 진행 상황: [7100/21248] 완료
✅ 진행 상황: [7150/21248] 완료
✅ 진행 상황: [7200/21248] 완료
✅ 진행 상황: [7250/21248] 완료
✅ 진행 상황: [7300/21248] 완료
✅ 진행 상황: [7350/21248] 완료
✅ 진행 상황: [7400/21248] 완료
✅ 진행 상황: [7450/21248] 완료
✅ 진행 상황: [7500/21248] 완료
✅ 진행 상황: [7550/21248] 완료
✅ 진행 상황: [7600/21248] 완료
✅ 진행 상황: [7650/21248] 완료
✅ 진행 상황: [7700/21248] 완료
✅ 진행 상황: [7750/21248] 완료
✅ 진행 상황: [7800/21248] 완료
✅ 진행 상황: [7850/21248] 완료
✅ 진행 상황: [7900/21248] 완료
✅ 진행 상황: [7950/21248] 완료
✅ 진행 상황: [8000/21248] 완료
✅ 진행 상황: [8050/21248] 완료
✅ 진행 상황: [8100/21248] 완료
✅ 진행 상황: [8150/21248] 완료
✅ 진행 상황: [8200/21248] 완료
✅ 진행 상황: [8250/21248] 완료
✅ 진행 상황: [8300/21248] 완료
✅ 진행 상황: [8350/21248] 완료
✅ 진행 상황: [8400/21248] 완료
✅ 진행 상황: [8450/21248] 완료
✅ 진행 상황: [8500/21248] 완료
✅ 진행 상황: [8550/21248] 완료
✅ 진행 상황: [8600/21248] 완료
✅ 진행 상황: [8650/21248] 완료
✅ 진행 상황: [8700/21248] 완료
✅ 진행 상황: [8750/21248] 완료
✅ 진행 상황: [8800/21248] 완료
✅ 진행 상황: [8850/21248] 완료
✅ 진행 상황: [8900/21248] 완료
✅ 진행 상황: [8950/21248] 완료
✅ 진행 상황: [9000/21248] 완료
✅ 진행 상황: [9050/21248] 완료
✅ 진행 상황: [9100/21248] 완료
✅ 진행 상황: [9150/21248] 완료
✅ 진행 상황: [9200/21248] 완료
✅ 진행 상황: [9250/21248] 완료
✅ 진행 상황: [9300/21248] 완료
✅ 진행 상황: [9350/21248] 완료
✅ 진행 상황: [9400/21248] 완료
✅ 진행 상황: [9450/21248] 완료
✅ 진행 상황: [9500/21248] 완료
✅ 진행 상황: [9550/21248] 완료
✅ 진행 상황: [9600/21248] 완료
✅ 진행 상황: [9650/21248] 완료
✅ 진행 상황: [9700/21248] 완료
✅ 진행 상황: [9750/21248] 완료
✅ 진행 상황: [9800/21248] 완료
✅ 진행 상황: [9850/21248] 완료
✅ 진행 상황: [9900/21248] 완료
✅ 진행 상황: [9950/21248] 완료
✅ 진행 상황: [10000/21248] 완료
✅ 진행 상황: [10050/21248] 완료
✅ 진행 상황: [10100/21248] 완료
✅ 진행 상황: [10150/21248] 완료
✅ 진행 상황: [10200/21248] 완료
✅ 진행 상황: [10250/21248] 완료
✅ 진행 상황: [10300/21248] 완료
✅ 진행 상황: [10350/21248] 완료
✅ 진행 상황: [10400/21248] 완료
✅ 진행 상황: [10450/21248] 완료
✅ 진행 상황: [10500/21248] 완료
✅ 진행 상황: [10550/21248] 완료
✅ 진행 상황: [10600/21248] 완료
✅ 진행 상황: [10650/21248] 완료
✅ 진행 상황: [10700/21248] 완료
✅ 진행 상황: [10750/21248] 완료
✅ 진행 상황: [10800/21248] 완료
✅ 진행 상황: [10850/21248] 완료
✅ 진행 상황: [10900/21248] 완료
✅ 진행 상황: [10950/21248] 완료
✅ 진행 상황: [11000/21248] 완료
✅ 진행 상황: [11050/21248] 완료
✅ 진행 상황: [11100/21248] 완료
✅ 진행 상황: [11150/21248] 완료
✅ 진행 상황: [11200/21248] 완료
✅ 진행 상황: [11250/21248] 완료
✅ 진행 상황: [11300/21248] 완료
✅ 진행 상황: [11350/21248] 완료
✅ 진행 상황: [11400/21248] 완료
✅ 진행 상황: [11450/21248] 완료
✅ 진행 상황: [11500/21248] 완료
✅ 진행 상황: [11550/21248] 완료
✅ 진행 상황: [11600/21248] 완료
✅ 진행 상황: [11650/21248] 완료
✅ 진행 상황: [11700/21248] 완료
✅ 진행 상황: [11750/21248] 완료
✅ 진행 상황: [11800/21248] 완료
✅ 진행 상황: [11850/21248] 완료
✅ 진행 상황: [11900/21248] 완료
✅ 진행 상황: [11950/21248] 완료
✅ 진행 상황: [12000/21248] 완료
✅ 진행 상황: [12050/21248] 완료
✅ 진행 상황: [12100/21248] 완료
✅ 진행 상황: [12150/21248] 완료
✅ 진행 상황: [12200/21248] 완료
✅ 진행 상황: [12250/21248] 완료
✅ 진행 상황: [12300/21248] 완료
✅ 진행 상황: [12350/21248] 완료
✅ 진행 상황: [12400/21248] 완료
✅ 진행 상황: [12450/21248] 완료
✅ 진행 상황: [12500/21248] 완료
✅ 진행 상황: [12550/21248] 완료
✅ 진행 상황: [12600/21248] 완료
✅ 진행 상황: [12650/21248] 완료
✅ 진행 상황: [12700/21248] 완료
✅ 진행 상황: [12750/21248] 완료
✅ 진행 상황: [12800/21248] 완료
✅ 진행 상황: [12850/21248] 완료
✅ 진행 상황: [12900/21248] 완료
✅ 진행 상황: [12950/21248] 완료
✅ 진행 상황: [13000/21248] 완료
✅ 진행 상황: [13050/21248] 완료
✅ 진행 상황: [13100/21248] 완료
✅ 진행 상황: [13150/21248] 완료
✅ 진행 상황: [13200/21248] 완료
✅ 진행 상황: [13250/21248] 완료
✅ 진행 상황: [13300/21248] 완료
✅ 진행 상황: [13350/21248] 완료
✅ 진행 상황: [13400/21248] 완료
✅ 진행 상황: [13450/21248] 완료
✅ 진행 상황: [13500/21248] 완료
✅ 진행 상황: [13550/21248] 완료
✅ 진행 상황: [13600/21248] 완료
✅ 진행 상황: [13650/21248] 완료
✅ 진행 상황: [13700/21248] 완료
✅ 진행 상황: [13750/21248] 완료
✅ 진행 상황: [13800/21248] 완료
✅ 진행 상황: [13850/21248] 완료
✅ 진행 상황: [13900/21248] 완료
✅ 진행 상황: [13950/21248] 완료
✅ 진행 상황: [14000/21248] 완료
✅ 진행 상황: [14050/21248] 완료
✅ 진행 상황: [14100/21248] 완료
✅ 진행 상황: [14150/21248] 완료
✅ 진행 상황: [14200/21248] 완료
✅ 진행 상황: [14250/21248] 완료
✅ 진행 상황: [14300/21248] 완료
✅ 진행 상황: [14350/21248] 완료
✅ 진행 상황: [14400/21248] 완료
✅ 진행 상황: [14450/21248] 완료
✅ 진행 상황: [14500/21248] 완료
✅ 진행 상황: [14550/21248] 완료
✅ 진행 상황: [14600/21248] 완료
✅ 진행 상황: [14650/21248] 완료
✅ 진행 상황: [14700/21248] 완료
✅ 진행 상황: [14750/21248] 완료
✅ 진행 상황: [14800/21248] 완료
✅ 진행 상황: [14850/21248] 완료
✅ 진행 상황: [14900/21248] 완료
✅ 진행 상황: [14950/21248] 완료
✅ 진행 상황: [15000/21248] 완료
✅ 진행 상황: [15050/21248] 완료
✅ 진행 상황: [15100/21248] 완료
✅ 진행 상황: [15150/21248] 완료
✅ 진행 상황: [15200/21248] 완료
✅ 진행 상황: [15250/21248] 완료
✅ 진행 상황: [15300/21248] 완료
✅ 진행 상황: [15350/21248] 완료
✅ 진행 상황: [15400/21248] 완료
✅ 진행 상황: [15450/21248] 완료
✅ 진행 상황: [15500/21248] 완료
✅ 진행 상황: [15550/21248] 완료
✅ 진행 상황: [15600/21248] 완료
✅ 진행 상황: [15650/21248] 완료
✅ 진행 상황: [15700/21248] 완료
✅ 진행 상황: [15750/21248] 완료
✅ 진행 상황: [15800/21248] 완료
✅ 진행 상황: [15850/21248] 완료
✅ 진행 상황: [15900/21248] 완료
✅ 진행 상황: [15950/21248] 완료
✅ 진행 상황: [16000/21248] 완료
✅ 진행 상황: [16050/21248] 완료
✅ 진행 상황: [16100/21248] 완료
✅ 진행 상황: [16150/21248] 완료
✅ 진행 상황: [16200/21248] 완료
✅ 진행 상황: [16250/21248] 완료
✅ 진행 상황: [16300/21248] 완료
✅ 진행 상황: [16350/21248] 완료
✅ 진행 상황: [16400/21248] 완료
✅ 진행 상황: [16450/21248] 완료
✅ 진행 상황: [16500/21248] 완료
✅ 진행 상황: [16550/21248] 완료
✅ 진행 상황: [16600/21248] 완료
✅ 진행 상황: [16650/21248] 완료
✅ 진행 상황: [16700/21248] 완료
✅ 진행 상황: [16750/21248] 완료
✅ 진행 상황: [16800/21248] 완료
✅ 진행 상황: [16850/21248] 완료
✅ 진행 상황: [16900/21248] 완료
✅ 진행 상황: [16950/21248] 완료
✅ 진행 상황: [17000/21248] 완료
✅ 진행 상황: [17050/21248] 완료
✅ 진행 상황: [17100/21248] 완료
✅ 진행 상황: [17150/21248] 완료
✅ 진행 상황: [17200/21248] 완료
✅ 진행 상황: [17250/21248] 완료
✅ 진행 상황: [17300/21248] 완료
✅ 진행 상황: [17350/21248] 완료
✅ 진행 상황: [17400/21248] 완료
✅ 진행 상황: [17450/21248] 완료
✅ 진행 상황: [17500/21248] 완료
✅ 진행 상황: [17550/21248] 완료
✅ 진행 상황: [17600/21248] 완료
✅ 진행 상황: [17650/21248] 완료
✅ 진행 상황: [17700/21248] 완료
✅ 진행 상황: [17750/21248] 완료
✅ 진행 상황: [17800/21248] 완료
✅ 진행 상황: [17850/21248] 완료
✅ 진행 상황: [17900/21248] 완료
✅ 진행 상황: [17950/21248] 완료
✅ 진행 상황: [18000/21248] 완료
✅ 진행 상황: [18050/21248] 완료
✅ 진행 상황: [18100/21248] 완료
✅ 진행 상황: [18150/21248] 완료
✅ 진행 상황: [18200/21248] 완료
✅ 진행 상황: [18250/21248] 완료
✅ 진행 상황: [18300/21248] 완료
✅ 진행 상황: [18350/21248] 완료
✅ 진행 상황: [18400/21248] 완료
✅ 진행 상황: [18450/21248] 완료
✅ 진행 상황: [18500/21248] 완료
✅ 진행 상황: [18550/21248] 완료
✅ 진행 상황: [18600/21248] 완료
✅ 진행 상황: [18650/21248] 완료
✅ 진행 상황: [18700/21248] 완료
✅ 진행 상황: [18750/21248] 완료
✅ 진행 상황: [18800/21248] 완료
✅ 진행 상황: [18850/21248] 완료
✅ 진행 상황: [18900/21248] 완료
✅ 진행 상황: [18950/21248] 완료
✅ 진행 상황: [19000/21248] 완료
✅ 진행 상황: [19050/21248] 완료
✅ 진행 상황: [19100/21248] 완료
✅ 진행 상황: [19150/21248] 완료
✅ 진행 상황: [19200/21248] 완료
✅ 진행 상황: [19250/21248] 완료
✅ 진행 상황: [19300/21248] 완료
✅ 진행 상황: [19350/21248] 완료
✅ 진행 상황: [19400/21248] 완료
✅ 진행 상황: [19450/21248] 완료
✅ 진행 상황: [19500/21248] 완료
✅ 진행 상황: [19550/21248] 완료
✅ 진행 상황: [19600/21248] 완료
✅ 진행 상황: [19650/21248] 완료
✅ 진행 상황: [19700/21248] 완료
✅ 진행 상황: [19750/21248] 완료
✅ 진행 상황: [19800/21248] 완료
✅ 진행 상황: [19850/21248] 완료
✅ 진행 상황: [19900/21248] 완료
✅ 진행 상황: [19950/21248] 완료
✅ 진행 상황: [20000/21248] 완료
✅ 진행 상황: [20050/21248] 완료
✅ 진행 상황: [20100/21248] 완료
✅ 진행 상황: [20150/21248] 완료
✅ 진행 상황: [20200/21248] 완료
✅ 진행 상황: [20250/21248] 완료
✅ 진행 상황: [20300/21248] 완료
✅ 진행 상황: [20350/21248] 완료
✅ 진행 상황: [20400/21248] 완료
✅ 진행 상황: [20450/21248] 완료
✅ 진행 상황: [20500/21248] 완료
✅ 진행 상황: [20550/21248] 완료
✅ 진행 상황: [20600/21248] 완료
✅ 진행 상황: [20650/21248] 완료
✅ 진행 상황: [20700/21248] 완료
✅ 진행 상황: [20750/21248] 완료
✅ 진행 상황: [20800/21248] 완료
✅ 진행 상황: [20850/21248] 완료
✅ 진행 상황: [20900/21248] 완료
✅ 진행 상황: [20950/21248] 완료
✅ 진행 상황: [21000/21248] 완료
✅ 진행 상황: [21050/21248] 완료
✅ 진행 상황: [21100/21248] 완료
✅ 진행 상황: [21150/21248] 완료
✅ 진행 상황: [21200/21248] 완료
✅ 진행 상황: [21248/21248] 완료

💾 결과 저장 완료: ./data/results/food_redirect.csv

,video_id,title,channel_id,channel_title,description,upload_date,tags,category_id,view_count,like_count,comment_count,duration,definition,license,embeddable,has_paid_product_placement,thumbnail,thumbnail_h,thumbnail_w,caption,verdict,final_url
0,gVdoQQI53HU,우베가 CU에도 나왔나배 | [톡! 까놓고 신상리뷰💬],UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],우베 디저트부터\n베이크하우스 405 담당 MD가 \n직접 소개하는 빵 신상까지!\...,2026-04-20T09:30:31Z,"CU편의점, CU, 씨유, 헤이루, Heyroo",20,2228,49.0,5.0,PT17M56S,hd,youtube,True,False,https://i.ytimg.com/vi/gVdoQQI53HU/hqdefault.jpg,360,480,False,longform,https://www.youtube.com/watch?v=gVdoQQI53HU
1,FuZKyvWuWP8,데우면 더 위험해지는 초코바게트 [톡! 까놓고 신상리뷰],UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],"초코칩과 가나슈가 듬뿍! 유행 초코템🍫\n📌405 초코바게트 3,200원\n\n지금...",2026-04-17T09:30:18Z,"CU편의점, CU, 씨유, 헤이루, Heyroo",20,144318,272.0,0.0,PT16S,hd,youtube,True,False,https://i.ytimg.com/vi/FuZKyvWuWP8/hqdefault.jpg,360,480,False,shorts,https://www.youtube.com/shorts/FuZKyvWuWP8
2,_1T0CAWGsPE,두바이 버터떡은 무슨 맛일까? [톡! 까놓고 신상리뷰],UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],"푸짐한 카다이프 페이스트를 쫄깃하게 감싼 버터떡🫶\n📌조이 두바이버터떡 3,900원...",2026-04-16T10:01:04Z,"CU편의점, CU, 씨유, 헤이루, Heyroo",20,135901,242.0,2.0,PT18S,hd,youtube,True,False,https://i.ytimg.com/vi/_1T0CAWGsPE/hqdefault.jpg,360,480,False,shorts,https://www.youtube.com/shorts/_1T0CAWGsPE
3,zrhBNe2EMNY,CU가 유행 끝내겠습니다 | [톡! 까놓고 신상리뷰💬],UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],두쫀쿠를 품은 버터떡에😋\n생과일을 품은 프리미엄 하이볼까지!🍊\n\n4월 2주차 ...,2026-04-13T10:01:41Z,"CU편의점, CU, 씨유, 헤이루, Heyroo",20,105129,86.0,7.0,PT16M43S,hd,youtube,True,False,https://i.ytimg.com/vi/zrhBNe2EMNY/hqdefault.jpg,360,480,False,longform,https://www.youtube.com/watch?v=zrhBNe2EMNY
4,kgajE44zZfo,짭짤하게 즐기는 황치즈쫀득쿠키 [톡! 까놓고 신상리뷰],UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],"황치즈 러버라면 지나칠 수 없는 디저트 출시!\n📌황치즈쫀득쿠키 3,500원\n\n...",2026-04-10T09:01:16Z,"CU편의점, CU, 씨유, 헤이루, Heyroo",20,100489,185.0,0.0,PT26S,hd,youtube,True,False,https://i.ytimg.com/vi/kgajE44zZfo/hqdefault.jpg,360,480,False,shorts,https://www.youtube.com/shorts/kgajE44zZfo

In [31]:
it_redirect = who_long_short_form(it_video_info, save_path='./data/results/it_redirect.csv', workers=30)
display(it_redirect.head())

🚀 총 20435개 영상 병렬 분석 시작 (Workers: 30)...

✅ 진행 상황: [50/20435] 완료
✅ 진행 상황: [100/20435] 완료
✅ 진행 상황: [150/20435] 완료
✅ 진행 상황: [200/20435] 완료
✅ 진행 상황: [250/20435] 완료
✅ 진행 상황: [300/20435] 완료
✅ 진행 상황: [350/20435] 완료
✅ 진행 상황: [400/20435] 완료
✅ 진행 상황: [450/20435] 완료
✅ 진행 상황: [500/20435] 완료
✅ 진행 상황: [550/20435] 완료
✅ 진행 상황: [600/20435] 완료
✅ 진행 상황: [650/20435] 완료
✅ 진행 상황: [700/20435] 완료
✅ 진행 상황: [750/20435] 완료
✅ 진행 상황: [800/20435] 완료
✅ 진행 상황: [850/20435] 완료
✅ 진행 상황: [900/20435] 완료
✅ 진행 상황: [950/20435] 완료
✅ 진행 상황: [1000/20435] 완료
✅ 진행 상황: [1050/20435] 완료
✅ 진행 상황: [1100/20435] 완료
✅ 진행 상황: [1150/20435] 완료
✅ 진행 상황: [1200/20435] 완료
✅ 진행 상황: [1250/20435] 완료
✅ 진행 상황: [1300/20435] 완료
✅ 진행 상황: [1350/20435] 완료
✅ 진행 상황: [1400/20435] 완료
✅ 진행 상황: [1450/20435] 완료
✅ 진행 상황: [1500/20435] 완료
✅ 진행 상황: [1550/20435] 완료
✅ 진행 상황: [1600/20435] 완료
✅ 진행 상황: [1650/20435] 완료
✅ 진행 상황: [1700/20435] 완료
✅ 진행 상황: [1750/20435] 완료
✅ 진행 상황: [1800/20435] 완료
✅ 진행 상황: [1850/20435] 완료
✅ 진행 상황: [1900/20435] 완료
✅ 진행 상황: [1950/20435] 완료
✅ 진행 상황: [2000/20435] 완료
✅ 진행 상황: [2050/20435] 완료
✅ 진행 상황: [2100/20435] 완료
✅ 진행 상황: [2150/20435] 완료
✅ 진행 상황: [2200/20435] 완료
✅ 진행 상황: [2250/20435] 완료
✅ 진행 상황: [2300/20435] 완료
✅ 진행 상황: [2350/20435] 완료
✅ 진행 상황: [2400/20435] 완료
✅ 진행 상황: [2450/20435] 완료
✅ 진행 상황: [2500/20435] 완료
✅ 진행 상황: [2550/20435] 완료
✅ 진행 상황: [2600/20435] 완료
✅ 진행 상황: [2650/20435] 완료
✅ 진행 상황: [2700/20435] 완료
✅ 진행 상황: [2750/20435] 완료
✅ 진행 상황: [2800/20435] 완료
✅ 진행 상황: [2850/20435] 완료
✅ 진행 상황: [2900/20435] 완료
✅ 진행 상황: [2950/20435] 완료
✅ 진행 상황: [3000/20435] 완료
✅ 진행 상황: [3050/20435] 완료
✅ 진행 상황: [3100/20435] 완료
✅ 진행 상황: [3150/20435] 완료
✅ 진행 상황: [3200/20435] 완료
✅ 진행 상황: [3250/20435] 완료
✅ 진행 상황: [3300/20435] 완료
✅ 진행 상황: [3350/20435] 완료
✅ 진행 상황: [3400/20435] 완료
✅ 진행 상황: [3450/20435] 완료
✅ 진행 상황: [3500/20435] 완료
✅ 진행 상황: [3550/20435] 완료
✅ 진행 상황: [3600/20435] 완료
✅ 진행 상황: [3650/20435] 완료
✅ 진행 상황: [3700/20435] 완료
✅ 진행 상황: [3750/20435] 완료
✅ 진행 상황: [3800/20435] 완료
✅ 진행 상황: [3850/20435] 완료
✅ 진행 상황: [3900/20435] 완료
✅ 진행 상황: [3950/20435] 완료
✅ 진행 상황: [4000/20435] 완료
✅ 진행 상황: [4050/20435] 완료
✅ 진행 상황: [4100/20435] 완료
✅ 진행 상황: [4150/20435] 완료
✅ 진행 상황: [4200/20435] 완료
✅ 진행 상황: [4250/20435] 완료
✅ 진행 상황: [4300/20435] 완료
✅ 진행 상황: [4350/20435] 완료
✅ 진행 상황: [4400/20435] 완료
✅ 진행 상황: [4450/20435] 완료
✅ 진행 상황: [4500/20435] 완료
✅ 진행 상황: [4550/20435] 완료
✅ 진행 상황: [4600/20435] 완료
✅ 진행 상황: [4650/20435] 완료
✅ 진행 상황: [4700/20435] 완료
✅ 진행 상황: [4750/20435] 완료
✅ 진행 상황: [4800/20435] 완료
✅ 진행 상황: [4850/20435] 완료
✅ 진행 상황: [4900/20435] 완료
✅ 진행 상황: [4950/20435] 완료
✅ 진행 상황: [5000/20435] 완료
✅ 진행 상황: [5050/20435] 완료
✅ 진행 상황: [5100/20435] 완료
✅ 진행 상황: [5150/20435] 완료
✅ 진행 상황: [5200/20435] 완료
✅ 진행 상황: [5250/20435] 완료
✅ 진행 상황: [5300/20435] 완료
✅ 진행 상황: [5350/20435] 완료
✅ 진행 상황: [5400/20435] 완료
✅ 진행 상황: [5450/20435] 완료
✅ 진행 상황: [5500/20435] 완료
✅ 진행 상황: [5550/20435] 완료
✅ 진행 상황: [5600/20435] 완료
✅ 진행 상황: [5650/20435] 완료
✅ 진행 상황: [5700/20435] 완료
✅ 진행 상황: [5750/20435] 완료
✅ 진행 상황: [5800/20435] 완료
✅ 진행 상황: [5850/20435] 완료
✅ 진행 상황: [5900/20435] 완료
✅ 진행 상황: [5950/20435] 완료
✅ 진행 상황: [6000/20435] 완료
✅ 진행 상황: [6050/20435] 완료
✅ 진행 상황: [6100/20435] 완료
✅ 진행 상황: [6150/20435] 완료
✅ 진행 상황: [6200/20435] 완료
✅ 진행 상황: [6250/20435] 완료
✅ 진행 상황: [6300/20435] 완료
✅ 진행 상황: [6350/20435] 완료
✅ 진행 상황: [6400/20435] 완료
✅ 진행 상황: [6450/20435] 완료
✅ 진행 상황: [6500/20435] 완료
✅ 진행 상황: [6550/20435] 완료
✅ 진행 상황: [6600/20435] 완료
✅ 진행 상황: [6650/20435] 완료
✅ 진행 상황: [6700/20435] 완료
✅ 진행 상황: [6750/20435] 완료
✅ 진행 상황: [6800/20435] 완료
✅ 진행 상황: [6850/20435] 완료
✅ 진행 상황: [6900/20435] 완료
✅ 진행 상황: [6950/20435] 완료
✅ 진행 상황: [7000/20435] 완료
✅ 진행 상황: [7050/20435] 완료
✅ 진행 상황: [7100/20435] 완료
✅ 진행 상황: [7150/20435] 완료
✅ 진행 상황: [7200/20435] 완료
✅ 진행 상황: [7250/20435] 완료
✅ 진행 상황: [7300/20435] 완료
✅ 진행 상황: [7350/20435] 완료
✅ 진행 상황: [7400/20435] 완료
✅ 진행 상황: [7450/20435] 완료
✅ 진행 상황: [7500/20435] 완료
✅ 진행 상황: [7550/20435] 완료
✅ 진행 상황: [7600/20435] 완료
✅ 진행 상황: [7650/20435] 완료
✅ 진행 상황: [7700/20435] 완료
✅ 진행 상황: [7750/20435] 완료
✅ 진행 상황: [7800/20435] 완료
✅ 진행 상황: [7850/20435] 완료
✅ 진행 상황: [7900/20435] 완료
✅ 진행 상황: [7950/20435] 완료
✅ 진행 상황: [8000/20435] 완료
✅ 진행 상황: [8050/20435] 완료
✅ 진행 상황: [8100/20435] 완료
✅ 진행 상황: [8150/20435] 완료
✅ 진행 상황: [8200/20435] 완료
✅ 진행 상황: [8250/20435] 완료
✅ 진행 상황: [8300/20435] 완료
✅ 진행 상황: [8350/20435] 완료
✅ 진행 상황: [8400/20435] 완료
✅ 진행 상황: [8450/20435] 완료
✅ 진행 상황: [8500/20435] 완료
✅ 진행 상황: [8550/20435] 완료
✅ 진행 상황: [8600/20435] 완료
✅ 진행 상황: [8650/20435] 완료
✅ 진행 상황: [8700/20435] 완료
✅ 진행 상황: [8750/20435] 완료
✅ 진행 상황: [8800/20435] 완료
✅ 진행 상황: [8850/20435] 완료
✅ 진행 상황: [8900/20435] 완료
✅ 진행 상황: [8950/20435] 완료
✅ 진행 상황: [9000/20435] 완료
✅ 진행 상황: [9050/20435] 완료
✅ 진행 상황: [9100/20435] 완료
✅ 진행 상황: [9150/20435] 완료
✅ 진행 상황: [9200/20435] 완료
✅ 진행 상황: [9250/20435] 완료
✅ 진행 상황: [9300/20435] 완료
✅ 진행 상황: [9350/20435] 완료
✅ 진행 상황: [9400/20435] 완료
✅ 진행 상황: [9450/20435] 완료
✅ 진행 상황: [9500/20435] 완료
✅ 진행 상황: [9550/20435] 완료
✅ 진행 상황: [9600/20435] 완료
✅ 진행 상황: [9650/20435] 완료
✅ 진행 상황: [9700/20435] 완료
✅ 진행 상황: [9750/20435] 완료
✅ 진행 상황: [9800/20435] 완료
✅ 진행 상황: [9850/20435] 완료
✅ 진행 상황: [9900/20435] 완료
✅ 진행 상황: [9950/20435] 완료
✅ 진행 상황: [10000/20435] 완료
✅ 진행 상황: [10050/20435] 완료
✅ 진행 상황: [10100/20435] 완료
✅ 진행 상황: [10150/20435] 완료
✅ 진행 상황: [10200/20435] 완료
✅ 진행 상황: [10250/20435] 완료
✅ 진행 상황: [10300/20435] 완료
✅ 진행 상황: [10350/20435] 완료
✅ 진행 상황: [10400/20435] 완료
✅ 진행 상황: [10450/20435] 완료
✅ 진행 상황: [10500/20435] 완료
✅ 진행 상황: [10550/20435] 완료
✅ 진행 상황: [10600/20435] 완료
✅ 진행 상황: [10650/20435] 완료
✅ 진행 상황: [10700/20435] 완료
✅ 진행 상황: [10750/20435] 완료
✅ 진행 상황: [10800/20435] 완료
✅ 진행 상황: [10850/20435] 완료
✅ 진행 상황: [10900/20435] 완료
✅ 진행 상황: [10950/20435] 완료
✅ 진행 상황: [11000/20435] 완료
✅ 진행 상황: [11050/20435] 완료
✅ 진행 상황: [11100/20435] 완료
✅ 진행 상황: [11150/20435] 완료
✅ 진행 상황: [11200/20435] 완료
✅ 진행 상황: [11250/20435] 완료
✅ 진행 상황: [11300/20435] 완료
✅ 진행 상황: [11350/20435] 완료
✅ 진행 상황: [11400/20435] 완료
✅ 진행 상황: [11450/20435] 완료
✅ 진행 상황: [11500/20435] 완료
✅ 진행 상황: [11550/20435] 완료
✅ 진행 상황: [11600/20435] 완료
✅ 진행 상황: [11650/20435] 완료
✅ 진행 상황: [11700/20435] 완료
✅ 진행 상황: [11750/20435] 완료
✅ 진행 상황: [11800/20435] 완료
✅ 진행 상황: [11850/20435] 완료
✅ 진행 상황: [11900/20435] 완료
✅ 진행 상황: [11950/20435] 완료
✅ 진행 상황: [12000/20435] 완료
✅ 진행 상황: [12050/20435] 완료
✅ 진행 상황: [12100/20435] 완료
✅ 진행 상황: [12150/20435] 완료
✅ 진행 상황: [12200/20435] 완료
✅ 진행 상황: [12250/20435] 완료
✅ 진행 상황: [12300/20435] 완료
✅ 진행 상황: [12350/20435] 완료
✅ 진행 상황: [12400/20435] 완료
✅ 진행 상황: [12450/20435] 완료
✅ 진행 상황: [12500/20435] 완료
✅ 진행 상황: [12550/20435] 완료
✅ 진행 상황: [12600/20435] 완료
✅ 진행 상황: [12650/20435] 완료
✅ 진행 상황: [12700/20435] 완료
✅ 진행 상황: [12750/20435] 완료
✅ 진행 상황: [12800/20435] 완료
✅ 진행 상황: [12850/20435] 완료
✅ 진행 상황: [12900/20435] 완료
✅ 진행 상황: [12950/20435] 완료
✅ 진행 상황: [13000/20435] 완료
✅ 진행 상황: [13050/20435] 완료
✅ 진행 상황: [13100/20435] 완료
✅ 진행 상황: [13150/20435] 완료
✅ 진행 상황: [13200/20435] 완료
✅ 진행 상황: [13250/20435] 완료
✅ 진행 상황: [13300/20435] 완료
✅ 진행 상황: [13350/20435] 완료
✅ 진행 상황: [13400/20435] 완료
✅ 진행 상황: [13450/20435] 완료
✅ 진행 상황: [13500/20435] 완료
✅ 진행 상황: [13550/20435] 완료
✅ 진행 상황: [13600/20435] 완료
✅ 진행 상황: [13650/20435] 완료
✅ 진행 상황: [13700/20435] 완료
✅ 진행 상황: [13750/20435] 완료
✅ 진행 상황: [13800/20435] 완료
✅ 진행 상황: [13850/20435] 완료
✅ 진행 상황: [13900/20435] 완료
✅ 진행 상황: [13950/20435] 완료
✅ 진행 상황: [14000/20435] 완료
✅ 진행 상황: [14050/20435] 완료
✅ 진행 상황: [14100/20435] 완료
✅ 진행 상황: [14150/20435] 완료
✅ 진행 상황: [14200/20435] 완료
✅ 진행 상황: [14250/20435] 완료
✅ 진행 상황: [14300/20435] 완료
✅ 진행 상황: [14350/20435] 완료
✅ 진행 상황: [14400/20435] 완료
✅ 진행 상황: [14450/20435] 완료
✅ 진행 상황: [14500/20435] 완료
✅ 진행 상황: [14550/20435] 완료
✅ 진행 상황: [14600/20435] 완료
✅ 진행 상황: [14650/20435] 완료
✅ 진행 상황: [14700/20435] 완료
✅ 진행 상황: [14750/20435] 완료
✅ 진행 상황: [14800/20435] 완료
✅ 진행 상황: [14850/20435] 완료
✅ 진행 상황: [14900/20435] 완료
✅ 진행 상황: [14950/20435] 완료
✅ 진행 상황: [15000/20435] 완료
✅ 진행 상황: [15050/20435] 완료
✅ 진행 상황: [15100/20435] 완료
✅ 진행 상황: [15150/20435] 완료
✅ 진행 상황: [15200/20435] 완료
✅ 진행 상황: [15250/20435] 완료
✅ 진행 상황: [15300/20435] 완료
✅ 진행 상황: [15350/20435] 완료
✅ 진행 상황: [15400/20435] 완료
✅ 진행 상황: [15450/20435] 완료
✅ 진행 상황: [15500/20435] 완료
✅ 진행 상황: [15550/20435] 완료
✅ 진행 상황: [15600/20435] 완료
✅ 진행 상황: [15650/20435] 완료
✅ 진행 상황: [15700/20435] 완료
✅ 진행 상황: [15750/20435] 완료
✅ 진행 상황: [15800/20435] 완료
✅ 진행 상황: [15850/20435] 완료
✅ 진행 상황: [15900/20435] 완료
✅ 진행 상황: [15950/20435] 완료
✅ 진행 상황: [16000/20435] 완료
✅ 진행 상황: [16050/20435] 완료
✅ 진행 상황: [16100/20435] 완료
✅ 진행 상황: [16150/20435] 완료
✅ 진행 상황: [16200/20435] 완료
✅ 진행 상황: [16250/20435] 완료
✅ 진행 상황: [16300/20435] 완료
✅ 진행 상황: [16350/20435] 완료
✅ 진행 상황: [16400/20435] 완료
✅ 진행 상황: [16450/20435] 완료
✅ 진행 상황: [16500/20435] 완료
✅ 진행 상황: [16550/20435] 완료
✅ 진행 상황: [16600/20435] 완료
✅ 진행 상황: [16650/20435] 완료
✅ 진행 상황: [16700/20435] 완료
✅ 진행 상황: [16750/20435] 완료
✅ 진행 상황: [16800/20435] 완료
✅ 진행 상황: [16850/20435] 완료
✅ 진행 상황: [16900/20435] 완료
✅ 진행 상황: [16950/20435] 완료
✅ 진행 상황: [17000/20435] 완료
✅ 진행 상황: [17050/20435] 완료
✅ 진행 상황: [17100/20435] 완료
✅ 진행 상황: [17150/20435] 완료
✅ 진행 상황: [17200/20435] 완료
✅ 진행 상황: [17250/20435] 완료
✅ 진행 상황: [17300/20435] 완료
✅ 진행 상황: [17350/20435] 완료
✅ 진행 상황: [17400/20435] 완료
✅ 진행 상황: [17450/20435] 완료
✅ 진행 상황: [17500/20435] 완료
✅ 진행 상황: [17550/20435] 완료
✅ 진행 상황: [17600/20435] 완료
✅ 진행 상황: [17650/20435] 완료
✅ 진행 상황: [17700/20435] 완료
✅ 진행 상황: [17750/20435] 완료
✅ 진행 상황: [17800/20435] 완료
✅ 진행 상황: [17850/20435] 완료
✅ 진행 상황: [17900/20435] 완료
✅ 진행 상황: [17950/20435] 완료
✅ 진행 상황: [18000/20435] 완료
✅ 진행 상황: [18050/20435] 완료
✅ 진행 상황: [18100/20435] 완료
✅ 진행 상황: [18150/20435] 완료
✅ 진행 상황: [18200/20435] 완료
✅ 진행 상황: [18250/20435] 완료
✅ 진행 상황: [18300/20435] 완료
✅ 진행 상황: [18350/20435] 완료
✅ 진행 상황: [18400/20435] 완료
✅ 진행 상황: [18450/20435] 완료
✅ 진행 상황: [18500/20435] 완료
✅ 진행 상황: [18550/20435] 완료
✅ 진행 상황: [18600/20435] 완료
✅ 진행 상황: [18650/20435] 완료
✅ 진행 상황: [18700/20435] 완료
✅ 진행 상황: [18750/20435] 완료
✅ 진행 상황: [18800/20435] 완료
✅ 진행 상황: [18850/20435] 완료
✅ 진행 상황: [18900/20435] 완료
✅ 진행 상황: [18950/20435] 완료
✅ 진행 상황: [19000/20435] 완료
✅ 진행 상황: [19050/20435] 완료
✅ 진행 상황: [19100/20435] 완료
✅ 진행 상황: [19150/20435] 완료
✅ 진행 상황: [19200/20435] 완료
✅ 진행 상황: [19250/20435] 완료
✅ 진행 상황: [19300/20435] 완료
✅ 진행 상황: [19350/20435] 완료
✅ 진행 상황: [19400/20435] 완료
✅ 진행 상황: [19450/20435] 완료
✅ 진행 상황: [19500/20435] 완료
✅ 진행 상황: [19550/20435] 완료
✅ 진행 상황: [19600/20435] 완료
✅ 진행 상황: [19650/20435] 완료
✅ 진행 상황: [19700/20435] 완료
✅ 진행 상황: [19750/20435] 완료
✅ 진행 상황: [19800/20435] 완료
✅ 진행 상황: [19850/20435] 완료
✅ 진행 상황: [19900/20435] 완료
✅ 진행 상황: [19950/20435] 완료
✅ 진행 상황: [20000/20435] 완료
✅ 진행 상황: [20050/20435] 완료
✅ 진행 상황: [20100/20435] 완료
✅ 진행 상황: [20150/20435] 완료
✅ 진행 상황: [20200/20435] 완료
✅ 진행 상황: [20250/20435] 완료
✅ 진행 상황: [20300/20435] 완료
✅ 진행 상황: [20350/20435] 완료
✅ 진행 상황: [20400/20435] 완료
✅ 진행 상황: [20435/20435] 완료

💾 결과 저장 완료: ./data/results/it_redirect.csv

,video_id,title,channel_id,channel_title,description,upload_date,tags,category_id,view_count,like_count,comment_count,duration,definition,license,embeddable,has_paid_product_placement,thumbnail,thumbnail_h,thumbnail_w,caption,verdict,final_url
0,YkE11u3wqcY,[#꿀팁줍숏] 퇴근 1시간 앞당기는 엑셀 단축키 2) Multi Key 📊,UCVaIGU8ch9zG42j-rAG6VoA,삼성SDS,엑셀. 언제까지 마우스로 딸깍거릴 거예요? 실전 단축키 모음 2탄! ⌨\n\nCtr...,2026-04-21T10:00:48Z,"삼성SDS, 삼성에스디에스, 꿀팁줍숏, AI활용법, 생성형AI, FabriX, Br...",28,1004,10.0,0.0,PT1M6S,hd,youtube,True,False,https://i.ytimg.com/vi/YkE11u3wqcY/hqdefault.jpg,360,480,False,shorts,https://www.youtube.com/shorts/YkE11u3wqcY
1,NSxpdlnn9wo,[#꿀팁줍숏] 퇴근 1시간 앞당기는 엑셀 단축키 1) Single Key 📊,UCVaIGU8ch9zG42j-rAG6VoA,삼성SDS,엑셀. 아직도 마우스로 하나하나 작업하며 시간 낭비 중?\n그거 계속하면 손목 터널...,2026-04-14T10:00:28Z,"삼성SDS, 삼성에스디에스, 꿀팁줍숏, AI활용법, 생성형AI, FabriX, Br...",28,2623,42.0,1.0,PT1M3S,hd,youtube,True,False,https://i.ytimg.com/vi/NSxpdlnn9wo/hqdefault.jpg,360,480,False,shorts,https://www.youtube.com/shorts/NSxpdlnn9wo
2,0mRKMcTFPAY,[#꿀팁줍숏] 일은 잘 시켜야 잘한다! 생성형 AI 프롬프트 잘 뽑는 법 ✨,UCVaIGU8ch9zG42j-rAG6VoA,삼성SDS,"너도 나도 다 쓰는 생성형 AI, 업무 중 쓰려니 자꾸 엉뚱한 대답만 내놓는다고? ...",2026-04-08T00:53:48Z,"삼성SDS, 삼성에스디에스, 꿀팁줍숏, 프롬프트, AI활용법, 생성형AI, Fabr...",28,716,10.0,0.0,PT1M3S,hd,youtube,True,False,https://i.ytimg.com/vi/0mRKMcTFPAY/hqdefault.jpg,360,480,False,shorts,https://www.youtube.com/shorts/0mRKMcTFPAY
3,mBu4qOdH8aI,[웨비나] 지능형 AI 협업으로 시작하는 공공부문 일하는 방식의 변화,UCVaIGU8ch9zG42j-rAG6VoA,삼성SDS,"반복되는 문서 작성, 부서 간 복잡한 협업..\n“조금 더 효율적인 방법은 없을까?...",2026-04-06T09:23:18Z,NaN,28,830,14.0,1.0,PT1H2M35S,hd,youtube,True,False,https://i.ytimg.com/vi/mBu4qOdH8aI/hqdefault.jpg,360,480,False,longform,https://www.youtube.com/watch?v=mBu4qOdH8aI
4,6D2ueCdbbes,"봄, 사랑, 벚꽃 말고 이거 챙겨라~! 🌸 feat. 2026년 4월 석촌호수 개발...",UCVaIGU8ch9zG42j-rAG6VoA,삼성SDS,벚꽃하면 어디? 석촌호수 🌸\n미신이요? 하면 지평좌표계 먼저 찾는 슈퍼T 부기 앞...,2026-04-02T10:00:09Z,"석촌호수, 석촌호수 실시간, 석촌호수 벚꽃축제, 벚꽃축제, 잠실 벚꽃, 서울 벚꽃,...",28,341,6.0,0.0,PT49S,hd,youtube,True,False,https://i.ytimg.com/vi/6D2ueCdbbes/hqdefault.jpg,360,480,False,longform,https://www.youtube.com/watch?v=6D2ueCdbbes

In [34]:
it_redirect[it_redirect['verdict']=='error']

,video_id,title,channel_id,channel_title,description,upload_date,tags,category_id,view_count,like_count,comment_count,duration,definition,license,embeddable,has_paid_product_placement,thumbnail,thumbnail_h,thumbnail_w,caption,verdict,final_url
4967,GALDe3pyq48,"[B tv 영화 추천/movie Big #20] 오션스 8, 도둑들, 섹션제로3: ...",UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,[금주의 빅무비] - 섹션제로3: 블록13\n[무비빅스타] - 영화배우 김환희\n[...,2018-08-03T02:54:09Z,"SK브로드밴드, SKB, B tv, movie Big, 백업무비, 버킷무비, 무비빅...",1,404,1.0,0.0,PT54M18S,hd,youtube,True,False,https://i.ytimg.com/vi/GALDe3pyq48/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=GALDe3pyq48
4974,3tzvP_ZPReg,[B tv 영화 추천/movie Big #20] 오션스 8 vs 도둑들,UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,"[B tv 영화 추천/movie Big #20] 오션스 8(Ocean's 8 , 2...",2018-07-26T09:14:19Z,"SK브로드밴드, SKB, B tv, movie Big, 백업무비, 버킷무비, 무비빅...",1,376,1.0,0.0,PT17M27S,hd,youtube,True,False,https://i.ytimg.com/vi/3tzvP_ZPReg/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=3tzvP_ZPReg
5300,sBM4pxyiXg4,"[B tv 영화 추천] 아토믹 블론드 (Atomic Blonde , 2017)",UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,[영화로운 세상] 웰컴 투 무비 - 아토믹 블론드,2017-10-25T07:00:02Z,"SK B tv, B tv, 비티비, 아토믹 블론드, Atomic Blonde, 영화...",1,544,3.0,0.0,PT3M51S,hd,youtube,True,False,https://i.ytimg.com/vi/sBM4pxyiXg4/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=sBM4pxyiXg4
5308,oUAP9Z8X_Ew,"[김태훈의 무비셀렉션] 윈드 리버 (Wind River , 2016)",UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,[영화로운 세상] 무비 셀렉션 - 윈드 리버,2017-10-22T04:00:01Z,"SK B tv, B tv, 비티비, 윈드 리버, Wind River, 영화추천, 추...",1,2092,15.0,0.0,PT8M7S,hd,youtube,True,False,https://i.ytimg.com/vi/oUAP9Z8X_Ew/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=oUAP9Z8X_Ew
5527,qchTQoMeGME,"[B tv 영화 추천] 재심 (New Trial, 2016)",UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,[영화로운 세상] 지혜로운 태용씨 - 재심,2017-04-13T03:27:20Z,"SK B tv, B tv, 비티비, 재심, 정우, 강하늘, 김해숙, 이동휘, 한재영...",1,521,5.0,0.0,PT12M10S,hd,youtube,True,False,https://i.ytimg.com/vi/qchTQoMeGME/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=qchTQoMeGME
5879,Emq8naf4RlM,이번 주 뭘 볼까? 영화 '님아 그강을 건너지 마오',UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,"우리는 76년째 연인입니다.\n89세 소녀감성 강계열 할머니, 98세 로맨티스트 조...",2015-02-13T10:01:08Z,"SK B tv, B tv, 비티비, 영화 추천, 님아 그강을 건너지 마오",24,6445,15.0,0.0,PT7M49S,hd,youtube,True,False,https://i.ytimg.com/vi/Emq8naf4RlM/hqdefault.jpg,360,480,True,error,https://www.youtube.com/watch?v=Emq8naf4RlM
7464,twRn4exv0Z8,if(kakao)2020 / 비즈니스. 톡처럼 쉬워지다.,UCBjvBJgIp3NGkrTBEfWBUVw,카카오,https://if.kakao.com\n카카오가 여러분의 비즈니스를 쉽게 성장시킬 ...,2020-11-19T04:00:05Z,NaN,22,1757,16.0,1.0,PT16M1S,hd,youtube,True,False,https://i.ytimg.com/vi/twRn4exv0Z8/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=twRn4exv0Z8&pp...
15474,KkcKEYLIblw,"밍찌니, 문도 피구 판 떠나라",UCMaDyFlagYlsolLLfWHu7Dw,숲 (SOOP),밍찌니♥ : https://bj.afreecatv.com/mjinhee\n\n아프리...,2021-11-02T09:00:52Z,"아프리카TV, AfreecaTV, BJ, 비제이, 먹방, Mukbang, 생방송, ...",20,842,NaN,0.0,PT2M28S,hd,youtube,True,False,https://i.ytimg.com/vi/KkcKEYLIblw/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=KkcKEYLIblw
17243,L_DiGKiEfiw,"리니지2 레볼루션, 수요공썰전 시즌5 2회, 난닝구출연 #1",UCMaDyFlagYlsolLLfWHu7Dw,숲 (SOOP),아프리카TV - http://afreecatv.com\nYouTube - https...,2018-02-01T06:57:24Z,"아프리카, 아프리카TV, AfreecaTV, BJ, 비제이, 생방, 녹방, 게임, ...",20,300,NaN,0.0,PT1H2S,hd,youtube,True,False,https://i.ytimg.com/vi/L_DiGKiEfiw/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=L_DiGKiEfiw
17258,CnslQ6NuQpo,[곽방TV]최초의 반려동물은 어떻게 탄생했을까? - 길들이기 특집 #1,UCMaDyFlagYlsolLLfWHu7Dw,숲 (SOOP),아프리카TV - http://afreecatv.com\nYouTube - https...,2018-01-30T09:37:05Z,"아프리카, 아프리카TV, AfreecaTV, BJ, 비제이, 생방, 녹방, 게임, ...",20,242,NaN,0.0,PT1H2S,hd,youtube,True,False,https://i.ytimg.com/vi/CnslQ6NuQpo/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=CnslQ6NuQpo
17533,RXSZ3vsvJGw,"티버누나, 우유로 라면 끓여먹기? [아프리카TV 핫동]",UCMaDyFlagYlsolLLfWHu7Dw,숲 (SOOP),아프리카TV - http://afreecatv.com\nYouTube - https...,2017-08-24T09:00:02Z,"아프리카, 아프리카TV, AfreecaTV, BJ, 비제이, 생방, 녹방, 게임, ...",20,1438,NaN,0.0,PT7M40S,hd,youtube,True,False,https://i.ytimg.com/vi/RXSZ3vsvJGw/hqdefault.jpg,360,480,False,error,https://www.youtube.com/watch?v=RXSZ3vsvJGw

---
### 2차 필터링
- 
---

In [53]:
food_redirect = food_redirect[food_redirect['upload_date'] >= '2021-07-13']

In [57]:
counts = food_redirect.groupby('channel_id')['verdict'].value_counts()

valid_channels = counts[counts >= 100]

valid_channels
# reset_index()['channel_id'].value_counts()

channel_id                verdict
UC-9HdRV-OzriZ1Q09bT304w  longform    136
                          shorts      106
UC-WFvgdXXmZPj4pDI8GFbzQ  shorts      165
                          longform    101
UCC3eqZIo6lqZQQAN9MO0LQA  shorts      414
                          longform    320
UCDjdk0ufvcvV08hAm_vF06Q  longform    122
UCDryA2PIGnbs9NYn_63rISw  shorts      147
UCEKRI0fipK4LEgV98nI2CQA  longform    117
UCFXwXfbr4b1HHl-YKCOaydA  longform    297
                          shorts      251
UCG_gfzGVpsxGwYuFgH8-tNA  longform    130
UCGgQBs1IgNkwMYbnu26S1yg  longform    183
                          shorts      129
UCGmLtNZFTL6PiKsz3Vpdgbw  longform    136
UCHvCHuXTg6yfQQ1QCeDQMLg  shorts      256
                          longform    130
UCOV_BpGzvmH7ZtjQOWg0bSQ  longform    125
UCSQ0lVqv57JVw1lOdJ2vTVA  shorts      476
                          longform    130
UCUQhyOLi8uFTmiFRmndjQxw  longform    156
UCaxvyTYdWaDXupmgj5ttDUQ  shorts      459
                          longform    180
UCbyV_HczPmqn2LthdcBIl2Q  longform    102
UCfv1dkNKCFUtZouvp3DhS3g  shorts      162
                          longform    108
UCl0HemfAt7dShJRf59_cuGQ  shorts      707
                          longform    351
UCmvqXRPTfMgkKF3MFWylMqQ  longform    177
UCpvT-53Ki7d9Z0PWKC6fGOA  longform    174
UCsM07dUwo0WOWhFbVsG8K6A  shorts      554
                          longform    416
UCs_L1_g_MeTHhuRhJEkF_xA  longform    100
UCt0Pnki9ZDDYx6auEtClYLQ  longform    183
                          shorts      157
UCy85dXvlDH-9H9puNRRGuxA  longform    278
UCzCxSb_RYZuaiaP3u9QNR_A  longform    210
                          shorts      136
UCzGara7SUTKXruclCD4eA5g  longform    427
                          shorts      205
UCzGbclHB9ZcrbcV4qg11C1A  shorts      112
UCzKFT7cBIKO9Dapikf6e3ow  longform    143
Name: count, dtype: int64

In [55]:
it_redirect = it_redirect[it_redirect['upload_date'] >= '2021-07-13']

counts = it_redirect.groupby('channel_id')['verdict'].value_counts()

valid_channels = counts[counts >= 100]

len(valid_channels.reset_index()['channel_id'].value_counts())

12

In [ ]:
# =======================================================================
# 채널 2차 필터링
# 1. 쇼츠 서비스 시작일 이전 데이터 제거
# 2. 롱폼, 쇼츠 개수 각 00개씩 제한
#  
# =======================================================================

def channel_second_filtering(data):
    # ==============================================
    # 1. 쇼츠 서비스 시작일 이전 데이터 제거
    # ==============================================
    data = data[data['upload_date'] >= '2021-07-13']
    
    # ==============================================
    # 2. 롱폼 00개 미만, 숏폼 00개 미만인 채널 제거
    # ==============================================
    # 
    counts = data['verdict'].value_counts()

In [ ]:
food_video_info['upload_date'] = pd.to_datetime(food_video_info['upload_date'], errors='coerce', format='mixed')
it_video_info['upload_date'] = pd.to_datetime(it_video_info['upload_date'], errors='coerce', format='mixed')