In [3]:

# ========================================
# 필요한 라이브러리를 불러옵니다
# ========================================

import os
import time
import platform
from pprint import pprint
from typing import List, Literal, Optional

import requests
import json
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from pydantic_ai import Agent, ModelRetry
from pydantic_ai.models.google import GoogleModelSettings

# 운영체제별 한글 폰트 설정
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'NanumGothic'

# 마이너스 기호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

# 출력 짤림 방지
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 50)

# .env 파일에서 API 키 로드
load_dotenv()
api_key = os.getenv('GEMINI_API_KEY')
gemini_model = os.getenv('GEMINI_MODEL', 'gemini-3.1-flash-lite-preview')
youtube_api_key = os.getenv('YOUTUBE_API_KEY')

# PydanticAI는 GEMINI_API_KEY 환경변수를 자동으로 인식합니다
# 모델 ID 형식: 'google-gla:{모델명}'
model_id = f'google-gla:{gemini_model}'

# API 키 유효성 검사
api_key_valid = api_key and 'YOUR_API_KEY' not in api_key
print(f"API 키 설정 확인: {'O' if api_key_valid else 'X'}")
if not api_key_valid:
    print("[주의] .env 파일에서 GEMINI_API_KEY를 실제 API 키로 설정해주세요!")
print(f"모델 확인: {model_id}")

youtube_api_key_valid = youtube_api_key and 'YOUR_API_KEY' not in youtube_api_key
print(f"유튜브 API 키 설정 확인: {'O' if youtube_api_key_valid else 'X'}")
if not api_key_valid:
    print("[주의] .env 파일에서 YOUTUBE_API_KEY를 실제 API 키로 설정해주세요!")

# API 호출 간격 (초) - 무료 플랜에 맞게 조정
API_DELAY = 3

API 키 설정 확인: O
모델 확인: google-gla:gemini-3.1-flash-lite-preview
유튜브 API 키 설정 확인: O

In [4]:

# =============================================================
# IT 기업리스트
# 생성된 데이터 프레임: it_channel_list
# 생성된 csv 파일 이름: IT채널정보조회.csv
# =============================================================
with open('./data/checkpoint_IT(배치처리).json', encoding='utf-8') as f:
    it_data = json.load(f) # Ai Agent가 정리한 IT기업의 채널 리스트 로드

it_records = [] # 데이터를 담을 빈 리스트 생성

# channels에 들어있는 dict 확장
for company in it_data:
    company_name = company['company_name']
    has_official = company['has_official']
    
    for ch in company['channels']:
        it_records.append({
            'company_name': company_name,
            'has_official': has_official,
            'channel_id': ch.get('channel_id'),
            'channel_name': ch.get('channel_name'),
            'channel_handle': ch.get('channel_handle'),
            'channel_url': ch.get('channel_url'),
            'channel_reason': ch.get('channel_reason')
        })

it_channel_list = pd.DataFrame(it_records)
it_channel_list.to_csv('./data/IT채널정보조회.csv')
it_channel_list.head()

# =============================================================
# 작성된 기업 리스트를 기반으로 수기로 하나하나 검증 중 . . .
# 완료!
# ============================================================= 

# 기업 채널 리스트 가져오기
it_channel_list2 = pd.read_csv('./data/IT리스트 정리.csv', encoding='euc-kr')

# 채널이 없는 기업 제외
it_channel_list2 = it_channel_list2.loc[it_channel_list2['channel_name'].notna(), ['company_name', 'channel_name', 'channel_id', 'channel_handle']]

# 정리된 채널 개수 확인
print('정리된 기업 채널 개수 :' , len(it_channel_list2['company_name']), '개')

정리된 기업 채널 개수 : 49 개

In [5]:

# =============================================================
# FOOD 기업리스트
# 생성된 데이터 프레임: food_channel_list
# 생성된 csv 파일 이름: FOOD채널정보조회.csv
# =============================================================

with open('./data/checkpoint_FOOD(배치처리).json', encoding='utf-8') as f:
    food_data = json.load(f) # Ai Agent가 정리한 FOOD기업의 채널 리스트 로드

food_records = [] # 데이터를 담을 빈 리스트 생성

# channels에 들어있는 dict 확장
for company in food_data:
    company_name = company['company_name']
    has_official = company['has_official']
    
    for ch in company['channels']:
        food_records.append({
            'company_name': company_name,
            'has_official': has_official,
            'channel_id': ch.get('channel_id'),
            'channel_name': ch.get('channel_name'),
            'channel_handle': ch.get('channel_handle'),
            'channel_url': ch.get('channel_url'),
            'channel_reason': ch.get('channel_reason')
        })

food_channel_list = pd.DataFrame(food_records)
food_channel_list.to_csv('./data/FOOD채널정보조회.csv')
food_channel_list.head()

# =============================================================
# 작성된 기업 리스트를 기반으로 수기로 하나하나 검증 중 . . .
# 완료!
# ============================================================= 

# 기업 채널리스트 가져오기
food_channel_list2 = pd.read_csv('./data/Book(실제 검증 채널).csv', encoding='utf-8-sig')

# 채널이 없는 기업 제외
food_channel_list2 = food_channel_list2.loc[food_channel_list2['channel_name'].notna(), ['company_name', 'channel_name', 'channel_id', 'channel_handle']]

# 정리된 채널 개수 확인
print('정리된 기업 채널 개수', len(food_channel_list2['company_name']), '개')

정리된 기업 채널 개수 70 개

In [6]:
# =============================================================
# 채널 정보 불러오기 API : get_channel_info(arg1, arg2, arg3, arg4)
# arg1: 채널 정보를 불러올 때 사용할 유튜브 API키 입니다. (필수)
# arg2: 정보를 불러올 채널의 핸들명 입니다. (arg2, arg3 중 하나만 선택 입력)
# arg3: 정보를 불러올 채널의 핸들명 입니다. (arg2, arg3 중 하나만 선택 입력)
# arg4: 채널의 정보를 담을 리스트 변수명 입니다. 함수가 동작되기 전에 미리 생성되어 있어야 합니다.
# 
# [불러올 정보]
# 1. 채널 아이디(channel_id): 채널이 가지고 있는 고유 아이디 값입니다.
#   - 이후에 유튜브 검색 API 함수에서 쓰입니다. (채널 별 영상 아이디를 가져올 거임)
# 2. 채널 이름(title): 불러올 채널의 이름입니다.
# 3. 채널 설명(description): 채널에 대한 설명입니다.
# 4. 구독자 수(subscriber_count): 채널의 구독자 수입니다.
# 5. 총 조회수(view_count): 채널 모든 영상의 조회수를 합한 값입니다.
# 6. 총 영상수(video_count): 채널이 업로드한 공개된 영상의 개수입니다. (비공개 영상 포함 X)
# 7. 채널 썸네일(thumbnails): 채널의 썸네일입니다. url형식으로 제공됩니다.
# 8. 채널 개설일(created_date): 채널의 개설 날짜입니다.
# 
# 사용할 API: 유튜브 채널 API
#   - 비용: 채널 1개 당 1 유닛
#
# ※ 주의사항
#   - 이 함수는 handle의 리스트나, channel_id의 리스트를 받아서 한꺼번에 출력할 수 없습니다.
#   - 따라서 handle, channel_id는 함수에 한개씩만 들어가야 합니다. (리스트 넣지 말라는 얘기입니다.)
#   - 여러 개의 기업 채널에 대해서 정보를 얻고 싶다면, 반복문 속에 함수를 넣으십시오.
#   - 이 함수는 사용한 유닛량을 알려주지 않습니다. 정보를 얻고자 하는 채널의 수와 유닛량이 같다는 점을 참고해주십시오.
# =============================================================

def get_channel_info(api_key, handle=None, channel_id=None, list_name=None):
    url = 'https://www.googleapis.com/youtube/v3/channels'
    
    params = {
        'part': 'snippet,statistics,brandingSettings',
        'key':api_key
    }
    
    if handle:
        params['forHandle'] = handle
    elif channel_id:
        params['id'] = channel_id
    else:
        raise ValueError('handle 또는 channel_id 중 반드시 하나는 입력해야 합니다.')
    
    if list_name == None:
        raise ValueError('채널 정보를 받을 리스트를 입력해주세요')
    r = requests.get(url, params=params, timeout=30)
    r.raise_for_status()
    data = r.json()
    
    if not data.get('items'):
        return None
    ch = data['items'][0]
    temp ={
        'channel_id': ch['id'], # 채널 아이디
        'title': ch['snippet']['title'], #채널 이름
        'description': ch['snippet'].get('description'), #채널 설명
        'subscriber_count': ch.get('statistics', {}).get('subscriberCount'), # 구독자 수
        'view_count': ch.get('statistics',{}).get('viewCount'), # 채널 총 조회수
        'video_count': ch.get('statistics',{}).get('videoCount'), #채널 총 영상 수
        'thumbnails': ch['snippet'].get('thumbnails').get('default').get('url'), # 채널 프로필 사진?
        'created_date': ch['snippet'].get('publishedAt') # 채널 생성 날짜
    }
    list_name.append(temp)
    return list_name

---
#### 채널 정보 수집
   수집 목적:
   1. 채널 정보를 분석하여 사용할 최종 채널 리스트를 선정하기 위함.
   2. 이후 영상정보 검색시 채널 id 정보가 필요.

---

In [8]:
# =============================================================
# 남은 토큰 관리를 위한 남은 토큰 수 입력
#   - https://console.cloud.google.com/iam-admin/quotas?hl=ko
#   - youtube api 키와 연결된 프로젝트 선택
#   - 서비스 Youtube Data API v3의 현재 사용량 확인.
#   - 
# =============================================================
print('API 사용량 확인: https://console.cloud.google.com/iam-admin/quotas?hl=ko')
total_unit = 10000 - int(input('이미 사용하신 사용량을 입력해주세요. 예) 256 :',))
print('현재 남은 유닛 수 :', total_unit)

API 사용량 확인: https://console.cloud.google.com/iam-admin/quotas?hl=ko
현재 남은 유닛 수 : 9710

In [9]:
# =============================================================
# IT 기업의 유튜브 채널 정보 수집 시작
# =============================================================
it_handle_list = it_channel_list2['channel_handle'].to_list() # 정제된 IT 채널 리스트를 가져옴

print('='*50)
print('현재 남은 유닛 수 :', total_unit)
print('사용 예정 유튜브 API 유닛 :', len(it_handle_list), 'units')

it_list = [] # it 채널의 정보를 담을 리스트 생성
unit= 0 # 유닛 수 계산 시작!
for handle in it_handle_list:
    get_channel_info(youtube_api_key, handle=handle, list_name=it_list)
    unit += 1
total_unit = total_unit - unit
print()
print('실제 사용된 유튜브 API 유닛: ', unit, 'units')
print('남은 유닛 수: ', total_unit)
print('='*50)

# IT 채널 정보 리스트 데이터프레임으로 변환
it_channel = pd.DataFrame(it_list)
print()
print('수집 결과:')
display(it_channel)
# csv로 저장
it_channel.to_csv('./data/IT채널정보조회.csv', encoding='utf-8-sig')

==================================================
현재 남은 유닛 수 : 9710
사용 예정 유튜브 API 유닛 : 49 units

실제 사용된 유튜브 API 유닛:  49 units
남은 유닛 수:  9661
==================================================

수집 결과:

,channel_id,title,description,subscriber_count,view_count,video_count,thumbnails,created_date
0,UCA5vKQkvC9zlTDOSNtoMdCQ,SK telecom,SK telecom 공식 YouTube 채널,1130000,1312523551,2705,https://yt3.ggpht.com/ytc/AIdro_m_9Gd-5ejb35YE...,2011-01-12T06:00:00Z
1,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"AI NOW & NEXT\n오늘날 AI로 이룬 혁신을 경험하고, 내일의 도약을 위한...",5320,192278,324,https://yt3.ggpht.com/BUovhY65Fkq3930DuKeBjwJB...,2022-08-04T08:01:36.337173Z
2,UCp3BSINVC7Ggj4kChEUiy7Q,LG유플러스 (LG Uplus),LG U+ 공식 Youtube 채널 \n,660000,1940089154,3713,https://yt3.ggpht.com/MXGutyn0ZJqNgLb5bPGj514z...,2011-12-19T07:47:10Z
3,UCVaIGU8ch9zG42j-rAG6VoA,삼성SDS,AI 풀스택 역량으로 기업의 AX를 선도하는 업무 혁신 파트너\n삼성SDS 공식 Y...,43200,74702371,1137,https://yt3.ggpht.com/v7Jgiy1VlR5ps-jDUHkpnzgf...,2016-10-04T07:31:53Z
4,UCqz8F0bdoDiyzgdYPZAdA-Q,LG CNS,Global AX 전문기업 LG CNS의 공식 유튜브 채널입니다.,76100,68761714,473,https://yt3.ggpht.com/gm9Yi3503swI8kz0XgMxY-xZ...,2012-05-16T04:55:12Z
5,UCwR9k7QggFEfeHkvTR31JcA,SK브로드밴드_B tv,SK 브로드밴드 공식 유튜브 채널입니다\n,75600,178641784,4330,https://yt3.ggpht.com/ojNY0Wvjfp63Lazv7n4DDAOo...,2014-06-20T06:54:37Z
6,UCjyYouHWnID_L4QaQ6U4voQ,네이버 NAVER,네이버 공식 유튜브 채널입니다.,32600,288220674,862,https://yt3.ggpht.com/D-DsROA_yjJi-B1x4nnHXXws...,2012-11-22T12:07:43Z
7,UCBjvBJgIp3NGkrTBEfWBUVw,카카오,일상에 스며든 카카오의 다양한 이야기를 전합니다. 카카오 공식 유튜브 채널.,132000,254314427,910,https://yt3.ggpht.com/SSvyEl7-5J4DlWtbrHfeERIs...,2012-03-26T03:51:31Z
8,UCRBtxwx23bzxyr5R9vFRYhw,현대오토에버,여기는 현대오토에버 공식 YouTube 채널입니다.,10200,3747653,147,https://yt3.ggpht.com/L2QnWR1xkuWsogbZ91hIx6CY...,2019-10-29T05:34:14.878126Z
9,UCqqoiebjYnMqfhx-4f1awKg,Microsoft Korea,Microsoft 목표와 가치는 전세계의 사람과 기업이 잠재력을 최대한 발휘할 수 ...,18600,70527385,1845,https://yt3.ggpht.com/MRNhR0pURHfaJW1zLqGwGc7-...,2011-03-18T07:38:13Z
10,UCcFA2TC568rGp94OqMq3Nig,두나무 (Dunamu),"블록체인 및 핀테크 전문 기업, 두나무의 공식 채널입니다. \nhttps://dun...",151,741555,14,https://yt3.ggpht.com/Ly4SD65RKZXmvnEZsxla7afQ...,2022-11-08T05:33:24.840414Z
11,UCZHb3OEEJ0WkizEH9ErlgvA,Dell Technologies,Welcome to Dell Technologies' official YouTube...,47200,242129008,1199,https://yt3.ggpht.com/FNcLs-Wgkhb7ThCfRl7kg060...,2016-08-05T09:55:02Z
12,UC2wPiIf2xSXGTJNqo8UOY9g,네이버클라우드 l NAVER Cloud,"앞서가는 클라우드의 모든 것, 네이버 클라우드 ☁\n\n네이버 클라우드 플랫폼(NA...",14000,2255621,653,https://yt3.ggpht.com/cThadcW1wOQDycH764qZPBZc...,2017-04-03T09:39:28Z
13,UCwfd3z7HQcVAbwPiZw6JNRw,Synopsys SIG Korea,안녕하세요? 시높시스 SIG (Software Integrity Group) Kor...,5,36,2,https://yt3.ggpht.com/_A2V9syQtxSQfvhEOTwvaqpy...,2023-03-09T06:13:35.629477Z
14,UC7JJk_THjnffYi4xEh54AiQ,Kakao Entertainment,,1190,0,0,https://yt3.ggpht.com/ytc/AIdro_lruG4PSGf43BPi...,2021-01-27T02:45:53.40723Z
15,UCpCNaKju3d8YNq4trfwcJrA,Oracle Korea,오라클은 포괄적이고 총체적으로 통합된 클라우드 애플리케이션과 플랫폼 서비스 스택을 ...,4080,2027055,829,https://yt3.ggpht.com/ytc/AIdro_nNKOlLiApor92J...,2015-01-14T06:55:30Z
16,UCn41TnmQX9Ccswo89wDBiyg,롯데이노베이트,고객의 비즈니스 전환을 선도하는 기업\nBusiness Transformation ...,1170,196407,138,https://yt3.ggpht.com/AVDLd_Vevglh5CJn5RvWF7eQ...,2014-03-14T06:04:29Z
17,UCQNv-1JeNQ9I_xKlLD6QmhA,kt cloud,"대한민국 1등 클라우드, kt cloud의 다양한 서비스 및 기능을 만나보실 수 있...",12300,456435,293,https://yt3.ggpht.com/sG7YOG7DozqJ8EOHsiu7UXZB...,2016-05-02T14:11:28Z
18,UCz-j1tzeMCqvOX0YNkOXIAw,[CJ OliveNetworks] CJ올리브네트웍스,[CJ올리브네트웍스 공식계정]\n디지털 기술과 데이터를 기반으로 공간과 일상의 변화...,1340,242067,103,https://yt3.ggpht.com/LhtEqdwyRd07Dx0IBhMq4yY6...,2019-07-03T23:29:08Z
19,UC6fYG3jaeK2ucyX6YYTWglg,KG이니시스,"1998년 설립된 KG이니시스는 국내 최대 전자지급결제대행업체로, 인터넷쇼핑몰의 결...",106,69701,6,https://yt3.ggpht.com/ytc/AIdro_kfIgc9vuoc0FXf...,2018-07-03T05:44:54Z
20,UCmWvEmIve2QHxqgWXAblahA,KT DS,Cloud와 AI 전문 SW 기업 (주)케이티디에스 입니다.,1480,389414,190,https://yt3.ggpht.com/olq2Fy4DoLFb5H-q3z0lqLaz...,2023-01-19T02:33:34.10329Z
21,UCDT2efYTZ8y516QjrfsDQSA,SHINSEGAE I&C,리테일 산업에 IT기술을 더하면? 신세계아이앤씨의 쉽고 재미있는 리테일테크 스토리를...,943,916857,69,https://yt3.ggpht.com/4z9k0juEyoYK2y6mEGBdUXIS...,2019-12-03T04:33:05.124289Z
22,UCXyGqs4y58arFQ6uBduhnsQ,DB Inc.솔루션사업그룹,,3,164,3,https://yt3.ggpht.com/ytc/AIdro_n6uXwQUZQrJSqg...,2024-05-15T23:09:31.716094Z
23,UCQ2qPELH8lcS-jRi4o-GR5Q,번호안내 114,"대한민국 전화번호를 책임지는! 언제 어디서나, 02-114입니다. 24시간 365일...",85,9770,15,https://yt3.ggpht.com/ytc/AIdro_kvohxUiVMaOwCe...,2018-10-19T01:46:03Z
24,UCgtGQjfrfO_uAnH6JcB1MTA,ETEVERS GROUP 에티버스그룹,에티버스그룹의 공식 유튜브 채널입니다!\nChallenge for Transform...,1280,487127,272,https://yt3.ggpht.com/h2DsgPMiz6WnuvglKVbnjmC0...,2020-05-08T01:34:56.568369Z
25,UCK08M2075Y5TOIc8l0aNIQA,LINE KOREA,,13600,15185509,90,https://yt3.ggpht.com/ytc/AIdro_mH3OZn6rdemCEQ...,2014-02-07T05:25:38Z
26,UCtY-kbAYmWfVOqunQv2Wp3w,나이스페이먼츠,,5,524,1,https://yt3.ggpht.com/ytc/AIdro_l3Bz6doyOqmxnb...,2021-11-10T03:14:52.996109Z
27,UCNucE-FsBf3RITeGbsE3RKw,kt is,Total Marketing Service & Biz Support 기업,67,9766,14,https://yt3.ggpht.com/ytc/AIdro_lptnEMC_bj6-pd...,2021-03-22T07:06:20.131511Z
28,UCsdkfl1-goECoNJUp4aMJ7Q,세무신고는 이지샵,,3990,3328170,243,https://yt3.ggpht.com/ytc/AIdro_lFvIK3fB62-3O7...,2014-11-04T02:04:29Z
29,UCB3YZT-IHFywklzOtnB6GGg,나이스정보통신,"NICE정보통신 공식 YOUTUBE 계정입니다.\nVAN, PG, TAXREFUND...",146,25208,29,https://yt3.ggpht.com/oEENg4-gZgPUiNQmHNY7WKyM...,2019-04-29T04:28:50Z
30,UCh2nkYoiq6hae8ePxaZUgkw,빗썸 Bithumb Official,"당신의 안전한 금융 파트너, 빗썸의 공식 유튜브 채널입니다. \n",70800,34590305,1257,https://yt3.ggpht.com/-wqva-xDJjTdszWMnLKUdPqY...,2017-09-21T12:32:15Z
31,UCuDsOOa9CtAWwv7_rmuL14g,카카오모빌리티,We move life\n우리의 기술로 생활을 움직입니다.\n\n편리한 이동이 가치...,6720,31944157,241,https://yt3.ggpht.com/ZxVtDIbWGLs3vX7B_w-Nfk8C...,2017-10-20T01:13:47Z
32,UCoGxUVOIOxtg2V7HALB5o2A,만나플러스,시간에 가치를 더하는\n만나플러스\n,262,35018,38,https://yt3.ggpht.com/cT6uymMm8tCQcW1gp_XhsCM_...,2022-06-14T04:41:15.428269Z
33,UCm0COQdmdRLN23D4gUK3FAA,코스콤,코스콤 유튜브에 방문해 주셔서 감사합니다.\n코스콤은 코스콤 5.0시대를 맞아 금융...,1740,146644,164,https://yt3.ggpht.com/M2bC3vMUhqveSTADBUfjmb1j...,2019-05-09T08:24:34Z
34,UCsc2G8g0k-H15yYuQQv7AYQ,더존TV,"✨Get Fun, Gain Insight '더존TV'\n모두를 위한 단 하나의 인사...",50500,1918439,162,https://yt3.ggpht.com/5wbT-EEpiUlmmwLlBnITpgv7...,2025-12-24T04:53:18.756064Z
35,UCdc_SRhKUlH3grljQXA0skw,Google Korea,,95100,576419726,628,https://yt3.ggpht.com/wBZS4tfRv4QEQWWmQ2VA9ylW...,2007-08-13T01:46:32Z
36,UCsY3aR2FYK4SbM2tBLksWtQ,다우오피스,"올인원 업무플랫폼, '다우오피스' 공식 유튜브 채널입니다. 😀\n직장인들을 위한 콘...",2370,2636157,600,https://yt3.ggpht.com/MGmllFKya8zvALiBb6qcHCRb...,2014-01-14T06:47:47Z
37,UCSvOg4rSu395lPz6uMqBekw,kt M모바일,190만 고객의 선택! 압도적 1등 알뜰폰 kt M모바일의 공식 유튜브입니다. \n...,12900,50331039,331,https://yt3.ggpht.com/-t9DNlJUQAHs3tlrQg6pW7QD...,2014-11-26T08:59:10Z
38,UCjpcrwZnzmLdSrxVcdZd0cQ,아이티센,세상 모든 서비스에 디지털 가치를 부여하는 IT 선도 기업,1320,273908,148,https://yt3.ggpht.com/9KQ_UqP1Z9nCnk4Yv1XURCfX...,2021-07-21T01:43:33.371158Z
39,UCrdvKtWTpBfOx9kFCQ6aK3A,BizTechi_ERP,Global No.1 Solution SAP를 활용한 기업경영환경의 혁신과 성장을 ...,42,5233,15,https://yt3.ggpht.com/Q_KEZHJjW6Y2F5Yg4Qv6dlHF...,2018-10-29T01:35:44Z
40,UCRGEUnlW_qBi3ZDohvP-ylQ,농협정보시스템,농협정보시스템 공식 유튜브 채널입니다,37,1910,2,https://yt3.ggpht.com/ytc/AIdro_mr-WyPcf2Y4UVf...,2016-09-23T05:45:13Z
41,UCsfezAG3HiKjf7OrYTdNZxg,신한DS_오픈스튜디오,,668,41418,71,https://yt3.ggpht.com/c0zs0JsGxLj0y_XlWCkobGuy...,2020-08-13T06:07:21.048803Z
42,UC8RTcqBjB7I9lD_4l8cmwHg,이테크 클라우드,,79,1110,10,https://yt3.ggpht.com/1lxJgEyL_RkJ_kOL17xq3bJt...,2021-03-22T06:57:28.485546Z
43,UC_7nyGIBuYk6HBBBftbn3kg,NOL,NOL(야놀자) 플랫폼 공식 웹사이트 \n☞ https://nol.yanolja.c...,36600,104509390,152,https://yt3.ggpht.com/LowY7r6RgPTITwWMqM4jzhWN...,2013-05-30T05:27:55Z
44,UCWaLVmBvB2ytgSXvtDBKQiw,미디어로그영화,MediaLog = Media + Dialogue\n영화로 소통하는 미디어로그입니다.,43700,47540673,1108,https://yt3.ggpht.com/ytc/AIdro_l98kiVolj84NPV...,2013-05-13T00:20:01Z
45,UCZHb3OEEJ0WkizEH9ErlgvA,Dell Technologies,Welcome to Dell Technologies' official YouTube...,47200,242129008,1199,https://yt3.ggpht.com/FNcLs-Wgkhb7ThCfRl7kg060...,2016-08-05T09:55:02Z
46,UCMaDyFlagYlsolLLfWHu7Dw,숲 (SOOP),"자유로운 소통, 무한한 연결. SOOP(숲) 공식 채널입니다.\n\nSOOP은 '누...",124000,70765278,5024,https://yt3.ggpht.com/TNh2TiRdXlv6mZPFVWEApllp...,2013-12-05T08:06:12Z
47,UCNUz9CIAlWDtaLWvFWzgsww,티머니,더 편한 이동과 결제를 위한 플랫폼 기업\n티머니(Tmoney) 공식 채널입니다.\n,4420,101041566,209,https://yt3.ggpht.com/4kA3G7zuYn2WkvAYxRnKHh1V...,2013-04-15T05:29:13Z
48,UCsfezAG3HiKjf7OrYTdNZxg,신한DS_오픈스튜디오,,668,41418,71,https://yt3.ggpht.com/c0zs0JsGxLj0y_XlWCkobGuy...,2020-08-13T06:07:21.048803Z

In [38]:
# =============================================================
# 식품 기업의 유튜브 채널 정보 수집 시작
# =============================================================
food_handle_list = food_channel_list2['channel_handle'].to_list() # 정제된 IT 채널 리스트를 가져옴

print('='*50)
print('현재 남은 유닛 수 :', total_unit)
print('사용 예정 유튜브 API 유닛 :', len(food_handle_list), 'units')

food_list = [] # it 채널의 정보를 담을 리스트 생성
unit= 0 # 유닛 수 계산 시작!
for handle in food_handle_list:
    get_channel_info(youtube_api_key, handle=handle, list_name=food_list)
    unit += 1
total_unit = total_unit - unit
print()
print('실제 사용된 유튜브 API 유닛: ', unit, 'units')
print('남은 유닛 수: ', total_unit)
print('='*50)

# IT 채널 정보 리스트 데이터프레임으로 변환
food_channel = pd.DataFrame(food_list)
print()
print('수집 결과:')
display(food_channel)
# csv로 저장
food_channel.to_csv('./data/FOOD채널정보조회.csv', encoding='utf-8-sig')

==================================================
현재 남은 유닛 수 : 9880
사용 예정 유튜브 API 유닛 : 70 units

실제 사용된 유튜브 API 유닛:  70 units
남은 유닛 수:  9810
==================================================

수집 결과:

,channel_id,title,description,subscriber_count,view_count,video_count,thumbnails,created_date
0,UCsM07dUwo0WOWhFbVsG8K6A,CU [씨유튜브],"편의점의 새로운 정의!\n트렌드의 중심, 재미의 기준을 만들지😎✌️""\n매일 새로운...",926000,304665948,1173,https://yt3.ggpht.com/ytc/AIdro_mI4fk2-pjTlfnJ...,2012-06-05T11:33:04Z
1,UCnL1m_iPeN8vX7zFHoB4SYg,테헤란로405,테헤란로405에서 좋은 친구 BGF의 주요 소식을 살펴보세요!\n-\n편의점 CU를...,2120,986429,501,https://yt3.ggpht.com/XgW8KshcFJNgLiN92DYhQ3KQ...,2017-03-03T10:34:35Z
2,UCl0HemfAt7dShJRf59_cuGQ,GS25 l 이리오너라,GS25 공식 유튜브 채널📻\n,1060000,222857797,2581,https://yt3.ggpht.com/AajkhhUfGCTlIBM8YvvfZmWK...,2012-12-26T06:54:54Z
3,UChD4kH8BcI49njXGL5-makg,GS리테일 뉴스룸,GS리테일 뉴스룸 공식 유튜브 채널입니다.\n최신 뉴스와 다양한 소식들을 영상으로 ...,2950,1041915,167,https://yt3.ggpht.com/dRpIX9kTKHJJXBJwtWoyXtBB...,2015-05-18T08:16:28Z
4,UCG_gfzGVpsxGwYuFgH8-tNA,대상 DAESANG,더 많은 것들을 존중의 대상으로 DAESANG\n#Respect for more #...,18500,330712069,254,https://yt3.ggpht.com/UGJpLrZkEdbCDTFulkdMEeaH...,2015-12-10T08:58:42Z
5,UCfv1dkNKCFUtZouvp3DhS3g,대상그룹 DAESANG 디튜브,대상그룹(DAESANG GROUP) 공식 소통 채널\n‘대상주식회사’의 식품 이야기...,10800,5743361,277,https://yt3.ggpht.com/JNGLkJj-SitafANGlfbseU-j...,2020-09-04T01:25:26.250343Z
6,UCDryA2PIGnbs9NYn_63rISw,CJ제일제당,CJ제일제당 공식 유튜브 채널입니다. \n,491000,34921332,204,https://yt3.ggpht.com/ULAliXxe7B5_ysZS8vIsPs18...,2011-01-26T00:52:39Z
7,UCOV_BpGzvmH7ZtjQOWg0bSQ,제당슈만,⭐제당슈만⭐ CJ제일제당이 당신을 🔥슈퍼스타🔥로 만들어 드립니다!\nCJ제일제당의 ...,20900,6641561,216,https://yt3.ggpht.com/Yk3vnP2gHzidyACXSqtTo1LU...,2020-05-15T11:50:40.345514Z
8,UCGmLtNZFTL6PiKsz3Vpdgbw,비비고 (bibigo),bibigo Official YouTube Channel\n\n,88100,275870080,307,https://yt3.ggpht.com/nQgCSi2mTp99T8VaSEH5MVyZ...,2013-04-02T11:37:09Z
9,UCFXwXfbr4b1HHl-YKCOaydA,맛깔스튜디오 by롯데웰푸드,맛있는 거 말고 재밌는 거도 기깔나게 잘합니다.\n롯데웰푸드의 맛깔나는 컨텐츠 제작...,147000,490338723,1311,https://yt3.ggpht.com/LJScwH9HDweKeTnwo8UAMcVd...,2011-11-23T07:54:50Z
10,UCpvT-53Ki7d9Z0PWKC6fGOA,롯데웰푸드 모락모락,모락모락 온기가 느껴지는 \n갓 지은 롯데웰푸드 콘텐츠 한끼🍴 \n,138000,137194931,625,https://yt3.ggpht.com/Emiy4Wt0qQd8VDKpwF_HeQz1...,2013-03-14T00:43:52Z
11,UCaxvyTYdWaDXupmgj5ttDUQ,Starbucks Korea,"""커피 이상의 특별한 경험을 소개합니다""\n스타벅스는 커피를 넘어, 사람과 사람을 ...",178000,58470553,807,https://yt3.ggpht.com/ytc/AIdro_morPijMJBwDTgc...,2007-06-19T23:26:27Z
12,UCbEEgpyRxXd6rbM_xhApb_Q,727스튜디오,Original Contents by STARBUCKS KOREA\n\nⓒ 727S...,125000,15113804,240,https://yt3.ggpht.com/4JG-2UP2kJp_pgaL6Tdxj1_q...,2025-01-14T05:06:10.93402Z
13,UCzGara7SUTKXruclCD4eA5g,농심 nongshim,맛있는 상상이 가득한 농심 공식 유튜브 채널 입니다.,44100,1307811613,1459,https://yt3.ggpht.com/2vDg5LPC9z_lExgRYWCFs6XQ...,2009-06-25T06:18:44Z
14,UCzKFT7cBIKO9Dapikf6e3ow,롯데칠성 LOTTE CHILSUNG,롯데칠성 유튜브 공식 채널입니다. \n다양한 영상 컨텐츠를 소개해 드립니다.\n앞으...,126000,675611211,541,https://yt3.ggpht.com/WopSa_1tJT2lQthlRuak2pwT...,2013-03-12T03:31:37Z
15,UC-WFvgdXXmZPj4pDI8GFbzQ,칠성레이블,칠성사이다가 선사하는 콘텐츠 시리즈!\n\n칠성사이다가 기획한 칠성레이블은\n평범한...,103000,70377149,266,https://yt3.ggpht.com/EBrCDOTLtaagP0mjTvgPgbn6...,2021-12-23T09:19:44.012307Z
16,UCHvCHuXTg6yfQQ1QCeDQMLg,오뚜기 Daily,오뚜기 공식 유튜브 채널(Otoki Official Youtube Channel),76200,227283680,826,https://yt3.ggpht.com/Hz_EJNq4FBpNf_hpOfKVi2yQ...,2012-09-14T01:34:19Z
17,UCGEaz9UlmXmQ2YCEDIAc1iA,ottoginoodle,맛으로 행복한 세상! 오뚜기 라면 이야기에 오신것을 환영합니다.\n\n뚜기네의 재밌...,11600,62499853,250,https://yt3.ggpht.com/ytc/AIdro_kPxov_YKhpPf92...,2011-12-07T01:42:35Z
18,UCSQ0lVqv57JVw1lOdJ2vTVA,이마트24 | ALLDAY HIGHLIGHT,"모든 순간이 하이라이트\nALLDAY HIGHLIGHT, 이마트24\n",144000,75527261,651,https://yt3.ggpht.com/PEHYGu8okwfvvk2-pTRhPmHl...,2020-09-24T00:06:25.081438Z
19,UCmvqXRPTfMgkKF3MFWylMqQ,HITEJINRO,당신의 인생을 더 큰 즐거움과 에너지로 채우는 하이트진로 공식 유튜브입니다.,125000,1281699009,880,https://yt3.ggpht.com/ubxjIFIFMFCCxi1H3Nj-7gTS...,2009-10-29T06:36:25Z
20,UClgbMkn177O0xNOEcR9rtug,하이트진로음료,,2900,48366698,219,https://yt3.ggpht.com/rMCqFHSwiET2uJo-03eJxu3p...,2013-06-20T06:53:57Z
21,UCX0cSM0jY9PmtGZixR75u1g,더반찬,No1. 온라인 푸드마켓 더반찬 \nwww.thebanchan.co.kr,397,618602,51,https://yt3.ggpht.com/ytc/AIdro_lHUOA1q_DPQguZ...,2016-10-18T01:54:59Z
22,UCPz4i66EweVQPddqYq7uULg,서울우유 seoulmilk,서울우유 협동조합의 공식 유튜브입니다.\n\n,15300,98570261,283,https://yt3.ggpht.com/UVN0WEXK3va2ZpEADDFelk8Y...,2010-11-24T02:39:38Z
23,UCs_L1_g_MeTHhuRhJEkF_xA,동원F&B(Dongwon),동원F&B 공식 채널입니다. (Dongwon F&B official )\n,37800,624853047,514,https://yt3.ggpht.com/FH56yK3ukI5SjQysrh9uurmC...,2011-07-11T04:11:05Z
24,UCULxh7_uMrbCn0IR_H1h3fg,동원몰 (dongwonmall),💙동원몰 공식 유튜브 채널💛\n다양한 동원몰 소식은 \n⬇️아래 링크에서 확인⬇️,70,133181,32,https://yt3.ggpht.com/ytc/AIdro_mptxWV4S7R-4st...,2012-01-27T00:43:19Z
25,UCC3eqZIo6lqZQQAN9MO0LQA,동원TV,동원그룹의 최신 소식과 유익한 볼거리가 가득한 곳! 여기는 동원그룹 공식 유튜브 채...,24100,316598561,1045,https://yt3.ggpht.com/JWWnneUCTFTzf5cMguzUzN8b...,2013-04-03T12:52:46Z
26,UCxHML2F6f8c5L7N2-0gF6Vw,삼양그룹,💡생활의 잠재력을 깨우고\n🌐인류의 미래를 바꾸는 \n💙삼양그룹 공식 인스타그램\n...,6900,269315096,354,https://yt3.ggpht.com/TQNeALOjJ4jGXfNJO1SOx6Kf...,2013-04-16T04:48:36Z
27,UClEdrjHVDXEOsll343sECmQ,큐원 알룰로스,"더 나은 달콤함의 시작\nBetter Sweet, One Choice, 큐원 알룰로스\n",17400,4618091,101,https://yt3.ggpht.com/1xOjNkRZWGiJInBBKVlCLEVL...,2015-07-28T05:45:03Z
28,UCMqZKRBemgZ0_1uLT2yAF9w,상쾌환 EASY TOMORROW,,1430,105772923,137,https://yt3.ggpht.com/OBZBKMisqoAWKG0KR_ODg7_R...,2019-01-14T11:34:22Z
29,UCGgQBs1IgNkwMYbnu26S1yg,파리바게뜨TV,놀고 먹는것에 진심인 사람들의 집합체 🍞🥖🥪🍬\n맛있는 즐거움으로 꽉 찬\n파리바게...,24800,150603121,575,https://yt3.ggpht.com/ytc/AIdro_nHRY5WmHpDGQjZ...,2014-06-16T08:46:37Z
30,UClYaslphHkJ3faHzJrU6ZSw,오비맥주,안녕하세요!\n여기는 오비맥주 공식 YouTube 채널입니다.,1500,1520654,35,https://yt3.ggpht.com/ytc/AIdro_nbT41LfpXIHJ-j...,2019-03-22T01:23:30Z
31,UCUQhyOLi8uFTmiFRmndjQxw,카스 CASS,"신선하고 톡 쏘는 맥주, 젊음의 활력과 에너지를 느낄 수 있는 대한민국 젊음의 대표...",83100,237726666,497,https://yt3.ggpht.com/Fufyjor6JyuU3onwTV9QAQkF...,2014-04-21T07:53:11Z
32,UCFRMEa0vlRfrgcQpnryE-TA,한맥 HANMAC,\n100% 국내산 고품질 쌀로 완성한\n상쾌한 풍미의 코리안 테이스트\n\n한국인...,932,62935061,94,https://yt3.ggpht.com/NoNVNCOHFoS2ViM-c9ZOK5ke...,2020-08-13T02:24:17.881209Z
33,UCowoImtEdqWGyBIRqt6L2dw,Stella Artois Korea,스텔라 아르투아 공식 유튜브 채널입니다. 음주는 책임있게. \n\t\n* 본 페이지...,5180,54930922,176,https://yt3.ggpht.com/1EBgazONM_RXFamXWm9li8Lp...,2015-06-08T07:48:24Z
34,UC-9HdRV-OzriZ1Q09bT304w,BUDWEISER KOREA,버드와이저 공식 유튜브 채널입니다. 음주는 책임있게.\n\n* 본 페이지의 콘텐츠는...,20800,58809550,431,https://yt3.ggpht.com/CDJxXuduCEMnjjIImQwE7KT2...,2017-06-03T10:08:46Z
35,UCOx-g_rEMW3oD8g-bQaLWkQ,Hoegaardenkr,도심 속에서 호가든을 느끼다.\n호가든에 오신 걸 환영합니다 🌿\n\n𝗪𝗲𝗹𝗰𝗼𝗺𝗲...,793,11091977,137,https://yt3.ggpht.com/xO6pBYAofv02TIlnLbWa4Rsv...,2018-09-11T09:56:45Z
36,UCYPk6gQRP0W2ApSem8qsW2g,구스아일랜드,구스아일랜드 공식 유튜브 채널입니다. 음주는 책임있게.\n\n본 페이지의 콘텐츠는 ...,170,3526174,93,https://yt3.ggpht.com/ytc/AIdro_mj0dE9rfy5Sdqs...,2018-09-10T08:48:03Z
37,UCbyV_HczPmqn2LthdcBIl2Q,커피라는 행복 맥심,,35400,913318080,868,https://yt3.ggpht.com/OV9SIS-26rHeYBLxdR2WywK2...,2013-10-03T12:56:18Z
38,UCIAFN5e9KzBu_F3dBDbmmVg,"세상에서 가장 작은 카페, 카누",,3250,347268250,327,https://yt3.ggpht.com/KU-a2Ss17Q113DZAJ-J5YCvG...,2022-12-26T02:15:16.71179Z
39,UCtFDX5H24C2igmDOdAJdS9Q,동서식품 유튜브,,18000,57672020,114,https://yt3.ggpht.com/wmjtHXOFc69OLqGslyT2i5io...,2014-05-21T01:45:41Z
40,UCt0Pnki9ZDDYx6auEtClYLQ,매일유업 | Maeil,매일유업의 공식 Youtube 입니다.,72500,318343678,1024,https://yt3.ggpht.com/XBGVTwpqwFjYd_y3hrEarY3N...,2010-09-03T05:51:06Z
41,UCzGbclHB9ZcrbcV4qg11C1A,셀렉스,"대한민국 1등 단백질, 셀렉스 공식 유튜브 채널입니다.\n",118000,69307312,171,https://yt3.ggpht.com/vBgT4prOdblpX9cSvjB8SyhD...,2022-03-18T07:03:41.518059Z
42,UC88W-nkd_7G9S7u-2xlX4DQ,삼립,보기만 해도 빵🥖빵🍞 터지는 삼립 공식 유튜브,4330,53101880,204,https://yt3.ggpht.com/LK3-fEwOU_YzesUxIH-ZsxFK...,2017-03-28T07:16:12Z
43,UCiyg3rAdPOJN4eKAgAs5FOQ,SPC그룹,"일상을 맛있게 행복하게, Happiness in every bite\n",5570,7620085,413,https://yt3.ggpht.com/xx8ZYgZxHElh9Sd3Gh-2nNPL...,2016-12-23T06:27:54Z
44,UCzCxSb_RYZuaiaP3u9QNR_A,Coca-Cola Korea,Real-Magic 코카-콜라의 공식 YouTube 채널입니다!,116000,757579888,727,https://yt3.ggpht.com/3gq979lNuPnYbsQJA7ZimgNN...,2011-02-15T09:06:14Z
45,UCC-RQrzmKSAV70txxsdXWqQ,팜스코TV,"(주)팜스코\nBeyond No.1, Everyday with Farmsco\nww...",3520,358834,302,https://yt3.ggpht.com/bnS0qpIZrhDa9CJzfAA-5BCW...,2019-06-12T05:43:11Z
46,UC4xGgCpoPfLHcuPeUbnMibA,사조대림,먹잘알들의 PICK👀\n믿고 먹는 사조대림!\n,1270,47141230,258,https://yt3.ggpht.com/ffn5eGjHgQP90uYCLCG7wZU3...,2022-01-26T05:52:42.197434Z
47,UCEKRI0fipK4LEgV98nI2CQA,버거킹,,51100,410023304,363,https://yt3.ggpht.com/kTGFMGRb__0Rodj-WPawVCFg...,2013-08-13T09:41:34Z
48,UCDjdk0ufvcvV08hAm_vF06Q,투썸플레이스,,82900,137344012,291,https://yt3.ggpht.com/GbVbtd__BYN_kIyMCywMiwYI...,2017-11-30T07:09:02Z
49,UCYnYhuh-L3ApSQ5A-zM3QkQ,빕스VIPS,,889,19818055,81,https://yt3.ggpht.com/MNQZn5AuHOKsis9HAO4T7hbF...,2013-12-30T00:31:01Z
50,UC9Hu-7OguU6HyWaxP_GBYcA,Samyangfoods삼양식품,SQUARE🟧 THE CIRCLE🟠\n불가능의 룰을 깨다\n,17700,282007140,255,https://yt3.ggpht.com/ytc/AIdro_l4o6EV2Hs-eL5p...,2011-05-24T06:31:26Z
51,UCWuIxsTBinJzNf4sQKy7FxA,킴스클럽 공식,,159,269575,60,https://yt3.ggpht.com/CLeokySMmN7wy_IkzkxcnW6T...,2015-11-01T11:22:37Z
52,UCtAHe2OINYIyGOTLDSCzFFg,아웃백 스테이크하우스,"우리들의 PLAYGROUND, 아웃백 그라운드🎈\n",84800,140733408,255,https://yt3.ggpht.com/ytc/AIdro_mdq6uNipbCy7a6...,2011-06-29T05:46:21Z
53,UCqXNBZbGHHS-0nwWvEWXf0A,코레일유통TV,🚄철도 모빌리티 서비스 기업 코레일유통❤️\n,1010,201000,100,https://yt3.ggpht.com/ytc/AIdro_msfYs7VrHQzkW3...,2020-04-02T07:01:42.156416Z
54,UCmSdD90HfUqyR3VNLys03EQ,이랜드이츠,,6,70521,9,https://yt3.ggpht.com/ytc/AIdro_l1Ei_UOn3gRmgf...,2025-01-01T07:51:01.79617Z
55,UCc76iFK6R2u2sqAunMZc8jw,더카페,🔽더카페 성공창업 문의🔽\nhttps://thecaffeopen.com\n\n대기업...,411,1398124,40,https://yt3.ggpht.com/7oCKQYLiGqQS3thAK_1kY1UE...,2022-05-23T07:54:35.677133Z
56,UCvRDrKfRaqYRSBjtj80Q1iQ,KFC Korea,,5110,30089087,174,https://yt3.ggpht.com/Jpt4-yILYIHYiNLqSOYTL2Qz...,2015-10-02T05:43:05Z
57,UCabcfEPMYK0rvbGIl3Gr3Ag,엠즈씨드주식회사,커피전문점 Paul Bassett 공식 YouTube 채널에 오신 것을 환영합니다.,31200,805226,33,https://yt3.ggpht.com/ytc/AIdro_k_6I392knvUBZm...,2015-04-05T14:44:45Z
58,UCbquzcEXtjLAKKlGQ4hLC-w,다담몰,,311,427254,10,https://yt3.ggpht.com/XBovUJb6yUdq4BDKYNTzVbgc...,2021-07-15T02:56:46.101064Z
59,UCrDYPLah4QRsqEZVvWQ6t7g,도미노피자,도미노피자 공식 유튜브 채널입니다.,20200,171090689,287,https://yt3.ggpht.com/_oV6lN8faYGHsjkU5uQVJCzt...,2010-11-29T00:22:40Z
60,UC9_GC5aoZJMz5MAH9e8x9Yg,ENTAS,대한민국 대표 외식문화기업 엔타스\n\n엔타스 그룹은 1991년 창업 이래 꾸준하고...,22,3867,13,https://yt3.ggpht.com/Dtm7uKrRhlF_D8Yc_R18zLQz...,2025-02-13T15:41:10.261329Z
61,UCnMNvrjrdtl_b_5rgvCn21Q,🍦Buza Company🍦,From 🇰🇷 to 🇦🇪🇸🇦🇧🇭🇰🇼🇴🇲 and 🌏\nIntroducing the h...,182,82791,82,https://yt3.ggpht.com/lAJRm9JMzvFiuIzSFUnBN2v7...,2021-08-15T12:39:56.026374Z
62,UCr0W7lsBivPQN5mB2_IntCg,그레인온,,113,4739522,33,https://yt3.ggpht.com/qxt1glZKqzVAyk42Pf-d-VKA...,2023-08-28T06:28:51.294443Z
63,UCuJkoRqYKKCwagZhmz6my-g,gongcha_korea,공들여 더하는 행복 공차.\nhttps://www.gong-cha.co.kr/bra...,14400,30102795,177,https://yt3.ggpht.com/TN6SSFmDwkGEV7UUKaICIR_u...,2016-09-22T04:16:24Z
64,UCy85dXvlDH-9H9puNRRGuxA,유사나헬스사이언스코리아,"유사나는 최고의 과학을 기반으로 개발 하고, 이를 바탕으로 직접 판매를 통해 우수한...",11800,1532455,592,https://yt3.ggpht.com/JnDmz84yPDvCNbWbKubIBjN3...,2013-09-26T16:29:24Z
65,UCvGz1yRdYIyq1wsVrdubFdg,63 스카이라인 다이닝,63 스카이라인 다이닝 공식 채널입니다.\n\n서울의 랜드 마크인 63빌딩에서\n즐...,420,139012,58,https://yt3.ggpht.com/-tf3IeHvN9EpqMASNf_uCdsH...,2020-10-19T02:36:24.92673Z
66,UCIAd6tBRFaU5dVJZflutneQ,CUCHARA_official,"STAY SAFE, STAY HEALTHY\n쿠차라는 신선한 재료로 매일 조리하는 ...",5,1287,4,https://yt3.ggpht.com/sTMC3EdFh7mTN0J7mm1w7LEF...,2021-07-26T06:19:41.020417Z
67,UCcf7JZQJuaxkgxaJvLP5ehw,Amoje food,,66,55085,58,https://yt3.ggpht.com/ytc/AIdro_kwMxDL9vQxTlM2...,2013-06-14T02:46:07Z
68,UCFqPOabewS-V-InoIsilfPg,매드포갈릭 Mad for Garlic,"모두의 다이닝, K-Cultured 이탈리안 레스토랑 '매드포갈릭'의 공식 유튜브 ...",285,1711424,5,https://yt3.ggpht.com/5OeI_1Wlq5As-4U2NOt8lx54...,2015-03-05T08:38:47Z
69,UCkY-OZQGn8e7loIO7Z9wHXQ,강강술래푸드,가정에서도 만나세요.\n강강술래에서 경험했던 맛을 가정에서도 그대로\n느끼실 수 있...,130,30368,67,https://yt3.ggpht.com/1Z0mMbXKodbr_EwaT99vsgjo...,2020-11-09T02:39:34.281239Z

---
#### 채널 선정기준
    - 채널 정보 데이터 EDA를 통해 선정 기준 정립

---

---
#### 채널 영상정보 검색
    - 채널이 가지고 있는 영상의 Video_id를 수집
    - 이후에 진행할 영상 상세정보 불러오기에 사용
---

In [10]:
# =======================================================================
# 채널의 영상정보 불러오기 API : get_search_info(arg1, arg2, arg3, arg4)
# arg1: 채널의 영상정보를 불러올 유튜브 API키 입니다. (필수)
# arg2: 영상정보를 불러올 채널의 채널 ID 입니다. (필수)
# arg3: 가져올 영상정보의 개수입니다.(기본값: 50개)
# arg4: 가져온 정보를 저장할 경로입니다. (필수. 예: save_path = './data/food_youtube_data.csv')
# 
# [불러올 정보]
# 1. 채널 아이디(chanel_id): 채널이 가지고 있는 고유 아이디 값입니다.
# 2. 영상 아이디(video_id): 영상 고유의 아이디 값입니다.
#   - 이후 영상 상세정보 불러오는 API에서 사용될 예정입니다.
# 3. 리소스 생성 날짜(published_at): 이 함수에서는 영상 업로드 일자를 나타냅니다.
# 4. 영상의 제목(title): 이 함수에서는 영상의 이름을 가져옵니다.
# 5. 영상의 설명(description): 이 함수에서는 영상의 설명을 가져옵니다.
#
# ※ 주의사항
#   - 이 함수는 결과를 파일로 저장합니다.(.csv 파일)
#   - save_path는 필수이므로, 꼭 정의해주셔야 합니다.
#   - 이 함수는 입력한 경로에 동일한 이름의 기존파일 존재 시 원본 파일에 데이터가 추가되는 형식입니다.
# =======================================================================


# 영상 검색 정보 불러오기 API

def get_search_info(api_key, channel_id=None, max_results=50, save_path=None):
    url = 'https://www.googleapis.com/youtube/v3/search'
    
    # 영상의 상세 정보를 담을 리스트 생성
    all_items = []
    next_page_token = None # 처음 데이터 호출할 때는 next_page_token 필요 x
    
    # 경로를 입력했는지 확인
    if save_path == None:
        raise ValueError("저장할 경로를 입력해주세요. 예: save_path = './data/food_youtube_data.csv'")
    
    # 기존 video_id 불러오기
    existing_video_ids = set()
    
    # 해당 경로에 파일이 있다면, video_id를 불러오기.
    if save_path and os.path.exists(save_path): # 해당 경로에 파일이 존재한다면,
        existing_df = pd.read_csv(save_path) # 파일을 불러오고,
        if 'video_id' in existing_df.columns: # video_id라는 컬럼이 그곳에 존재한다면,
            existing_video_ids = set(existing_df['video_id'].dropna().astype(str)) # video_id 결측없이/문자형태로/set(중복 없음, 순서없음, 집합개념) 형태로 가져오기
    
    # 최대 개수에 맞게 동영상 반복 수집하기.
    while len(all_items) < max_results: # item의 개수가 max_results 이상 넘어가게 되면 중지
        params = {
            'part': 'id,snippet',
            'key': api_key,
            'maxResults': 50, # 50개씩 수집
            'type': 'video', # 영상정보만 수집
            'order': 'date', # date: 최신순 / rating: 높은 평점 순 / relevance: 검색어와의 관련성 순 / title: 제목의 알파벳 순 / videoCount: 채널의 총 영상 수 큰 순 / viewCount: 조회수가 높은 순
            # 'publishedAfter': '2020-05-01', # 2020년 5월 1일 이후에 업로드된 영상만 포함
            # 'publishedBefore': '2020-05-01', # 2020년 5월 1일 이전에 업로드된 영상만 포함
            # 'q': '광고영상', # 검색할 검색어/search/list?hl=ko&_gl=1*vc89q6*_up*MQ..*_ga*NjQ5MjA0OTUwLjE3NzY0ODg5MDQ.*_ga_SM8HXJ53K2*czE3NzY0ODg5MDMkbzEkZzAkdDE3NzY0ODg5MDMkajYwJGwwJGgw
            # 'videoCaption': 'any', # any: 자막 사용 가능 여부 상관 없음 / closedCaption:를 지정할 수 있음. 활용 유튜브 공식문서 참고 필요 https://developers.google.com/youtube/v3/docs 캡션이 있는 동영상만 포함 / none: 자막이 없는 동영상만 포함
            # 'videoDuration': 'short', # any: 동영상 길이 상관 없음 / long: 20분 보다 긴 영상만 / medium: 4분 이상 20분 이하 / short: 4분 미만
        }

        # 2번째 루프부터는 next_page_token 생김. param의 pageToken에 할당.
        if next_page_token:
            params['pageToken'] = next_page_token

        # 채널 아이디는 필수 입력 항목이므로 입력 없으면 루프 종료.
        if channel_id :
            params['channelId'] = channel_id
        else:
            raise ValueError('channel_id를 입력해주세요')

        # api 호출
        r = requests.get(url, params=params, timeout=30)
        
        # 오류 발생시 이유
        print(r.url)
        if not r.ok:
            print('status_code:', r.status_code) # 오류코드
            try:
                print('error_json:', r.json()) 
            except Exception:
                print('error_text:', r.text)
            break
        
        # 호출 결과 json형태로 저장
        data = r.json()

        # 불러온 데이터가 존재하지 않으면 루프 종료.
        items = data.get('items', [])
        if not items:
            break
        
        # 종료 플래그 생성
        stop_flag = False
        
        # 50개의 영상 정보 저장
        for ch in items:
            video_id = ch.get('id', {}).get('videoId') # 검색결과에서 영상 아이디 가져오기.
            
            if not video_id: 
                continue # video_id가 없으면 다음 루프로!
            
            video_id = str(video_id) # video_id 문자 형태로 변환하기
            
            # 중복된 video_id가 있다면 중복! -> 중단 또는 건너뛰기
            if video_id in existing_video_ids:
                stop_flag = True
                break
            
            # 영상의 상세정보를 리스트에 추가.
            all_items.append({
                'channel_id': ch.get('snippet',{}).get('channelId'), # 채널 아이디
                'video_id': ch.get('id',{}).get('videoId'), # 영상 아이디
                'published_at' : ch.get('snippet',{}).get('publishedAt'), # 리소스 생성 날짜
                'title': ch.get('snippet',{}).get('title'), # 영상 제목
                'description': ch.get('snippet', {}).get('description') # 영상 설명
            })
            
            # 개수 제한
            if len(all_items) >= max_results:
                break
        
        # stop_flag에 따라 정지 여부
        if stop_flag:
            break
        
        # 다음페이지 토큰 불러오기
        next_page_token = data.get('nextPageToken') # 다음페이지 토큰 저장
        if not next_page_token:
            break # 만약 다음페이지 토큰이 없다면 (마지막 영상까지 수집 완료) 반복문 종료!
    
    # 파일로 저장.
    if all_items:
        new_df = pd.DataFrame(all_items)
    
        if not os.path.exists(save_path): # 만약 해당 경로에 파일이 없다면?
            new_df.to_csv(save_path, index=False, encoding='utf-8-sig') # 새로운 csv로 저장
        else: # 해당 경로에 파일이 있다면?
            new_df.to_csv(save_path, mode='a', header=False, index=False, encoding='utf-8-sig') # 기존 데이터 프레임에 내용 추가 mode='a'가 기존 데이터에 이어붙이는 함수
            
    return all_items

In [43]:
# =======================================================================
# IT 기업 채널의 영상정보 수집 API
# =======================================================================

In [ ]:
# =======================================================================
# FOOD 기업 채널의 영상정보 수집 API
# =======================================================================

---
#### 영상 상세 정보 출력
    - 이제 본 분석에 사용될 영상의 상세 정보를 가져온다.

---

In [28]:
# 영상 상세 정보 불러오기 !

def get_video_info(api_key, video_ids=None, save_path=None):
    
    # 영상 정보 수집 API url 가져오기
    url = 'https://www.googleapis.com/youtube/v3/videos'
    all_results = []
    
    if not video_ids:
        print('video_ids가 없습니다.')
        return pd.DataFrame()
    
    if save_path == None:
        raise ValueError('파일을 저장할 경로를 입력해주세요.')
    
    # 기존 video_id 불러오기
    existing_video_ids = set()
    
    if save_path and os.path.exists(save_path):
        existing_df = pd.read_csv(save_path)
        if 'video_id' in existing_df.columns:
            existing_video_ids = set(existing_df['video_id'].dropna().astype(str)) # video_id 결측없이/문자형/set(중복 없음, 순서없음, 집합개념) 형태로 가져오기
    
    # 중복 제거 & 리스트로 변환
    video_ids = [str(v) for v in video_ids if v] # 만약 영상 아이디가 video_ids에 포함되고, 값이 존재한다면 문자열로 변환된 영상 아이디를 출력 반복
    video_ids = list(dict.fromkeys(video_ids))
    
    # 이미 저장된 video_id 제외
    if existing_video_ids:
        video_ids = [vid for vid in video_ids if vid not in existing_video_ids]
    
    # 불러올 video_id가 없을 때
    if not video_ids:
        print('새로 수집할 video_id가 없습니다.')
        return pd.DataFrame()
    
    for i in range(0, len(video_ids), 50):
        batch_ids = video_ids[i:i+50]
        
        params = {
            'part': 'snippet,statistics,contentDetails,status,paidProductPlacementDetails',
            'id': ','.join(batch_ids),
            'key': api_key
        }
    
        r = requests.get(url, params=params, timeout=30)
    
        if not r.ok:
            print('status_code :', r.status_code)
            try:
                print('error_json :', r.json())
            except Exception:
                print('error_text :', r.text)
            break
        
        data = r.json()
        items = data.get('items', [])
        
        for item in items:
            snippet = item.get('snippet', {})
            statistics = item.get('statistics',{})
            content_details = item.get('contentDetails', {})
            status = item.get('status', {})
            ppl = item.get('paidProductPlacementDetails', {})
            # file_details = item.get('fileDetails', {})
            # processing_details = item.get('processingDetails',{})
            # suggestions = item.get('suggestions', {})
            
            all_results.append({
                'video_id' : item.get('id'), # 영상 아이디
                'title' : snippet.get('title'), # 영상 제목
                'channel_id' : snippet.get('channelId'), # 채널 아이디
                'channel_title' : snippet.get('channelTitle'), # 채널 이름
                'description' : snippet.get('description'), # 영상 설명
                'upload_date' : snippet.get('publishedAt'), # 영상 업로드 날짜
                'tags' : ', '.join(snippet.get('tags', [])), # 영상 키워드 태그 목록
                'category_id' : snippet.get('categoryId'), # 영상의 카테고리 아이디
                'view_count' : statistics.get('viewCount'), # 영상의 조회수(Shorts 영상은 최소 시청조건 없음. 재생 또는 다시보기 시작되는 횟수 반환)
                'like_count' : statistics.get('likeCount'), # 영상에 좋아요를 표시한 사용자 수
                'comment_count' : statistics.get('commentCount'), # 영상의 댓글 개수
                'duration' : content_details.get('duration'), # 영상 길이 (PT#H#M#S 형식)
                'definition' : content_details.get('definition'), # 영상을 고화질로 시청할 수 있는지 여부 (hd, sd 형식)
                'content_rating' : content_details.get('contentRating'), # 다양한 평가 기준에 따라 동영상이 받은 평가
                'kmrb_rating' : content_details.get('contentRating', {}).get('kmrbRating'), # 대한민국 영상물등급위원회(KMRB) 등급(예: 전체 관람가)
                'license' : status.get('license'), # 동영상 라이선스 (creativeCommon: 타인의 영상 재편집, 재배포 가능, 출처 표기 / youtube: 재사용/수정 불가)
                'embeddable' : status.get('embeddable'), # 영상을 다른 웹사이트에 퍼갈 수 있는가?
                'has_paid_product_placement' : ppl.get('hasPaidProductPlacement'), # 유료 PPL이 사용되는 경우 true, 아니면 False
                # 'width_pixels' : file_details.get('videoStream[]', []).get('widthPixels'), # 콘텐츠 가로 너비
                # 'height_pixels' : file_details.get('videoStream[]', []).get('heightPixels'), # 콘텐츠 세로 높이
                # 'aspect_ratio' : file_details.get('videoStream[]', []).get('aspectRatio'), # 콘텐츠 가로세로 비율
                # 'vendor' : file_details.get('videoStream[]', []).get('vendor'), # 동영상 공급업체 코드
                # 'tag_suggestions_availability' : processing_details.get('tagSuggestionsAvailability'), # 동영상에 키워드 추천을 사용할 수 있는지 여부 (동영상을 더 쉽게 찾을 수 있도록 동영상의 메타데이터에 태그 추가 가능.)
                # 'tag' : suggestions.get('tagSuggestions[]', []).get('tag'), # 영상에 추천된 키워드 태그 
                # 'category_restiricts' : suggestions.get('tagSuggestions[]', []).get('categoryRestricts[]'), # 태그와 관련된 동영상 카테고리 집합
                # 'caption' : content_details.get('caption'), # 자막을 사용할 수 있는지 여부(bool)
                # 'thumbnail' : snippet.get('thumbnails', {}).get('high',{}).get('url'), # 영상 썸네일(고해상도)
            })
        
    # 영상정보 결과 데이터 프레임으로 저장
    df= pd.DataFrame(all_results)
    
    # 파일로 저장.
    if save_path and not df.empty: # 경로가 존재하고, 데이터 프레임이 비어있지 않다면,
        os.makedirs(os.path.dirname(save_path), exist_ok=True) if os.path.dirname(save_path) else None
        
        if not os.path.exists(save_path):
            df.to_csv(save_path, index=False, encoding='utf-8-sig')
        else:
            df.to_csv(save_path, mode='a', header=False, index=False, encoding='utf-8-sig')
    return df

In [19]:
test1 = pd.read_csv('./data/test1.csv')
test1

,channel_id,video_id,published_at,title,description
0,UCA5vKQkvC9zlTDOSNtoMdCQ,r44LTGvxHig,2026-04-17T10:04:39Z,[장르만뉴스] 더욱 똑똑해진 에어닷 노트! 일상을 더 편리하게 관리해보세요 🙌,"매일 쌓이는 회의록, 정리 안 된 강의 노트, 떠오를 때마다 적어둔 아이디어들… 어..."
1,UCA5vKQkvC9zlTDOSNtoMdCQ,0aT46-BaIuk,2026-04-14T03:00:08Z,[고객님께 가는 길] SK텔레콤의 고객 경청 프로젝트 with 노홍철,고객님들 덕분에 성장한 SK텔레콤! 고객님을 향한 초심으로 돌아가 한 분 한 분...

In [20]:
# 테스트 2
channel_ids = it_channel['channel_id'].tolist()
channel_id = channel_ids[1]
print(channel_id)
get_search_info(youtube_api_key, channel_id=channel_id, max_results=50, save_path='./data/test2.csv')

UCqi8fAllvDe9-QCDlhxSg8Q
https://www.googleapis.com/youtube/v3/search?part=id%2Csnippet&key=AIzaSyBSpR_KPs9HnEYrDGXS0r_7aHjXyJxXpsI&maxResults=50&type=video&order=date&channelId=UCqi8fAllvDe9-QCDlhxSg8Q

[{'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'oI8lPKD8HQc',
  'published_at': '2025-11-20T06:00:46Z',
  'title': 'The Human Factor : 인간다움을 지키며 AI를 구축하는 방법 | MIT 에릭데이비스',
  'description': 'AI, 단순한 공학적 과제가 아니라 인간 중심 디자인의 영역이기도 합니다. AI가 높은 기대에 부응하고 인류에 이익을 주기 위해서는 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'eY-IZV8Jizg',
  'published_at': '2025-11-20T06:00:40Z',
  'title': '거대 연산망 구현을 위한 CPO 기반 차세대 연결 기술로의 진화 | SK하이닉스 이규상',
  'description': 'Chip 레벨에서 고도화된 협업 구조가 마련되고 있지만, AI 시스템의 물리적 연결 구조는 여전히 성능의 한계 요인으로 작용하고 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': '4wiqhGENzpk',
  'published_at': '2025-11-20T06:00:09Z',
  'title': '나만의 AI Worker, 이제는 직접 만든다. Agent를 만드는 Agentic Platform 명장 AI. | SK AX 문기식',
  'description': '최근 산업 현장에서는 AI 자동화에 대한 수요가 높지만, 현장 전문가의 IT/AI 역량 부족과 복잡한 개발·운영 과정이 도입의 장애물로 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'BPRDY_Z9D_s',
  'published_at': '2025-11-20T06:00:18Z',
  'title': 'AI Readable 데이터와 활용 체계 | SK텔레콤 윤철중',
  'description': 'SK텔레콤은 데이터를 AI가 이해하고 활용할 수 있는 형태로 전환하는 체계와 과정을 구축했습니다. AI Agent가 데이터를 효과적으로 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': '7U-8YszwidA',
  'published_at': '2025-11-20T06:00:14Z',
  'title': '내 AI는 문제가 없을까? AI 상용화의 핵심, 신뢰성 평가 | 셀렉트스타 김세엽',
  'description': 'AI 서비스 개발에는 품질과 안전성을 보장하기 위한 신뢰성 평가가 필수적입니다. Foundation Model은 확률적 동작으로 인해 의도치 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'uZPUplLSSzo',
  'published_at': '2025-11-20T06:00:49Z',
  'title': 'AI를 사회적 공간에 배치하기: SNS와 실사용 환경에서의 모델 적용 실험 | TUNiB 박규병',
  'description': 'AI는 이제 정보 제공이나 생산을 넘어, 사람 간 소통이 이뤄지는 서비스 영역으로 확장되고 있습니다. 특히 감정과 반응이 흐르는 SNS ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': '0RAz4Ge-9YU',
  'published_at': '2025-11-20T06:00:02Z',
  'title': 'Voice LLM 우리는 무엇을 기대하는가? | SK텔레콤 황성수',
  'description': 'Voice LLM 연구는 단순히 모델 구조를 선택하는 문제가 아니라, 목표 설정과 제약 조건 정의가 선행되는 전략적 결정 과정입니다.'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'Kpra7EWOvkM',
  'published_at': '2025-11-20T06:00:16Z',
  'title': '어떤 광고가 돈이 될까? AI 기반 광고 수익 최적화 | SK플래닛 신호준, 윤이연',
  'description': '광고 운영, 이제 AI가 알아서 합니다. OK캐쉬백, Syrup, 오락, T멤버십 등 다양한 서비스에 적용된 Planet AD는 SK플래닛의 지능형 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'Jwrz_qXl0f4',
  'published_at': '2025-11-20T06:00:18Z',
  'title': '핵심업무에 집중하고, 나머지는 AI에게 맡기세요. 일하는 방식의 혁신, A.Biz | SK텔레콤 임세호',
  'description': '최근 효율적으로 업무를 처리할 수 있는 AI 기반 솔루션에 대한 수요가 빠르게 증가하고 있습니다. 하지만 실제 현장에서는 부서/직무 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'iQirlenF19I',
  'published_at': '2025-11-20T06:00:41Z',
  'title': '칩에서 쿨링까지, 열을 다스리는 인프라 전략 | 슈나이더 일렉트릭 이창호',
  'description': 'AI 데이터센터의 고밀도화에 따른 냉각 방식의 변화를 다룹니다. 기존 냉각 방식의 한계를 넘어 리퀴드 쿨링, 특히 칩에 직접 냉각하는 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'jGEJMX0CgTQ',
  'published_at': '2025-11-20T06:00:43Z',
  'title': '차세대 무선망, ‘AI - RAN’ 실현을 위한 핵심 기술 및 연구개발 사례 소개 | SK텔레콤 이상민',
  'description': 'AI는 모든 기술 영역으로 확산되고 있으며, 정교하고 복잡한 무선 통신 기술이 집약된 5G/6G 기지국도 예외가 아닙니다. 기존의 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'QJAZWOp_dDs',
  'published_at': '2025-11-20T06:00:20Z',
  'title': '생성형 AI 추론의 확장: 기술, 최적화, 그리고 실전 교훈 | FriendliAI 유경인',
  'description': '생성형 AI의 도입이 가속화되고 Agentic AI 시스템이 새로운 추론 수요를 만들어내면서, 가장 큰 과제는 프로토타입을 넘어 실제 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'eHkwXyi2ZOc',
  'published_at': '2025-11-20T06:00:40Z',
  'title': '스마트 에너지와 지능형 운영 인프라 | 슈나이더 일렉트릭 이승윤',
  'description': '스마트 센서를 포함한 지능형 전기장치들을 활용하여 기존 전력감시제어 시스템의 기능을 한 단계 진화시킨 디지털 에너지 운영 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'tYaW-LVjeSw',
  'published_at': '2025-11-20T06:00:49Z',
  'title': '안심하고 사용할 수 있는 커뮤니케이션 서비스 진화 방향 | SK텔레콤 조현덕',
  'description': '전화 서비스에서 고객 만족도가 높았던 스팸 필터링은 이제 AI 기술을 기반으로 한 단계 더 진화하고 있습니다. 이번 발표에서는 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'HqBJX53esCc',
  'published_at': '2025-11-20T06:00:24Z',
  'title': '생각하는 기계를 위한 운영체제 | VAST Data Renen Hallak',
  'description': 'AI 데이터 플랫폼 소프트웨어 기업 VAST Data에서 지능적이고 데이터 중심적인 컴퓨팅 시대를 구동하는, 세계 최초의 AI 운영체제(AI ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'mZL0hjQ9pbo',
  'published_at': '2025-11-20T06:00:46Z',
  'title': 'A.X LLM with Reasoning | SK텔레콤 조석환',
  'description': '초거대 AI 경쟁이 가속화되는 가운데 SK텔레콤은 독자적인 Foundation Model A.X를 통해 범용성과 추론력을 갖춘 LLM을 개발해 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'VwE-bIhI_A4',
  'published_at': '2025-11-20T06:00:26Z',
  'title': 'AI x HR : Talent AX가 바꾸는 일과 사람의 미래 | SK AX 김민주',
  'description': 'AI가 HR의 경계를 넘어, 새로운 가능성을 열고 있습니다. Talent AX는 AI와 사람이 공존하는 Hybrid Resource Management System ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': '1lY7kcWTNy4',
  'published_at': '2025-11-20T06:00:01Z',
  'title': '크래프톤에서의 AI Transformation: 일하는 방식과 프로세스의 AI 기반 혁신 | 크래프톤 김도균',
  'description': "생성형 AI와 Agent의 등장은 지식 노동의 문법을 근본적으로 바꾸고 있습니다. 이제 우리는 '어떻게 일할 것인가'를 다시 써야 하는 ..."},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'gGUxpNhxqDU',
  'published_at': '2025-11-20T06:00:27Z',
  'title': 'AX를 넘어 BX로, EXAONE이 만드는 금융 및 제약 산업에서의 사업 대혁신 | LG AI연구원 이화영',
  'description': '생성형 AI의 등장은 수많은 새로운 모델 발표와 함께, 클라우드 기반 API 비즈니스의 확산을 이끌고 있습니다. 그러나 실제 사업적 가치 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'gn0pXvZdg6o',
  'published_at': '2025-11-20T06:00:39Z',
  'title': 'Agentic AI 적용의 첫걸음: 산업별 기회와 실전 가이드 | MakinaRocks 임용섭',
  'description': '생성형 AI의 다음 진화 단계로 주목받는 Agentic AI는 특정 산업과 업무에 맞춘 AI가 판단하고 실행까지 수행함으로써 생산성과 경쟁력 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'Tie_JRjxfUw',
  'published_at': '2025-11-20T06:00:34Z',
  'title': 'VISTA로 보는 새로운 시야 : 고객의 목소리를 AI로 구조화하여 만난 인사이트 | SK브로드밴드 김준형',
  'description': '고객 VoC의 효과적인 사후 분석과 대응을 위해 상담 내역을 기반으로 인사이트와 검색 서비스를 제공하는 플랫폼 VISTA(VoC Insight ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'luk0plb8Urk',
  'published_at': '2025-11-20T06:00:51Z',
  'title': '2025년 LLM 훈련과 서빙의 진화: 하이퍼스케일 AI 플랫폼 Backend.AI의 기술적 도전과 해법 | Lablup 신정규',
  'description': '거대 언어 모델(LLM)의 급속한 진화로 AI 인프라 플랫폼은 전례 없는 복잡성과 도전에 직면하고 있습니다. 특히 2025년은 단일 벤더 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'c2FFh6ZWmpM',
  'published_at': '2025-11-20T06:00:39Z',
  'title': '풀스택 LLM에서 AI 에이전트까지 : 데이터와 자본의 제약을 넘어서기 | 트릴리온랩스 신재민',
  'description': '트릴리온랩스는 작은 스타트업으로서 글로벌에서도 손꼽히는 70B 규모 풀스택 LLM을 from-scratch 방식으로 직접 개발했습니다.'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'MeOh1esbUg8',
  'published_at': '2025-11-20T06:00:20Z',
  'title': 'AI 에이전트, A2A로 일하는 세상 | Persona AI 유승재',
  'description': '젠스테이션(Gen Station)은 A2A 구조 기반의 AI 에이전트 솔루션으로, 300여 개의 다양한 AI 봇을 통해 인사, 회계, 교육, 마케팅 등 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'HLY2cuM1NhA',
  'published_at': '2025-11-20T06:00:25Z',
  'title': 'Physical AI 개발과 도입의 가속화 | Config Intelligence 손형목',
  'description': '곧 출시될 예정인 로봇 데이터·개발 플랫폼 Config Box를 소개합니다. Config Box는 사용자가 정의한 Task를 빠르고 효율적으로 개발 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'b01v2Xa8mNk',
  'published_at': '2025-11-20T06:00:36Z',
  'title': 'Ego-View AI: AI/AR 글라스로 산업을 혁신하는 Multi-Agent 시스템 | SK텔레콤 마춘페이',
  'description': 'AI/AR 글라스의 산업 혁신을 위해서는 복잡한 현장 상황에 대응할 수 있는 멀티 에이전트 시스템이 필수적입니다. SK텔레콤의 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'vlnfDZoC-IA',
  'published_at': '2025-11-20T06:01:01Z',
  'title': 'LLM이 추천을 만나면? SKT의 LLM 기반 추천 시스템 개발기 | SK텔레콤 김태산, 윤형준',
  'description': 'SK텔레콤은 고객 행동 데이터를 활용해 요금제, T-우주 구독 상품, 멤버십, Tworld AI , 에이닷(A.Dot), Tdeal 등 주요 서비스 전반에서 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'WFUwTtbuctc',
  'published_at': '2025-11-20T06:00:36Z',
  'title': '소프트웨어 개발의 AIX, RFP분석에서 시스템 구현까지, SW Dev. AI Agent와 함께 | SK AX 양준기',
  'description': 'SK AX는 기존 인간 중심 소프트웨어 개발이 안고 있던 효율성과 품질 문제를 해결하기 위해 AI와 협업하는 새로운 개발 패러다임, ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'DQvmReiBjSU',
  'published_at': '2025-11-20T06:00:17Z',
  'title': 'AI Agent를 위한 LLM (LARP) 개발과 Sales Agent 도전기 | SK텔레콤 이동헌',
  'description': '단순한 LLM 챗봇을 넘어, 도구를 활용하고 결정을 내리며 복잡한 작업까지 수행하는 AI 에이전트가 주목받고 있습니다. 완성도 높은 AI ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'bB0RRmtQE0o',
  'published_at': '2025-11-20T06:00:36Z',
  'title': 'TelAgentBench - Telco 도메인 사례로 보는 에이전트 성능 평가 | SK텔레콤 이선우',
  'description': 'LLM 기반 Agent가 빠르게 발전하며 통신 서비스에도 적용되고 있지만, 그 성능을 어떻게 측정할 것인지에 대한 명확한 정의는 아직 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'XuXHhPiyGe0',
  'published_at': '2025-11-20T06:00:26Z',
  'title': '미션 크리티컬한 문제에서의 의사 결정에 도움이 되는 AI : 안보, 재난 영역 사례 | S2W 박근태',
  'description': '미션 크리티컬한 문제를 해결하기 위해서는 다양한 데이터를 다각도에서 정교하게 연결하여 정확히 분석하는 것이 필요하고, S2W는 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'c5-quBOPgLw',
  'published_at': '2025-11-20T06:00:28Z',
  'title': '에이전트 월드를 준비하는 에이닷의 현재와 미래 | SK텔레콤 김지훈',
  'description': 'SK텔레콤의 대표 AI 에이전트 에이닷(A.Dot)과 이를 둘러싼 에이전트 사업의 전략과 단계별 변화 방향을 소개합니다. 먼저 전화·음성 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'pvZ7C5TGOL0',
  'published_at': '2025-11-20T06:00:48Z',
  'title': 'AI 인프라, 도전을 넘어 신뢰로 (Cloudflare와 함께하는 DDoS 방어와 데이터 보호의 새로운 기준) | Cloudflare 황성하',
  'description': 'AI 워크로드를 운영하는 데이터센터는 전통적인 공격과 새로운 위협이 동시에 몰려오는 환경에 직면해 있습니다. 이번 발표에서는 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'NykDXfF3wbU',
  'published_at': '2025-11-20T06:00:18Z',
  'title': '모두를 위한 AI 최적화! 경량화에서 추론까지 End-to-End AI 최적화 인프라 플랫폼 ‘NetsPresso’ 기술 소개 | 노타 김태호',
  'description': '노타의 혁신적인 AI 모델 최적화 플랫폼 NetsPresso를 소개합니다. NetsPresso는 모델 설계부터 압축, 추론 최적화, 배포까지 전 과정 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'fuLIi9W08ws',
  'published_at': '2025-11-20T06:00:39Z',
  'title': '오픈소스, 강화학습을 만나다: Helpy의 특화 AI 모델 개발 전략 | Elice 김수인',
  'description': '강력한 오픈소스 모델을 누구나 활용할 수 있는 시대가 되었지만, 특정 도메인에 특화되고 높은 안정성을 요구하는 AI 모델을 개발하는 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': '3ZZIg8gZuyA',
  'published_at': '2025-11-20T06:00:02Z',
  'title': '휴머노이드가 바꾸는 산업 현장! AI 로봇 자동화의 경험적 인사이트로 완성하는 휴머노이드 선행기술 소개 | CMES 김현우',
  'description': 'CMES 휴머노이드 로봇 기술은 다양한 연구 결과들이 선행 기술로 제시되며 빠르게 진화하고 있으나, 실제 산업 현장에 적용하기에는 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': '-LSyy0EwCuE',
  'published_at': '2025-11-20T06:00:00Z',
  'title': 'TMAP AI 모빌리티 데이터로 진화하는 차세대 지능형 교통체계(ITS) | 티맵모빌리티 조형진',
  'description': '2500만명의 티맵 사용자로부터 수집된 방대한 모빌리티 데이터를 AI로 학습·가공하여 기존 인프라 중심의 지능형교통체계(ITS)를 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'oFiJCTFuwlw',
  'published_at': '2025-11-20T06:00:45Z',
  'title': 'MentAI VISION: AI 기반 정신건강 관리 | SK텔레콤 김창현, 정구익',
  'description': '대한민국 정신질환은 심각한 사회적 이슈로 대두되며 정부 차원에서도 대응이 이루어지고 있으나 병원 방문에 대한 심리적 장벽과 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'aJL95Obw6Pw',
  'published_at': '2025-11-20T06:00:01Z',
  'title': '소리 내어 말하는 LLM: AI와의 자연스러운 대화를 위한 음성합성 기술 | SK텔레콤 이준모',
  'description': 'LLM의 전반적 성능 향상으로 다양한 서비스에 빠르게 적용되며 사용자 경험이 크게 향상되고 있습니다. 그러나 대부분의 LLM은 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'tvdCv_-YAhQ',
  'published_at': '2025-11-20T06:00:51Z',
  'title': 'AI Cloud Manager: 국내 최대 B200 GPU 1,000장 클러스터를 Day 0부터 활용하는 법 | SK텔레콤 이주은',
  'description': '초거대 AI 모델 학습 수요가 급증하면서 많은 기업이 대규모 GPU 클러스터 구축과 이를 즉시 활용할 수 있는 AIOps 솔루션 도입을 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'a8WOP2YCrjg',
  'published_at': '2025-11-20T06:00:01Z',
  'title': 'AI 도입 시 마주하는 Legacy Data의 벽: 엔코아가 제안하는 AI Ready Data 확보 방안 | Encore 김범',
  'description': '많은 기업이 AI 도입을 원하지만, 여전히 Legacy 시스템과 데이터의 벽에 가로막혀 어려움을 겪고 있습니다. 엔코아는 수십 년간 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'mFLigW9wVe0',
  'published_at': '2025-11-20T06:00:45Z',
  'title': 'Agentic AI를 통해 바뀌게 될 Car Life의 현재와 미래 | SK텔레콤 윤현상',
  'description': '에이닷에서 자체 개발한 Agentic Workflow를 적용해 한층 똑똑해진 T맵 with A.과, 출시를 앞둔 A.auto 서비스의 특장점과 향후 비전을 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'CfBPWRs7jJU',
  'published_at': '2025-11-20T06:00:10Z',
  'title': '전략적 데이터의 시대:생성형 AI와 합성데이터로 만드는 산업적 전환점 | GenGenAI 조호진',
  'description': '최근 수년간 AI 연구는 눈부신 속도로 발전해 왔으며, Vision Transformer, Multimodal Foundation Model, Diffusion 기반 생성형 AI 등 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'p20BqMHlwoo',
  'published_at': '2025-11-20T06:00:52Z',
  'title': '회의·강의 환경에서도 정확하게: 에이닷노트 음성인식 성능을 끌어올린 Generative AI 전처리 기술 소개 | SK텔레콤 송명석',
  'description': 'AI 기술의 대중화와 함께 음성인식은 단순한 기기 제어를 넘어 업무 효율을 높이는 생산성 도구로 빠르게 확장되고 있습니다. 그러나 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': '3mS4WXYottk',
  'published_at': '2025-11-20T06:00:08Z',
  'title': '전력망부터 칩까지, AI 데이터센터의 시작 | 슈나이더 일렉트릭 이진환',
  'description': '유틸리티 그리드(한전 공급 전원)에서 고객의 IT와 기계 부하까지 안정적이고 고품질의 전력 시스템 관리를 위한 최근 전력시스템 설계 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'ZkcahL6V4Ys',
  'published_at': '2025-11-20T06:00:38Z',
  'title': '에너지 분야 응용을 위한 대규모 멀티모달 모델(LMMs) | SK텔레콤 조동연',
  'description': '정밀한 용도에 맞는 신소재 발견은 오랫동안 큰 도전 과제로 남아 있습니다. 인공지능(AI)과 로보틱스가 발전했음에도 불구하고, 실험 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'AKvhfOridVI',
  'published_at': '2025-11-20T06:00:08Z',
  'title': 'AI기반 예측 기술을 통해 내 몸에 맞는 효과적인 항암치료제 찾기 | 임프리메드 임성원',
  'description': '다양한 메디컬 데이터를 기반으로 개발한 머신러닝(ML) 모델들을 통해 환자맞춤형 암치료를 가능하게 함으로써 암환자의 수명을 연장 ...'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'O9K2gNJ2VfQ',
  'published_at': '2025-11-20T06:00:31Z',
  'title': '오프라인 유통 매장에서의 AX 적용 사례 | 신세계아이앤씨 김정언',
  'description': 'AI는 세상을 떠들썩하게 만들고 우리 일상의 풍경을 바꾸고 있지만, 실제 유통 매장에서 매장 혁신을 이끈 사례는 아직 많지 않습니다.'},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': '9e0GRsQu9gc',
  'published_at': '2025-11-20T06:00:19Z',
  'title': '내 반려동물에게도 AI가? 내 펫의 반려 AI, 에이닷 펫 출시 | SK텔레콤 조재혁',
  'description': "AI 기술은 이제 사람을 돕는 영역을 넘어, 다양한 분야로 빠르게 확장되고 있습니다. 그중 '에이닷 펫'은 반려동물의 삶을 더욱 풍요롭게 ..."},
 {'channel_id': 'UCqi8fAllvDe9-QCDlhxSg8Q',
  'video_id': 'HDjp_l8YCi4',
  'published_at': '2025-11-20T06:00:26Z',
  'title': 'Media AI를 경험하는 지금, Enterprise AI Business의 새로운 변화 | SK텔레콤 김계향',
  'description': 'Media AI는 방송국이나 OTT 등 전통적 미디어 산업의 경계를 넘어, 디스플레이 기술을 활용하는 모든 분야의 핵심 역량으로 부상 ...'}]

In [22]:
test2 = pd.read_csv('./data/test2.csv')
test2

,channel_id,video_id,published_at,title,description
0,UCqi8fAllvDe9-QCDlhxSg8Q,oI8lPKD8HQc,2025-11-20T06:00:46Z,The Human Factor : 인간다움을 지키며 AI를 구축하는 방법 | MIT...,"AI, 단순한 공학적 과제가 아니라 인간 중심 디자인의 영역이기도 합니다. AI가 ..."
1,UCqi8fAllvDe9-QCDlhxSg8Q,eY-IZV8Jizg,2025-11-20T06:00:40Z,거대 연산망 구현을 위한 CPO 기반 차세대 연결 기술로의 진화 | SK하이닉스 이규상,"Chip 레벨에서 고도화된 협업 구조가 마련되고 있지만, AI 시스템의 물리적 연결..."
2,UCqi8fAllvDe9-QCDlhxSg8Q,4wiqhGENzpk,2025-11-20T06:00:09Z,"나만의 AI Worker, 이제는 직접 만든다. Agent를 만드는 Agentic ...","최근 산업 현장에서는 AI 자동화에 대한 수요가 높지만, 현장 전문가의 IT/AI ..."
3,UCqi8fAllvDe9-QCDlhxSg8Q,BPRDY_Z9D_s,2025-11-20T06:00:18Z,AI Readable 데이터와 활용 체계 | SK텔레콤 윤철중,SK텔레콤은 데이터를 AI가 이해하고 활용할 수 있는 형태로 전환하는 체계와 과정을...
4,UCqi8fAllvDe9-QCDlhxSg8Q,7U-8YszwidA,2025-11-20T06:00:14Z,"내 AI는 문제가 없을까? AI 상용화의 핵심, 신뢰성 평가 | 셀렉트스타 김세엽",AI 서비스 개발에는 품질과 안전성을 보장하기 위한 신뢰성 평가가 필수적입니다. F...
5,UCqi8fAllvDe9-QCDlhxSg8Q,uZPUplLSSzo,2025-11-20T06:00:49Z,AI를 사회적 공간에 배치하기: SNS와 실사용 환경에서의 모델 적용 실험 | TU...,"AI는 이제 정보 제공이나 생산을 넘어, 사람 간 소통이 이뤄지는 서비스 영역으로 ..."
6,UCqi8fAllvDe9-QCDlhxSg8Q,0RAz4Ge-9YU,2025-11-20T06:00:02Z,Voice LLM 우리는 무엇을 기대하는가? | SK텔레콤 황성수,"Voice LLM 연구는 단순히 모델 구조를 선택하는 문제가 아니라, 목표 설정과 ..."
7,UCqi8fAllvDe9-QCDlhxSg8Q,Kpra7EWOvkM,2025-11-20T06:00:16Z,"어떤 광고가 돈이 될까? AI 기반 광고 수익 최적화 | SK플래닛 신호준, 윤이연","광고 운영, 이제 AI가 알아서 합니다. OK캐쉬백, Syrup, 오락, T멤버십 ..."
8,UCqi8fAllvDe9-QCDlhxSg8Q,Jwrz_qXl0f4,2025-11-20T06:00:18Z,"핵심업무에 집중하고, 나머지는 AI에게 맡기세요. 일하는 방식의 혁신, A.Biz ...",최근 효율적으로 업무를 처리할 수 있는 AI 기반 솔루션에 대한 수요가 빠르게 증가...
9,UCqi8fAllvDe9-QCDlhxSg8Q,iQirlenF19I,2025-11-20T06:00:41Z,"칩에서 쿨링까지, 열을 다스리는 인프라 전략 | 슈나이더 일렉트릭 이창호",AI 데이터센터의 고밀도화에 따른 냉각 방식의 변화를 다룹니다. 기존 냉각 방식의 ...
10,UCqi8fAllvDe9-QCDlhxSg8Q,jGEJMX0CgTQ,2025-11-20T06:00:43Z,"차세대 무선망, ‘AI - RAN’ 실현을 위한 핵심 기술 및 연구개발 사례 소개 ...","AI는 모든 기술 영역으로 확산되고 있으며, 정교하고 복잡한 무선 통신 기술이 집약..."
11,UCqi8fAllvDe9-QCDlhxSg8Q,QJAZWOp_dDs,2025-11-20T06:00:20Z,"생성형 AI 추론의 확장: 기술, 최적화, 그리고 실전 교훈 | FriendliAI...",생성형 AI의 도입이 가속화되고 Agentic AI 시스템이 새로운 추론 수요를 만...
12,UCqi8fAllvDe9-QCDlhxSg8Q,eHkwXyi2ZOc,2025-11-20T06:00:40Z,스마트 에너지와 지능형 운영 인프라 | 슈나이더 일렉트릭 이승윤,스마트 센서를 포함한 지능형 전기장치들을 활용하여 기존 전력감시제어 시스템의 기능을...
13,UCqi8fAllvDe9-QCDlhxSg8Q,tYaW-LVjeSw,2025-11-20T06:00:49Z,안심하고 사용할 수 있는 커뮤니케이션 서비스 진화 방향 | SK텔레콤 조현덕,전화 서비스에서 고객 만족도가 높았던 스팸 필터링은 이제 AI 기술을 기반으로 한 ...
14,UCqi8fAllvDe9-QCDlhxSg8Q,HqBJX53esCc,2025-11-20T06:00:24Z,생각하는 기계를 위한 운영체제 | VAST Data Renen Hallak,AI 데이터 플랫폼 소프트웨어 기업 VAST Data에서 지능적이고 데이터 중심적인...
15,UCqi8fAllvDe9-QCDlhxSg8Q,mZL0hjQ9pbo,2025-11-20T06:00:46Z,A.X LLM with Reasoning | SK텔레콤 조석환,초거대 AI 경쟁이 가속화되는 가운데 SK텔레콤은 독자적인 Foundation Mo...
16,UCqi8fAllvDe9-QCDlhxSg8Q,VwE-bIhI_A4,2025-11-20T06:00:26Z,AI x HR : Talent AX가 바꾸는 일과 사람의 미래 | SK AX 김민주,"AI가 HR의 경계를 넘어, 새로운 가능성을 열고 있습니다. Talent AX는 A..."
17,UCqi8fAllvDe9-QCDlhxSg8Q,1lY7kcWTNy4,2025-11-20T06:00:01Z,크래프톤에서의 AI Transformation: 일하는 방식과 프로세스의 AI 기반...,생성형 AI와 Agent의 등장은 지식 노동의 문법을 근본적으로 바꾸고 있습니다. ...
18,UCqi8fAllvDe9-QCDlhxSg8Q,gGUxpNhxqDU,2025-11-20T06:00:27Z,"AX를 넘어 BX로, EXAONE이 만드는 금융 및 제약 산업에서의 사업 대혁신 |...","생성형 AI의 등장은 수많은 새로운 모델 발표와 함께, 클라우드 기반 API 비즈니..."
19,UCqi8fAllvDe9-QCDlhxSg8Q,gn0pXvZdg6o,2025-11-20T06:00:39Z,Agentic AI 적용의 첫걸음: 산업별 기회와 실전 가이드 | MakinaRoc...,생성형 AI의 다음 진화 단계로 주목받는 Agentic AI는 특정 산업과 업무에 ...
20,UCqi8fAllvDe9-QCDlhxSg8Q,Tie_JRjxfUw,2025-11-20T06:00:34Z,VISTA로 보는 새로운 시야 : 고객의 목소리를 AI로 구조화하여 만난 인사이트 ...,고객 VoC의 효과적인 사후 분석과 대응을 위해 상담 내역을 기반으로 인사이트와 검...
21,UCqi8fAllvDe9-QCDlhxSg8Q,luk0plb8Urk,2025-11-20T06:00:51Z,2025년 LLM 훈련과 서빙의 진화: 하이퍼스케일 AI 플랫폼 Backend.AI...,거대 언어 모델(LLM)의 급속한 진화로 AI 인프라 플랫폼은 전례 없는 복잡성과 ...
22,UCqi8fAllvDe9-QCDlhxSg8Q,c2FFh6ZWmpM,2025-11-20T06:00:39Z,풀스택 LLM에서 AI 에이전트까지 : 데이터와 자본의 제약을 넘어서기 | 트릴리온...,트릴리온랩스는 작은 스타트업으로서 글로벌에서도 손꼽히는 70B 규모 풀스택 LLM을...
23,UCqi8fAllvDe9-QCDlhxSg8Q,MeOh1esbUg8,2025-11-20T06:00:20Z,"AI 에이전트, A2A로 일하는 세상 | Persona AI 유승재","젠스테이션(Gen Station)은 A2A 구조 기반의 AI 에이전트 솔루션으로, ..."
24,UCqi8fAllvDe9-QCDlhxSg8Q,HLY2cuM1NhA,2025-11-20T06:00:25Z,Physical AI 개발과 도입의 가속화 | Config Intelligence 손형목,곧 출시될 예정인 로봇 데이터·개발 플랫폼 Config Box를 소개합니다. Con...
25,UCqi8fAllvDe9-QCDlhxSg8Q,b01v2Xa8mNk,2025-11-20T06:00:36Z,Ego-View AI: AI/AR 글라스로 산업을 혁신하는 Multi-Agent 시...,AI/AR 글라스의 산업 혁신을 위해서는 복잡한 현장 상황에 대응할 수 있는 멀티 ...
26,UCqi8fAllvDe9-QCDlhxSg8Q,vlnfDZoC-IA,2025-11-20T06:01:01Z,LLM이 추천을 만나면? SKT의 LLM 기반 추천 시스템 개발기 | SK텔레콤 김...,"SK텔레콤은 고객 행동 데이터를 활용해 요금제, T-우주 구독 상품, 멤버십, Tw..."
27,UCqi8fAllvDe9-QCDlhxSg8Q,WFUwTtbuctc,2025-11-20T06:00:36Z,"소프트웨어 개발의 AIX, RFP분석에서 시스템 구현까지, SW Dev. AI Ag...",SK AX는 기존 인간 중심 소프트웨어 개발이 안고 있던 효율성과 품질 문제를 해결...
28,UCqi8fAllvDe9-QCDlhxSg8Q,DQvmReiBjSU,2025-11-20T06:00:17Z,AI Agent를 위한 LLM (LARP) 개발과 Sales Agent 도전기 | ...,"단순한 LLM 챗봇을 넘어, 도구를 활용하고 결정을 내리며 복잡한 작업까지 수행하는..."
29,UCqi8fAllvDe9-QCDlhxSg8Q,bB0RRmtQE0o,2025-11-20T06:00:36Z,TelAgentBench - Telco 도메인 사례로 보는 에이전트 성능 평가 | ...,"LLM 기반 Agent가 빠르게 발전하며 통신 서비스에도 적용되고 있지만, 그 성능..."
30,UCqi8fAllvDe9-QCDlhxSg8Q,XuXHhPiyGe0,2025-11-20T06:00:26Z,"미션 크리티컬한 문제에서의 의사 결정에 도움이 되는 AI : 안보, 재난 영역 사례...",미션 크리티컬한 문제를 해결하기 위해서는 다양한 데이터를 다각도에서 정교하게 연결하...
31,UCqi8fAllvDe9-QCDlhxSg8Q,c5-quBOPgLw,2025-11-20T06:00:28Z,에이전트 월드를 준비하는 에이닷의 현재와 미래 | SK텔레콤 김지훈,SK텔레콤의 대표 AI 에이전트 에이닷(A.Dot)과 이를 둘러싼 에이전트 사업의 ...
32,UCqi8fAllvDe9-QCDlhxSg8Q,pvZ7C5TGOL0,2025-11-20T06:00:48Z,"AI 인프라, 도전을 넘어 신뢰로 (Cloudflare와 함께하는 DDoS 방어와 ...",AI 워크로드를 운영하는 데이터센터는 전통적인 공격과 새로운 위협이 동시에 몰려오는...
33,UCqi8fAllvDe9-QCDlhxSg8Q,NykDXfF3wbU,2025-11-20T06:00:18Z,모두를 위한 AI 최적화! 경량화에서 추론까지 End-to-End AI 최적화 인프...,노타의 혁신적인 AI 모델 최적화 플랫폼 NetsPresso를 소개합니다. Nets...
34,UCqi8fAllvDe9-QCDlhxSg8Q,fuLIi9W08ws,2025-11-20T06:00:39Z,"오픈소스, 강화학습을 만나다: Helpy의 특화 AI 모델 개발 전략 | Elice...","강력한 오픈소스 모델을 누구나 활용할 수 있는 시대가 되었지만, 특정 도메인에 특화..."
35,UCqi8fAllvDe9-QCDlhxSg8Q,3ZZIg8gZuyA,2025-11-20T06:00:02Z,휴머노이드가 바꾸는 산업 현장! AI 로봇 자동화의 경험적 인사이트로 완성하는 휴머...,CMES 휴머노이드 로봇 기술은 다양한 연구 결과들이 선행 기술로 제시되며 빠르게 ...
36,UCqi8fAllvDe9-QCDlhxSg8Q,-LSyy0EwCuE,2025-11-20T06:00:00Z,TMAP AI 모빌리티 데이터로 진화하는 차세대 지능형 교통체계(ITS) | 티맵모...,2500만명의 티맵 사용자로부터 수집된 방대한 모빌리티 데이터를 AI로 학습·가공하...
37,UCqi8fAllvDe9-QCDlhxSg8Q,oFiJCTFuwlw,2025-11-20T06:00:45Z,"MentAI VISION: AI 기반 정신건강 관리 | SK텔레콤 김창현, 정구익",대한민국 정신질환은 심각한 사회적 이슈로 대두되며 정부 차원에서도 대응이 이루어지고...
38,UCqi8fAllvDe9-QCDlhxSg8Q,aJL95Obw6Pw,2025-11-20T06:00:01Z,소리 내어 말하는 LLM: AI와의 자연스러운 대화를 위한 음성합성 기술 | SK텔...,LLM의 전반적 성능 향상으로 다양한 서비스에 빠르게 적용되며 사용자 경험이 크게 ...
39,UCqi8fAllvDe9-QCDlhxSg8Q,tvdCv_-YAhQ,2025-11-20T06:00:51Z,"AI Cloud Manager: 국내 최대 B200 GPU 1,000장 클러스터를 ...",초거대 AI 모델 학습 수요가 급증하면서 많은 기업이 대규모 GPU 클러스터 구축과...
40,UCqi8fAllvDe9-QCDlhxSg8Q,a8WOP2YCrjg,2025-11-20T06:00:01Z,AI 도입 시 마주하는 Legacy Data의 벽: 엔코아가 제안하는 AI Read...,"많은 기업이 AI 도입을 원하지만, 여전히 Legacy 시스템과 데이터의 벽에 가로..."
41,UCqi8fAllvDe9-QCDlhxSg8Q,mFLigW9wVe0,2025-11-20T06:00:45Z,Agentic AI를 통해 바뀌게 될 Car Life의 현재와 미래 | SK텔레콤 윤현상,에이닷에서 자체 개발한 Agentic Workflow를 적용해 한층 똑똑해진 T맵 ...
42,UCqi8fAllvDe9-QCDlhxSg8Q,CfBPWRs7jJU,2025-11-20T06:00:10Z,전략적 데이터의 시대:생성형 AI와 합성데이터로 만드는 산업적 전환점 | GenGe...,"최근 수년간 AI 연구는 눈부신 속도로 발전해 왔으며, Vision Transfor..."
43,UCqi8fAllvDe9-QCDlhxSg8Q,p20BqMHlwoo,2025-11-20T06:00:52Z,회의·강의 환경에서도 정확하게: 에이닷노트 음성인식 성능을 끌어올린 Generati...,AI 기술의 대중화와 함께 음성인식은 단순한 기기 제어를 넘어 업무 효율을 높이는 ...
44,UCqi8fAllvDe9-QCDlhxSg8Q,3mS4WXYottk,2025-11-20T06:00:08Z,"전력망부터 칩까지, AI 데이터센터의 시작 | 슈나이더 일렉트릭 이진환",유틸리티 그리드(한전 공급 전원)에서 고객의 IT와 기계 부하까지 안정적이고 고품질...
45,UCqi8fAllvDe9-QCDlhxSg8Q,ZkcahL6V4Ys,2025-11-20T06:00:38Z,에너지 분야 응용을 위한 대규모 멀티모달 모델(LMMs) | SK텔레콤 조동연,정밀한 용도에 맞는 신소재 발견은 오랫동안 큰 도전 과제로 남아 있습니다. 인공지능...
46,UCqi8fAllvDe9-QCDlhxSg8Q,AKvhfOridVI,2025-11-20T06:00:08Z,AI기반 예측 기술을 통해 내 몸에 맞는 효과적인 항암치료제 찾기 | 임프리메드 임성원,다양한 메디컬 데이터를 기반으로 개발한 머신러닝(ML) 모델들을 통해 환자맞춤형 암...
47,UCqi8fAllvDe9-QCDlhxSg8Q,O9K2gNJ2VfQ,2025-11-20T06:00:31Z,오프라인 유통 매장에서의 AX 적용 사례 | 신세계아이앤씨 김정언,"AI는 세상을 떠들썩하게 만들고 우리 일상의 풍경을 바꾸고 있지만, 실제 유통 매장..."
48,UCqi8fAllvDe9-QCDlhxSg8Q,9e0GRsQu9gc,2025-11-20T06:00:19Z,"내 반려동물에게도 AI가? 내 펫의 반려 AI, 에이닷 펫 출시 | SK텔레콤 조재혁","AI 기술은 이제 사람을 돕는 영역을 넘어, 다양한 분야로 빠르게 확장되고 있습니다..."
49,UCqi8fAllvDe9-QCDlhxSg8Q,HDjp_l8YCi4,2025-11-20T06:00:26Z,"Media AI를 경험하는 지금, Enterprise AI Business의 새로운...","Media AI는 방송국이나 OTT 등 전통적 미디어 산업의 경계를 넘어, 디스플레..."

In [ ]:
video_ids = test2['video_id'].tolist()

get_video_info(youtube_api_key, video_ids=video_ids, save_path='./data/test2_result.csv')

,video_id,title,channel_id,channel_title,description,upload_date,tags,category_id,view_count,like_count,comment_count,duration,definition,content_rating,kmrb_rating,license,embeddable,has_paid_product_placement
0,oI8lPKD8HQc,The Human Factor : 인간다움을 지키며 AI를 구축하는 방법 | MIT...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"AI, 단순한 공학적 과제가 아니라 인간 중심 디자인의 영역이기도 합니다. AI가 ...",2025-11-20T06:00:46Z,,28,99,0,0,PT4M19S,hd,{},None,youtube,True,False
1,eY-IZV8Jizg,거대 연산망 구현을 위한 CPO 기반 차세대 연결 기술로의 진화 | SK하이닉스 이규상,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"Chip 레벨에서 고도화된 협업 구조가 마련되고 있지만, AI 시스템의 물리적 연결...",2025-11-20T06:00:40Z,,28,505,11,1,PT21M14S,hd,{},None,youtube,True,False
2,4wiqhGENzpk,"나만의 AI Worker, 이제는 직접 만든다. Agent를 만드는 Agentic ...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"최근 산업 현장에서는 AI 자동화에 대한 수요가 높지만, 현장 전문가의 IT/AI ...",2025-11-20T06:00:09Z,,28,397,6,0,PT20M31S,hd,{},None,youtube,True,False
3,BPRDY_Z9D_s,AI Readable 데이터와 활용 체계 | SK텔레콤 윤철중,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,SK텔레콤은 데이터를 AI가 이해하고 활용할 수 있는 형태로 전환하는 체계와 과정을...,2025-11-20T06:00:18Z,,28,187,4,0,PT20M4S,hd,{},None,youtube,True,False
4,7U-8YszwidA,"내 AI는 문제가 없을까? AI 상용화의 핵심, 신뢰성 평가 | 셀렉트스타 김세엽",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,AI 서비스 개발에는 품질과 안전성을 보장하기 위한 신뢰성 평가가 필수적입니다. F...,2025-11-20T06:00:14Z,,28,131,4,0,PT20M10S,hd,{},None,youtube,True,False
5,uZPUplLSSzo,AI를 사회적 공간에 배치하기: SNS와 실사용 환경에서의 모델 적용 실험 | TU...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"AI는 이제 정보 제공이나 생산을 넘어, 사람 간 소통이 이뤄지는 서비스 영역으로 ...",2025-11-20T06:00:49Z,,28,58,1,0,PT20M30S,hd,{},None,youtube,True,False
6,0RAz4Ge-9YU,Voice LLM 우리는 무엇을 기대하는가? | SK텔레콤 황성수,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"Voice LLM 연구는 단순히 모델 구조를 선택하는 문제가 아니라, 목표 설정과 ...",2025-11-20T06:00:02Z,,28,190,5,0,PT14M45S,hd,{},None,youtube,True,False
7,Kpra7EWOvkM,"어떤 광고가 돈이 될까? AI 기반 광고 수익 최적화 | SK플래닛 신호준, 윤이연",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"광고 운영, 이제 AI가 알아서 합니다. OK캐쉬백, Syrup, 오락, T멤버십 ...",2025-11-20T06:00:16Z,,28,103,1,0,PT22M20S,hd,{},None,youtube,True,False
8,Jwrz_qXl0f4,"핵심업무에 집중하고, 나머지는 AI에게 맡기세요. 일하는 방식의 혁신, A.Biz ...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,최근 효율적으로 업무를 처리할 수 있는 AI 기반 솔루션에 대한 수요가 빠르게 증가...,2025-11-20T06:00:18Z,,28,177,3,0,PT22M40S,hd,{},None,youtube,True,False
9,iQirlenF19I,"칩에서 쿨링까지, 열을 다스리는 인프라 전략 | 슈나이더 일렉트릭 이창호",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,AI 데이터센터의 고밀도화에 따른 냉각 방식의 변화를 다룹니다. 기존 냉각 방식의 ...,2025-11-20T06:00:41Z,,28,152,1,0,PT21M39S,hd,{},None,youtube,True,False
10,jGEJMX0CgTQ,"차세대 무선망, ‘AI - RAN’ 실현을 위한 핵심 기술 및 연구개발 사례 소개 ...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"AI는 모든 기술 영역으로 확산되고 있으며, 정교하고 복잡한 무선 통신 기술이 집약...",2025-11-20T06:00:43Z,,28,509,7,0,PT22M25S,hd,{},None,youtube,True,False
11,QJAZWOp_dDs,"생성형 AI 추론의 확장: 기술, 최적화, 그리고 실전 교훈 | FriendliAI...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,생성형 AI의 도입이 가속화되고 Agentic AI 시스템이 새로운 추론 수요를 만...,2025-11-20T06:00:20Z,,28,196,5,0,PT20M41S,hd,{},None,youtube,True,False
12,eHkwXyi2ZOc,스마트 에너지와 지능형 운영 인프라 | 슈나이더 일렉트릭 이승윤,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,스마트 센서를 포함한 지능형 전기장치들을 활용하여 기존 전력감시제어 시스템의 기능을...,2025-11-20T06:00:40Z,,28,66,1,0,PT29M7S,hd,{},None,youtube,True,False
13,tYaW-LVjeSw,안심하고 사용할 수 있는 커뮤니케이션 서비스 진화 방향 | SK텔레콤 조현덕,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,전화 서비스에서 고객 만족도가 높았던 스팸 필터링은 이제 AI 기술을 기반으로 한 ...,2025-11-20T06:00:49Z,,28,78,0,0,PT24M55S,hd,{},None,youtube,True,False
14,HqBJX53esCc,생각하는 기계를 위한 운영체제 | VAST Data Renen Hallak,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,AI 데이터 플랫폼 소프트웨어 기업 VAST Data에서 지능적이고 데이터 중심적인...,2025-11-20T06:00:24Z,,28,100,2,0,PT22M27S,hd,{},None,youtube,True,False
15,mZL0hjQ9pbo,A.X LLM with Reasoning | SK텔레콤 조석환,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,초거대 AI 경쟁이 가속화되는 가운데 SK텔레콤은 독자적인 Foundation Mo...,2025-11-20T06:00:46Z,,28,449,5,0,PT20M43S,hd,{},None,youtube,True,False
16,VwE-bIhI_A4,AI x HR : Talent AX가 바꾸는 일과 사람의 미래 | SK AX 김민주,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"AI가 HR의 경계를 넘어, 새로운 가능성을 열고 있습니다. Talent AX는 A...",2025-11-20T06:00:26Z,,28,873,15,0,PT21M21S,hd,{},None,youtube,True,False
17,1lY7kcWTNy4,크래프톤에서의 AI Transformation: 일하는 방식과 프로세스의 AI 기반...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,생성형 AI와 Agent의 등장은 지식 노동의 문법을 근본적으로 바꾸고 있습니다. ...,2025-11-20T06:00:01Z,,28,1081,18,2,PT22M13S,hd,{},None,youtube,True,False
18,gGUxpNhxqDU,"AX를 넘어 BX로, EXAONE이 만드는 금융 및 제약 산업에서의 사업 대혁신 |...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"생성형 AI의 등장은 수많은 새로운 모델 발표와 함께, 클라우드 기반 API 비즈니...",2025-11-20T06:00:27Z,,28,260,0,0,PT21M51S,hd,{},None,youtube,True,False
19,gn0pXvZdg6o,Agentic AI 적용의 첫걸음: 산업별 기회와 실전 가이드 | MakinaRoc...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,생성형 AI의 다음 진화 단계로 주목받는 Agentic AI는 특정 산업과 업무에 ...,2025-11-20T06:00:39Z,,28,169,2,0,PT16M33S,hd,{},None,youtube,True,False
20,Tie_JRjxfUw,VISTA로 보는 새로운 시야 : 고객의 목소리를 AI로 구조화하여 만난 인사이트 ...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,고객 VoC의 효과적인 사후 분석과 대응을 위해 상담 내역을 기반으로 인사이트와 검...,2025-11-20T06:00:34Z,,28,80,4,0,PT21M5S,hd,{},None,youtube,True,False
21,luk0plb8Urk,2025년 LLM 훈련과 서빙의 진화: 하이퍼스케일 AI 플랫폼 Backend.AI...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,거대 언어 모델(LLM)의 급속한 진화로 AI 인프라 플랫폼은 전례 없는 복잡성과 ...,2025-11-20T06:00:51Z,,28,212,9,0,PT20M13S,hd,{},None,youtube,True,False
22,c2FFh6ZWmpM,풀스택 LLM에서 AI 에이전트까지 : 데이터와 자본의 제약을 넘어서기 | 트릴리온...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,트릴리온랩스는 작은 스타트업으로서 글로벌에서도 손꼽히는 70B 규모 풀스택 LLM을...,2025-11-20T06:00:39Z,,28,218,3,0,PT15M52S,hd,{},None,youtube,True,False
23,MeOh1esbUg8,"AI 에이전트, A2A로 일하는 세상 | Persona AI 유승재",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"젠스테이션(Gen Station)은 A2A 구조 기반의 AI 에이전트 솔루션으로, ...",2025-11-20T06:00:20Z,,28,206,6,0,PT11M36S,hd,{},None,youtube,True,False
24,HLY2cuM1NhA,Physical AI 개발과 도입의 가속화 | Config Intelligence 손형목,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,곧 출시될 예정인 로봇 데이터·개발 플랫폼 Config Box를 소개합니다. Con...,2025-11-20T06:00:25Z,,28,1657,14,0,PT25M49S,hd,{},None,youtube,True,False
25,b01v2Xa8mNk,Ego-View AI: AI/AR 글라스로 산업을 혁신하는 Multi-Agent 시...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,AI/AR 글라스의 산업 혁신을 위해서는 복잡한 현장 상황에 대응할 수 있는 멀티 ...,2025-11-20T06:00:36Z,,28,176,9,2,PT20M50S,hd,{},None,youtube,True,False
26,vlnfDZoC-IA,LLM이 추천을 만나면? SKT의 LLM 기반 추천 시스템 개발기 | SK텔레콤 김...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"SK텔레콤은 고객 행동 데이터를 활용해 요금제, T-우주 구독 상품, 멤버십, Tw...",2025-11-20T06:01:01Z,,28,551,13,0,PT20M30S,hd,{},None,youtube,True,False
27,WFUwTtbuctc,"소프트웨어 개발의 AIX, RFP분석에서 시스템 구현까지, SW Dev. AI Ag...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,SK AX는 기존 인간 중심 소프트웨어 개발이 안고 있던 효율성과 품질 문제를 해결...,2025-11-20T06:00:36Z,,28,355,2,0,PT24M5S,hd,{},None,youtube,True,False
28,DQvmReiBjSU,AI Agent를 위한 LLM (LARP) 개발과 Sales Agent 도전기 | ...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"단순한 LLM 챗봇을 넘어, 도구를 활용하고 결정을 내리며 복잡한 작업까지 수행하는...",2025-11-20T06:00:17Z,,28,145,4,0,PT21M4S,hd,{},None,youtube,True,False
29,bB0RRmtQE0o,TelAgentBench - Telco 도메인 사례로 보는 에이전트 성능 평가 | ...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"LLM 기반 Agent가 빠르게 발전하며 통신 서비스에도 적용되고 있지만, 그 성능...",2025-11-20T06:00:36Z,,28,112,5,0,PT22M55S,hd,{},None,youtube,True,False
30,XuXHhPiyGe0,"미션 크리티컬한 문제에서의 의사 결정에 도움이 되는 AI : 안보, 재난 영역 사례...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,미션 크리티컬한 문제를 해결하기 위해서는 다양한 데이터를 다각도에서 정교하게 연결하...,2025-11-20T06:00:26Z,,28,94,0,0,PT25M42S,hd,{},None,youtube,True,False
31,c5-quBOPgLw,에이전트 월드를 준비하는 에이닷의 현재와 미래 | SK텔레콤 김지훈,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,SK텔레콤의 대표 AI 에이전트 에이닷(A.Dot)과 이를 둘러싼 에이전트 사업의 ...,2025-11-20T06:00:28Z,,28,133,1,0,PT24M48S,hd,{},None,youtube,True,False
32,pvZ7C5TGOL0,"AI 인프라, 도전을 넘어 신뢰로 (Cloudflare와 함께하는 DDoS 방어와 ...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,AI 워크로드를 운영하는 데이터센터는 전통적인 공격과 새로운 위협이 동시에 몰려오는...,2025-11-20T06:00:48Z,,28,132,3,0,PT23M54S,hd,{},None,youtube,True,False
33,NykDXfF3wbU,모두를 위한 AI 최적화! 경량화에서 추론까지 End-to-End AI 최적화 인프...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,노타의 혁신적인 AI 모델 최적화 플랫폼 NetsPresso를 소개합니다. Nets...,2025-11-20T06:00:18Z,,28,170,6,0,PT23M58S,hd,{},None,youtube,True,False
34,fuLIi9W08ws,"오픈소스, 강화학습을 만나다: Helpy의 특화 AI 모델 개발 전략 | Elice...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"강력한 오픈소스 모델을 누구나 활용할 수 있는 시대가 되었지만, 특정 도메인에 특화...",2025-11-20T06:00:39Z,,28,51,1,0,PT22M41S,hd,{},None,youtube,True,False
35,3ZZIg8gZuyA,휴머노이드가 바꾸는 산업 현장! AI 로봇 자동화의 경험적 인사이트로 완성하는 휴머...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,CMES 휴머노이드 로봇 기술은 다양한 연구 결과들이 선행 기술로 제시되며 빠르게 ...,2025-11-20T06:00:02Z,,28,80,0,0,PT13M52S,hd,{},None,youtube,True,False
36,-LSyy0EwCuE,TMAP AI 모빌리티 데이터로 진화하는 차세대 지능형 교통체계(ITS) | 티맵모...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"2,500만명의 티맵 사용자로부터 수집된 방대한 모빌리티 데이터를 AI로 학습·가공...",2025-11-20T06:00:00Z,,28,222,0,1,PT21M58S,hd,{},None,youtube,True,False
37,oFiJCTFuwlw,"MentAI VISION: AI 기반 정신건강 관리 | SK텔레콤 김창현, 정구익",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,대한민국 정신질환은 심각한 사회적 이슈로 대두되며 정부 차원에서도 대응이 이루어지고...,2025-11-20T06:00:45Z,,28,88,1,0,PT21M12S,hd,{},None,youtube,True,False
38,aJL95Obw6Pw,소리 내어 말하는 LLM: AI와의 자연스러운 대화를 위한 음성합성 기술 | SK텔...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,LLM의 전반적 성능 향상으로 다양한 서비스에 빠르게 적용되며 사용자 경험이 크게 ...,2025-11-20T06:00:01Z,,28,101,5,0,PT12M56S,hd,{},None,youtube,True,False
39,tvdCv_-YAhQ,"AI Cloud Manager: 국내 최대 B200 GPU 1,000장 클러스터를 ...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,초거대 AI 모델 학습 수요가 급증하면서 많은 기업이 대규모 GPU 클러스터 구축과...,2025-11-20T06:00:51Z,,28,324,11,0,PT21M14S,hd,{},None,youtube,True,False
40,a8WOP2YCrjg,AI 도입 시 마주하는 Legacy Data의 벽: 엔코아가 제안하는 AI Read...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"많은 기업이 AI 도입을 원하지만, 여전히 Legacy 시스템과 데이터의 벽에 가로...",2025-11-20T06:00:01Z,,28,232,5,0,PT19M57S,hd,{},None,youtube,True,False
41,mFLigW9wVe0,Agentic AI를 통해 바뀌게 될 Car Life의 현재와 미래 | SK텔레콤 윤현상,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,에이닷에서 자체 개발한 Agentic Workflow를 적용해 한층 똑똑해진 T맵 ...,2025-11-20T06:00:45Z,,28,142,2,0,PT25M9S,hd,{},None,youtube,True,False
42,CfBPWRs7jJU,전략적 데이터의 시대:생성형 AI와 합성데이터로 만드는 산업적 전환점 | GenGe...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"최근 수년간 AI 연구는 눈부신 속도로 발전해 왔으며, Vision Transfor...",2025-11-20T06:00:10Z,,28,112,3,0,PT21M59S,hd,{},None,youtube,True,False
43,p20BqMHlwoo,회의·강의 환경에서도 정확하게: 에이닷노트 음성인식 성능을 끌어올린 Generati...,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,AI 기술의 대중화와 함께 음성인식은 단순한 기기 제어를 넘어 업무 효율을 높이는 ...,2025-11-20T06:00:52Z,,28,273,7,0,PT19M30S,hd,{},None,youtube,True,False
44,3mS4WXYottk,"전력망부터 칩까지, AI 데이터센터의 시작 | 슈나이더 일렉트릭 이진환",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,유틸리티 그리드(한전 공급 전원)에서 고객의 IT와 기계 부하까지 안정적이고 고품질...,2025-11-20T06:00:08Z,,28,268,1,0,PT22M6S,hd,{},None,youtube,True,False
45,ZkcahL6V4Ys,에너지 분야 응용을 위한 대규모 멀티모달 모델(LMMs) | SK텔레콤 조동연,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,정밀한 용도에 맞는 신소재 발견은 오랫동안 큰 도전 과제로 남아 있습니다. 인공지능...,2025-11-20T06:00:38Z,,28,82,3,0,PT7M30S,hd,{},None,youtube,True,False
46,AKvhfOridVI,AI기반 예측 기술을 통해 내 몸에 맞는 효과적인 항암치료제 찾기 | 임프리메드 임성원,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,다양한 메디컬 데이터를 기반으로 개발한 머신러닝(ML) 모델들을 통해 환자맞춤형 암...,2025-11-20T06:00:08Z,,28,91,0,0,PT15M28S,hd,{},None,youtube,True,False
47,O9K2gNJ2VfQ,오프라인 유통 매장에서의 AX 적용 사례 | 신세계아이앤씨 김정언,UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"AI는 세상을 떠들썩하게 만들고 우리 일상의 풍경을 바꾸고 있지만, 실제 유통 매장...",2025-11-20T06:00:31Z,,28,133,3,0,PT23M34S,hd,{},None,youtube,True,False
48,9e0GRsQu9gc,"내 반려동물에게도 AI가? 내 펫의 반려 AI, 에이닷 펫 출시 | SK텔레콤 조재혁",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"AI 기술은 이제 사람을 돕는 영역을 넘어, 다양한 분야로 빠르게 확장되고 있습니다...",2025-11-20T06:00:19Z,,28,101,1,0,PT18M59S,hd,{},None,youtube,True,False
49,HDjp_l8YCi4,"Media AI를 경험하는 지금, Enterprise AI Business의 새로운...",UCqi8fAllvDe9-QCDlhxSg8Q,SK AI SUMMIT 2025,"Media AI는 방송국이나 OTT 등 전통적 미디어 산업의 경계를 넘어, 디스플레...",2025-11-20T06:00:26Z,,28,52,1,0,PT22M44S,hd,{},None,youtube,True,False